
[core]
copyFrom:ROOT:\data\templates\builderEffect.template, ROOT:\data\templates\gatherer.template, ROOT:\data\templates\unitXp.template, ROOT:\data\templates\drowning.template, ROOT:\data\templates\unitInventory.template
name: highpeakEquuxiBuilder_1
tags: bio, cavalry, normalVision, miner, famulus, builder
displayText: Famulus
displayDescription: -Can build and repair structures\n -Can mine emeralds\n -Fast
class: CustomUnitMetadata
price: Food=125, Lodging=1
borrowResourcesWhileBuilt:Lodging=1
maxHp: 190
selfRegenRate:0
armour:2
mass: 100
radius: 6
softCollisionOnAll: 6

techLevel: 1
experimental: false
buildSpeed: 14s

isBio: true
isBug: false
hideScorchMark: true

isBuilder: true
autoRepair: true
nanoRepairSpeed: 0.05
nanoBuildSpeed: 0.6
canRepairBuildings: true
canRepairUnits:true
canRepairUnitsOnlyWithTags:machine, building
nanoRange: 60

effectOnDeath:CUSTOM:death, CUSTOM:blood*3
unitsSpawnedOnDeath:neutralDead

[effect_death]
life: 0
spawnChance:0.40
alpha:0
alsoPlaySound:ROOT:\data\soundFx\deathHorse1.ogg:0.05, ROOT:\data\soundFx\deathHorse2.ogg:0.05


[effect_blood]
attachedToUnit: false
life: 60
physics: true
scaleFrom:1.1
scaleTo: 0.2
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.5
hSpeed: 1
image: ROOT:\data\images\bloodRed.png
drawUnderUnits:false

[canBuild_base]
name: repair, reclaim, highpeakEquuxiFarm, highpeakEquuxiForge, highpeakMine, highpeakEquuxiCenter, highpeakEquuxiSchool_1, highpeakEquuxiSchool_2, highpeakEquuxiWorkshop
pos: 1.1

[canBuild_Flodrjinai]
isVisible: if self.numberOfUnitsInAllyNotOwnTeam(withTag='factionFlodrjinai', greaterThan=0)
name: highpeakFlodrjinaiBarracks
pos: 1.1

[canBuild_campfire]
isVisible:  if numberOfUnitsInNeutralTeam(withTag='winter', greaterThan=0)
name: highpeakNeutralcampfire
pos: 1.2

[effect_buildArcane]
teamColorRatio:1
alwayStartDirAtZero:true
fadeInTime:60
dirOffsetRandom:360
hOffset:0
attachedToUnit: true
life: 140
alpha: 1
scaleFrom:0.75
scaleTo: 0.1
#hSpeedRandom: -0.1
dirSpeed:0.5
image: ROOT:\data\images\buildArcane.png
priority: high
drawUnderUnits:false

[effect_buildArcane2]
teamColorRatio:1
alwayStartDirAtZero:true
fadeInTime:30
dirOffsetRandom:360
hOffset:0
attachedToUnit: true
life: 80
alpha: 1
scaleFrom:0.75
scaleTo: 0.9
#hSpeedRandom: -0.1
dirSpeed:-0.5
image: ROOT:\data\images\buildArcane.png
priority: high
drawUnderUnits:true

[graphics]
imageScale: 0.7
total_frames: 5
showEnergyBar:false
image:        body.png
image_wreak:  ROOT:\data\images\skeletonHorse.png
image_turret: NONE

image_shadow: SHADOW:ROOT:\data\images\shadowHorse.png
shadowOffsetX:1
shadowOffsetY:1

repairEffectAtTarget:CUSTOM:buildArcane, CUSTOM:buildArcane2
repairEffectRate:45


animation_moving_start: 1
animation_moving_end: 2
animation_moving_speed: 4
animation_moving_pingPong: true

animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 120
animation_idle_scale_start:1
animation_idle_scale_end:1.03
animation_idle_pingPong: true

animation_attack_start: 0
animation_attack_end: 3
animation_attack_speed: 5
animation_attack_pingPong: true

lock_body_rotation_with_main_turret: true

[attack]

canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
isFixedFiring: true
turretSize: 8
turretTurnSpeed: 3

maxAttackRange: 1
shootDelay: 1s

[movement]
movementType: LAND
moveSpeed: 1
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.05
joinsGroupFormations: true

maxTurnSpeed: 8.5
turnAcceleration: 2.5

moveSlidingMode :false
moveIgnoringBody:false
moveSlidingDir:  180
reverseSpeedPercentage:0

[ai]
useAsBuilder:true

[animation_repair]
onActions : repair

body_0s: {frame:2}
body_0.1s: {frame:2}
body_0.5s: {frame:4} 
body_0.8s: {frame:4}

