[core]
copyFrom: ROOT:\data\templates\unitXp.template
name: highpeakDvarikWalker_2
displayText: Velite
tags:machine, normalVision
displayDescription: -Siege machine\n -Well armored\n -Good vs buildings and large\n -Trample damage while it moves\n -Fast moving, slow turning
class: CustomUnitMetadata
price: Emerald=400, Gazul=200, Lodging=1
borrowResourcesWhileBuilt:Lodging=1

maxHp: 200
armour: 5
armourMinDamageToKeep: 0
mass: 3000

techLevel: 1
buildSpeed: 16s
radius: 14
isBio: false
isBug: false
fogOfWarSightRange: 18
hideScorchMark: false
selfRegenRate:0
softCollisionOnAll: 12

################################# Information #################################

################################# Abilities #################################

[hiddenAction_smoke]
autoTrigger:true
spawnEffects:CUSTOM:smoke*3

[hiddenAction_claddingShield]
autoTrigger: if self.resource(type='blackCladdingLayer')>=2 and not (self.tags(includes='shield') or self.tags(includes='plate'))
temporarilyAddTags: shield

[hiddenAction_claddingPlate]
autoTrigger: if self.resource(type='blackCladdingLayer')>=4 and not self.tags(includes='plate')
temporarilyAddTags: plate
temporarilyRemoveTags: shield

[action_bulldozer]
iconImage:ROOT:\data\images\bulldozerIcon.png
displayType:action
isVisible: if not self.tags(includes='bulldozer')
allowMultipleInQueue:false
whenBuilding_cannotMove:true
ai_isDisabled:true
price: BlackIron=350
temporarilyAddTags:bulldozer
text: Bulldozer
description: -Use Black Iron ingots to install bulldozer plate\n -Increases charge damage
buildSpeed: 45s
pos: 0.5
spawnEffects: CUSTOM:blackIronUpgrade

[action_blackCladding]
iconImage:ROOT:\data\images\platedPlus.png
displayType:action
isVisible: true
isLocked: if self.resource(type='blackCladdingLayer')>=5
isLockedMessage: Maximum 5 layers
allowMultipleInQueue:false
whenBuilding_cannotMove:true
ai_isDisabled:true
price: BlackIron=90
addResources: blackCladdingLayer=1
setUnitStats: maxHp+=20, hp+=20, moveSpeed-=${ movement.moveSpeed * 0.03 }
text: Black Cladding
description: -Use Black Iron ingots to increase hp by 20\n -New layers of cladding slow down the unit\n -Unit becomes Shielded at 2 layers, and Plated at 4 layers\n -Maximum 5 layers
buildSpeed: 20s
pos: 0.5
spawnEffects: CUSTOM:blackIronUpgrade

[hiddenAction_dvarLegsTechTrigger]
autoTrigger:if self.globalTeamTags(includes='dvarikLegsTech') and not self.tags(includes='DvarLegsTech')
setUnitStats: moveSpeed+=${movement.moveSpeed * 0.1}
temporarilyAddTags: DvarLegsTech

################################# Graphics #################################

[graphics]
total_frames: 1
imageScale: 0.9
scaleTurretImagesTo: 15
image_turret:turret.png
teamColorsOnTurret: true
image:        body.png
image_wreak:  ROOT:\data\images\medium_dead_wood.png
image_shadow: AUTO
shadowOffsetX:2
shadowOffsetY:3
showTransportBar:false

movementEffect:CUSTOM:smoke*2
movementEffectRate:10

animation_moving_start: 0
animation_moving_end: 0
animation_moving_speed: 10
animation_moving_scale_start:1
animation_moving_scale_end:1.01

animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 15
animation_idle_scale_start:1
animation_idle_scale_end:1.01

[effect_trail]
atmospheric:true
createWhenZoomedOut: false
color:#ff4e00
image: ROOT:\data\images\trail.png
life: 120
fadeOut: true
attachedToUnit: false
fadeInTime:2
scaleFrom: 0.7
scaleTo: 0.5
alpha: 0.6
drawUnderUnits:false

[effect_smoke]
xOffsetRelative:6
yOffsetRelative:-9
attachedToUnit: false
life: 150
alpha: 0.5
scaleFrom:0.3
scaleTo: 1.6
xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.1
hSpeed: 0.1
image: ROOT:\data\images\smoke.png
priority: low
drawUnderUnits:false
atmospheric:true

[effect_blackIronUpgrade]
alsoPlaySound:ROOT:\data\soundFx\equipWeapon.ogg:0.15
fadeInTime:10
alwayStartDirAtZero:true
attachedToUnit: true
life: 30
alpha: 1
image: ROOT:\data\images\upgrade.png
priority: high
drawUnderUnits:true
scaleFrom:0.6
scaleTo: 1.4

################################# Attacks #################################

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
aimOffsetSpread:0
turretSize: 11
turretTurnSpeed: 0
isFixedFiring: true
maxAttackRange: 275
shootDelay: 4s

[turret_1]
x:0
y:0
canShoot:false
invisible:true

[turret_main]
x:0
y:2
shoot_flame:small
shoot_sound: ROOT:\data\soundFx\shootGun.ogg
shoot_sound_vol:0.15
recoilOffset: -3
recoilOutTime: 4
recoilReturnTime: 18
turnSpeed:2
limitingAngle:15
projectile:1

[projectile_1]
mutatorLarge_ifUnitWithTags:large
mutatorLarge_directDamageMultiplier:2.5

lightColor:#ff7200
directDamage:30
armourIgnoreAmount:5
life: 200
speed: 4
buildingDamageMultiplier: 2.5
image:bullet.png
drawSize:1.0
shadowFrame:11
trailEffect:CUSTOM:trail
trailEffectRate:1

wobbleAmplitude: 0.3
wobbleFrequency: 0.6s

initialUnguidedSpeedHeight: 1
gravity:0.25

mutatorFire_ifUnitWithTags: canBurn
mutatorFire_addResourcesDirectHit: Fire=8



[hiddenAction_charge]
autoTrigger:if self.isMoving()
fireTurretXAtGround: charge
fireTurretXAtGround_withOffset:0,50

[turret_charge]
x: 0
y: 0
size:0
canShoot:false
invisible: true
projectile: charge
turnSpeed: 40

[projectile_charge]
life: 140
speed: 10
drawSize: 0
targetGround:true
explodeEffect:NONE
deflectionPower: -1
areaDamage: 25
areaRadius: 25
buildingDamageMultiplier:0
mutator1_ifUnitWithTags:shield
mutator1_areaDamageMultiplier:0.5
mutator2_ifUnitWithTags:cavalry
mutator2_areaDamageMultiplier:0



[hiddenAction_bulldozerCharge]
autoTrigger:if self.isMoving() and self.tags(includes='bulldozer')
fireTurretXAtGround: bulldozerCharge
fireTurretXAtGround_withOffset:0,50

[turret_bulldozerCharge]
x: 0
y: 0
size:0
canShoot:false
invisible: true
projectile: bulldozerCharge
turnSpeed: 40

[projectile_bulldozerCharge]
life: 140
speed: 10
drawSize: 0
targetGround:true
explodeEffect:NONE
deflectionPower: -1
areaDamage: 35
areaRadius: 35
buildingDamageMultiplier:1
mutator1_ifUnitWithTags:shield
mutator1_areaDamageMultiplier:0.5
mutator2_ifUnitWithTags:cavalry
mutator2_areaDamageMultiplier:0

################################# Limbs #################################

[leg_1]
x: -9
y: -1
attach_x: 5
attach_y: -2
rotateSpeed:100
moveSpeed: 2.8
resetAngle:5
heightSpeed: 1
dust_effect: false
holdDisMin: 5
holdDisMax: 15
hardLimit: 15
holdDisMin_maxMovingLegs:1
hold_moveOnlyIfFurthest:true
estimatingPositionMultiplier:0.54
endDirOffset:180
draw_foot_on_top:true
image_leg:  leg.png
image_foot:  foot.png

[leg_2]
x: 9
y: -1
attach_x: -5
attach_y: -2
copyFrom: 1

endDirOffset:180

[leg_3]
x: 0
y: 12
attach_x: 0
attach_y: 5
copyFrom: 1

endDirOffset:0

[arm_1]
x: 0.5
y: 15
drawOverBody:true


[arm_9]
hidden: if not self.tags(includes='bulldozer')
x: 0.35
y: 17
drawOverBody:true
image_end:  ROOT:\data\images\bulldozer.png

################################# Movement #################################

[movement]
movementType: OVER_CLIFF
moveSpeed: 0.7
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.06
maxTurnSpeed: 0.75
turnAcceleration: 0.3
moveSlidingMode :true
moveIgnoringBody:false
moveSlidingDir:  181
reverseSpeedPercentage:0