
[core]
name: highpeakDvarikWorkshop
tags:building, dvarikFactory
class: CustomUnitMetadata
price: Emerald=850
maxHp: 2200
mass: 9000

displayText: Foundry
displayDescription: "War is an art. Here we mold our masterpieces."\n\n -Can train war machines

techLevel: 1
buildSpeed: 20s

radius: 35
footprint: -1,-1,1,1
constructionFootprint: -1,-1,1,2
buildingToFootprintOffsetX:10
buildingToFootprintOffsetY:0

isBuilding: true
isBio: false
numBitsOnDeath: 5


exit_y:35

################################# Training #################################

[canBuild_1]
isLocked: false
name:setRally,highpeakDvarikDrill_1, highpeakDvarikDrill_2, highpeakDvarikWalker_1
pos: 0.1
addResources: Lodging=1

[canBuild_2]
isLocked: false
name: highpeakDvarikDrill_2
pos: 0.2
addResources: Lodging=2



[canBuild_3]
isLocked: if not self.tags(includes='dvarikFoundryUpgrade')
isLockedMessage: Foundry upgrade required
name:highpeakDvarikWalker_2
pos: 0.2
addResources: Lodging=1

[canBuild_4]
isLocked: if not self.tags(includes='dvarikFoundryUpgrade')
isLockedMessage: Foundry upgrade required
name:highpeakDvarikChariot_1, highpeakDvarikAirship_1
pos: 0.4
addResources: Lodging=2

[canBuild_5]
isLocked: if not self.tags(includes='dvarikFoundryUpgrade')
isLockedMessage: Foundry upgrade required
name:highpeakDvarikwarMachine_2
pos: 0.4
addResources: Lodging=8



[canBuild_ai]
name:highpeakDvarikWalker_1_ai
pos: 0.5
isVisible:if self.isControlledByAI()
addResources: Lodging=1

[canBuild_ai2]
name:highpeakDvarikChariot_1_ai, highpeakDvarikAirship_1_ai
pos: 0.6
isVisible:if self.isControlledByAI()
addResources: Lodging=2

[canBuild_ai3]
name:highpeakDvarikwarMachine_2_ai
pos: 0.7
isVisible:if self.isControlledByAI()
addResources: Lodging=8

################################# Abilities #################################

[hiddenAction_smoke]
autoTrigger:true
spawnEffects:CUSTOM:smoke*3

[action_dvarikFoundryUpgrade]
iconImage: back.png
iconExtraImage: base.png
isVisible: if not self.tags(includes='dvarikFoundryUpgrade')
temporarilyAddTags: dvarikFoundryUpgrade
text: Upgrade Foundry
description: -Upgrade Foundry to produce more advanced vehicles\n -Additionally, increase health
buildSpeed: 60s
price: Emerald=450
setUnitStats: maxHp+=500, hp+=500

[hiddenAction_reinforceTech]
autoTrigger: if self.globalTeamTags(includes='dvarikBuildingTech') and not self.tags(includes='reinforced')
temporarilyAddTags: reinforced
setUnitStats: hp+=${core.maxHp*0.25}, maxHp+=${core.maxHp*0.25}

################################# Graphics #################################

[graphics]
total_frames: 1
imageScale: 0.9

image:        base.png
image_back:  back.png
image_wreak:  NONE
image_turret: NONE

image_shadow: NONE
shadowOffsetX:0
shadowOffsetY:0

[effect_smoke]
xOffsetRelative:5
yOffsetRelative:-19
attachedToUnit: false
life: 400
alpha: 0.3
scaleFrom:0.5
scaleTo: 2
#physics: true
xSpeedRelativeRandom: 0.07
ySpeedRelativeRandom: 0.07
hSpeed: 0.1
image: ROOT:\data\images\smoke.png
priority: low
drawUnderUnits:false
atmospheric:true
fadeInTime:40

################################# Weapons #################################

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

turretSize: 0
turretTurnSpeed: 1


maxAttackRange: 0
shootDelay: 2s

################################# Movement #################################

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0
turnAcceleration: 0.1



[ai]

buildPriority: 0.30

noneGlobalExtraPriority: 0.1

maxEachBase: 1