[core]
copyFrom: ROOT:\data\templates\unitXp.template
name: highpeakDvarikChariot_1
displayText: Testudo
tags:machine, normalVision, large
displayDescription: -Large machine\n -Well armed and armored\n -Fire attack\n -Trample damage while it moves\n -Good vs buildings \n -Can garrison units
class: CustomUnitMetadata
price: Emerald=450, Gazul=250, Lodging=2
borrowResourcesWhileBuilt:Lodging=2

maxHp: 500
armour: 15
armourMinDamageToKeep: 1
mass: 3000

maxTransportingUnits:6
transportUnitsRequireTag:infantry, small
transportUnitsCanUnloadUnits:if not self.isOverLiquid()
transportUnitsUnloadDelayBetweenEachUnit:6

techLevel: 1
buildSpeed: 16s
radius: 17
isBio: false
isBug: false
fogOfWarSightRange: 18
hideScorchMark: false
selfRegenRate:0
softCollisionOnAll: 12

################################# Information #################################

[action_fire]
iconImage:ROOT:\data\images\fireIcon.png
displayType:action
pos:0.5
text: Fire
description: Passive\n -Can set buildings on fire, dealing damage over time
buildSpeed: 0s
isVisible: true

[action_unstoppable]
iconImage:ROOT:\data\images\bulldozerIconClean.png
displayType:action
pos:1
text: Unstoppable Force
description: Passive\n -This unit may not be stunned, slowed, or confused in any way
buildSpeed: 0s
isVisible: if self.tags(includes='Unstoppable')

[action_dvarikPlated]
iconImage:ROOT:\data\images\plated.png
displayType:action
pos:1
text: Plated
description: Passive\n -This unit is extremely resistant to small projectiles
buildSpeed: 0s
isVisible: if self.tags(includes='plate')

[action_dvarikShield]
iconImage:ROOT:\data\images\shield.png
displayType:action
pos:1
text: Shield
description: Passive\n -This unit is resistant to small projectiles
buildSpeed: 0s
isVisible: if self.tags(includes='shield')


################################# Abilities #################################

[action_refit]
iconImage:ROOT:\data\images\shieldPlus.png
displayType:action
isVisible: true
isLocked: if not self.numberOfUnitsInTeam(withinRange=90, greaterThan=0, withTag='dvarikFactory')
isLockedMessage: Must be close to a Foundry
allowMultipleInQueue: false
whenBuilding_cannotMove: true
ai_isDisabled: true
price: BlackIron=350, lodging=1
text: Refit Testudo
description: -Refit this Testudo, strengthening its weapon and armor, but removing its transport capacity.
convertTo:highpeakDvarikwarMachine_1
convertTo_keepCurrentFields: maxHp, moveSpeed
convertTo_keepCurrentTags: true
setUnitStats: maxHp+=100, hp+=100, armour+=3
pos:0.5
addResources: lodging=1
buildSpeed: 30s

[action_blackCladding]
iconImage:ROOT:\data\images\platedPlus.png
displayType:action
isVisible: true
isLocked: if self.resource(type='blackCladdingLayer')>=5
isLockedMessage: Maximum 5 layers
allowMultipleInQueue:false
whenBuilding_cannotMove:true
ai_isDisabled:true
price: BlackIron=150
addResources: blackCladdingLayer=1
setUnitStats: maxHp+=50, hp+=50, moveSpeed-=${ movement.moveSpeed * 0.03 }
text: Black Cladding
description: -Use Black Iron ingots to increase hp by 50\n -New layers of cladding slow down the unit\n -Unit becomes Shielded at 2 layers, and Plated at 4 layers\n -Maximum 5 layers
buildSpeed: 20s
pos: 0.5
spawnEffects: CUSTOM:blackIronUpgrade

[action_bulldozer]
iconImage:ROOT:\data\images\bulldozerIcon.png
displayType:action
isVisible: if not self.tags(includes='bulldozer')
allowMultipleInQueue:false
whenBuilding_cannotMove:true
ai_isDisabled:true
price: BlackIron=350
temporarilyAddTags:bulldozer
text: Bulldozer
description: -Use Black Iron ingots to install bulldozer plate\n -Increases charge damage
buildSpeed: 45s
pos: 0.5
spawnEffects: CUSTOM:blackIronUpgrade

[hiddenAction_smoke]
autoTrigger:true
spawnEffects:CUSTOM:smoke*3

[hiddenAction_dvarLegsTechTrigger]
autoTrigger:if self.globalTeamTags(includes='dvarikLegsTech') and not self.tags(includes='DvarLegsTech')
setUnitStats: moveSpeed+=${movement.moveSpeed * 0.1}
temporarilyAddTags: DvarLegsTech, Unstoppable
pos:0.6

[hiddenAction_claddingShield]
autoTrigger: if self.resource(type='blackCladdingLayer')>=2 and not (self.tags(includes='shield') or self.tags(includes='plate'))
temporarilyAddTags: shield

[hiddenAction_claddingPlate]
autoTrigger: if self.resource(type='blackCladdingLayer')>=4 and not self.tags(includes='plate')
temporarilyAddTags: plate
temporarilyRemoveTags: shield

################################# Graphics #################################

[graphics]
total_frames: 1
imageScale: 0.9
teamColorsOnTurret: true
image:        body.png
image_wreak:  ROOT:\data\images\medium_dead_wood.png
image_turret: mainTurret.png
image_shadow: AUTO
shadowOffsetX:2
shadowOffsetY:3
showTransportBar:false

movementEffect:CUSTOM:smoke*2
movementEffectRate:10

animation_moving_start: 0
animation_moving_end: 0
animation_moving_speed: 10
animation_moving_scale_start:1
animation_moving_scale_end:1.01

animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 15
animation_idle_scale_start:1
animation_idle_scale_end:1.01

[effect_trail]
atmospheric:true
createWhenZoomedOut: false
color:#ff4e00
image: ROOT:\data\images\trail.png
life: 90
fadeOut: true
attachedToUnit: false
fadeInTime:2
scaleFrom: 0.5
scaleTo: 0.2
alpha: 0.6
drawUnderUnits:false

[effect_smoke]
xOffsetRelative:-8
yOffsetRelative:-13
attachedToUnit: false
life: 150
alpha: 0.5
scaleFrom:0.3
scaleTo: 1.6
xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.1
hSpeed: 0.1
image: ROOT:\data\images\smoke.png
priority: low
drawUnderUnits:false
atmospheric:true

[effect_blackIronUpgrade]
alsoPlaySound:ROOT:\data\soundFx\equipWeapon.ogg:0.15
fadeInTime:10
alwayStartDirAtZero:true
attachedToUnit: true
life: 30
alpha: 1
image: ROOT:\data\images\upgrade.png
priority: high
drawUnderUnits:true
scaleFrom:0.6
scaleTo: 1.4

################################# Attacks #################################

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
isFixedFiring:true
aimOffsetSpread:0
turretSize: 11
turretTurnSpeed: 0
maxAttackRange: 150
shootDelay: 1.5s

[turret_1]
x:0
y:4
shoot_flame:small
shoot_sound: ROOT:\data\soundFx\flameThrower.ogg
shoot_sound_vol:0.15
recoilOffset: -3
recoilOutTime: 4
recoilReturnTime: 18
projectile:1

[projectile_1]
lightColor:#ff7200
directDamage:60
armourIgnoreAmount:5
life: 200
speed: 4
image: ROOT:\data\images\ember.png
buildingDamageMultiplier: 1.5
drawSize:0.9
shadowFrame:11
trailEffect:CUSTOM:trail
trailEffectRate:1

wobbleAmplitude: 0.5
wobbleFrequency: 0.3s

initialUnguidedSpeedHeight: 1
gravity:0.18

mutatorFire_ifUnitWithTags: canBurn
mutatorFire_addResourcesDirectHit: Fire=5



[hiddenAction_charge]
autoTrigger:if self.isMoving()
fireTurretXAtGround: charge
fireTurretXAtGround_withOffset:0,50

[turret_charge]
x: 0
y: 0
size:0
canShoot:false
invisible: true
projectile: charge
turnSpeed: 40

[projectile_charge]
life: 140
speed: 10
drawSize: 0
targetGround:true
explodeEffect:NONE
deflectionPower: -1
areaDamage: 75
areaRadius: 35
buildingDamageMultiplier:0
mutator1_ifUnitWithTags:shield
mutator1_areaDamageMultiplier:0.5
mutator2_ifUnitWithTags:cavalry
mutator2_areaDamageMultiplier:0



[hiddenAction_bulldozerCharge]
autoTrigger:if self.isMoving() and self.tags(includes='bulldozer')
fireTurretXAtGround: bulldozerCharge
fireTurretXAtGround_withOffset:0,50

[turret_bulldozerCharge]
x: 0
y: 0
size:0
canShoot:false
invisible: true
projectile: bulldozerCharge
turnSpeed: 40

[projectile_bulldozerCharge]
life: 140
speed: 10
drawSize: 0
targetGround:true
explodeEffect:NONE
deflectionPower: -1
areaDamage: 35
areaRadius: 45
buildingDamageMultiplier:1
mutator1_ifUnitWithTags:shield
mutator1_areaDamageMultiplier:0.5
mutator2_ifUnitWithTags:cavalry
mutator2_areaDamageMultiplier:0

################################# Attachments #################################

[attachment_1]
x: -6
y: 9
idleDir:0
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
setDrawLayerOnTop:true
addTransportedUnits:true
rotateWithParent:true

[attachment_2]
x: 6
y: 9
idleDir:0
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
setDrawLayerOnTop:true
addTransportedUnits:true
rotateWithParent:true

[attachment_3]
x: -8
y: 1
idleDir:0
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
setDrawLayerOnTop:true
addTransportedUnits:true
rotateWithParent:true


[attachment_4]
x: 8
y: 1
idleDir:0
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
setDrawLayerOnTop:true
addTransportedUnits:true
rotateWithParent:true

[attachment_5]
x: -5
y: -7
idleDir:0
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
setDrawLayerOnTop:true
addTransportedUnits:true
rotateWithParent:true

[attachment_6]
x: 5
y: -7
idleDir:0
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
setDrawLayerOnTop:true
addTransportedUnits:true
rotateWithParent:true

################################# Limbs #################################

[leg_1]
x: -12
y: 10
attach_x: -4
attach_y: 10
rotateSpeed:100
moveSpeed: 2.8
resetAngle:5
heightSpeed: 1
dust_effect: false
holdDisMin: 5
holdDisMax: 15
hardLimit: 15
holdDisMin_maxMovingLegs:1
hold_moveOnlyIfFurthest:true
estimatingPositionMultiplier:0.54
endDirOffset:0
draw_foot_on_top:true
image_leg:  leg.png
image_foot:  foot.png

[leg_2]
x: 12
y: 10
attach_x: 4
attach_y: 10
copyFrom: 1

endDirOffset:0

[leg_3]
x: -10
y: -10
attach_x: -4
attach_y: -10
copyFrom: 1

endDirOffset:180

[leg_4]
x: 10
y: -10
attach_x: 4
attach_y: -10
copyFrom: 1

endDirOffset:180

[arm_9]
hidden: if not self.tags(includes='bulldozer')
x: 0
y: 21
drawOverBody:true
image_end:  ROOT:\data\images\bulldozer.png

################################# Movement #################################

[movement]
movementType: OVER_CLIFF
moveSpeed: 0.8
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.06
maxTurnSpeed: 1
turnAcceleration: 0.5
moveSlidingMode :true
moveIgnoringBody:false
moveSlidingDir:  181
reverseSpeedPercentage:0