
[core]
name: highpeakTheWizardHouse
tags: building, house, sanctum, canBurn
class: CustomUnitMetadata
price: Emerald=350
maxHp: 2000
mass: 9000

displayText: Laboratory
displayDescription: "A place for study of the great alchemy..."\n\n -Can train minions\n -Can transmute resources\n -Provides 3 lodging\n -Can be raised from the ground as a new tower\n -Can only be built on Gazul veins

techLevel: 1
buildSpeed: 20s
placeOnlyOnResPool: true

borrowResourcesWhileBuilt:lodging=-3

radius: 30

isBuilding: true
isBio: false
numBitsOnDeath: 5

exit_y:25

[canBuild_mageLesserTower]
isVisible: if game.nukesEnabled() and self.globalTeamTags(includes='factionTheWizard')
name: highpeakTheWizardMageTowerLesser
isLocked: if numberOfUnitsInTeam(withTag='wizardTower', greaterThan=0, factoryQueue=true)
isLockedMessage:The tower still stands
pos:2
addResources: hp=-10000

[canBuild_hero]
name: highpeakTheWizardHero
isVisible: if self.globalTeamTags(includes='factionTheWizard')
isLocked: if numberOfUnitsInTeam(withTag='hero', greaterThan=0, factoryQueue=true)
isLockedMessage:Your explorer is alive
pos:2

[canBuild_builder]
name: setRally, highpeakTheWizardBuilder_1
pos: 2.2
addResources: Lodging=1

[hiddenAction_aiBoost]
autoTrigger: if self.resource(type='Gazul',lessThan=2000) or self.resource(type='Emerald',lessThan=2000)
requireConditional: if self.isControlledByAI()
addResources:Emerald=2, Gazul=2

[action_impPowder]
isVisible: if self.globalTeamTags(includes='factionTheWizard') and not self.globalTeamTags(includes='impPowder')
allowMultipleInQueue:false

iconImage:ROOT:\data\images\fireIcon.png
addGlobalTeamTags:impPowder
displayType: upgrade
price:  Amber=15, Ruby=25, Sapphire=15
text: Imp powder
description:Triple minion's attack damage and add fire effect
buildSpeed: 120s
pos:0.3


#----------------------------(transmutation actions)-------------------------------------#
[hiddenAction_transmutation]
autoTrigger: if not self.tags(includes='transmutation')
temporarilyAddTags:generateGazul, transmutation


[action_generateGazul]
iconImage:ROOT:\data\images\gazulIcon.png
isGuiBlinking: if self.tags(includes='generateGazul')
isLocked: if self.tags(includes='generateGazul')
text: Extract->Gazul
description:-Generate gazul trickles
price:0
buildSpeed:5s
temporarilyRemoveTags:generateEmerald, generateAmber, generateRuby, generateSapphire, generateCoin
temporarilyAddTags:generateGazul
pos:20

[action_generateEmerald]
iconImage:ROOT:\data\images\emeraldIcon.png
isGuiBlinking: if self.tags(includes='generateEmerald')
isLocked: if self.tags(includes='generateEmerald')
text: Transmute->Emerald
description:-Transmute gazul trickles into emerald
price:0
buildSpeed:5s
temporarilyRemoveTags:generateGazul, generateAmber, generateRuby, generateSapphire, generateCoin
temporarilyAddTags:generateEmerald
pos:20

[action_generateCoin]
isVisible: if self.numberOfUnitsInAllyNotOwnTeam(withTag='factionFlodrjinai', greaterThan=0) or self.globalTeamTags(includes='factionFlodrjinai')
iconImage:ROOT:\data\images\coinIcon.png
isGuiBlinking: if self.tags(includes='generateCoin')
isLocked: if self.tags(includes='generateCoin')
text: Transmute->Coin
description:-Transmute gazul trickles into coin
price:0
buildSpeed:5s
temporarilyRemoveTags:generateGazul, generateEmerald, generateAmber, generateRuby, generateSapphire
temporarilyAddTags:generateCoin
pos:20

[action_generateAmber]
isVisible: if self.globalTeamTags(includes='earthLore')
iconImage:ROOT:\data\images\amberIcon.png
isGuiBlinking: if self.tags(includes='generateAmber')
isLocked: if self.tags(includes='generateAmber')
text: Transmute->Amber
description:-Transmute gazul trickles into amber
price:0
buildSpeed:5s
temporarilyRemoveTags:generateGazul, generateEmerald, generateRuby, generateSapphire, generateCoin
temporarilyAddTags:generateAmber
pos:20

[action_generateRuby]
isVisible: if self.globalTeamTags(includes='fireLore')
iconImage:ROOT:\data\images\rubyIcon.png
isGuiBlinking: if self.tags(includes='generateRuby')
isLocked: if self.tags(includes='generateRuby')
text: Transmute->Ruby
description:-Transmute gazul trickles into ruby
price:0
buildSpeed:5s
temporarilyRemoveTags:generateGazul, generateEmerald, generateAmber, generateSapphire, generateCoin
temporarilyAddTags:generateRuby
pos:20

[action_generateSapphire]
isVisible: if self.globalTeamTags(includes='iceLore')
iconImage:ROOT:\data\images\sapphireIcon.png
isGuiBlinking: if self.tags(includes='generateSapphire')
isLocked: if self.tags(includes='generateSapphire')
text: Transmute->Sapphire
description:-Transmute gazul trickles into sapphire
price:0
buildSpeed:5s
temporarilyRemoveTags:generateGazul, generateEmerald, generateAmber, generateRuby, generateCoin
temporarilyAddTags:generateSapphire
pos:20



#----------------------------(transmutation timers)-------------------------------------#

[hiddenAction_gazulTimer]
autoTrigger: if self.customTimer(laterThanSeconds=5) and self.tags(includes='generateGazul')
alsoTriggerAction: gazulLvL1
resetCustomTimer:true
[hiddenAction_gazulLvL1]
addResourcesScaledByAIHandicaps: Gazul=10
spawnEffects:CUSTOM:produceGazul

[effect_produceGazul]
alwayStartDirAtZero:true
attachedToUnit: false
life: 100
alpha: 1
hOffset:16
hSpeed: 0.3
image: ROOT:\data\images\gazul10.png
priority: high
drawUnderUnits:false
scaleFrom:1.2
scaleTo: 1.2

[hiddenAction_emeraldTimer]
autoTrigger: if self.customTimer(laterThanSeconds=5) and self.tags(includes='generateEmerald')
alsoTriggerAction: emeraldLvL1
resetCustomTimer:true
[hiddenAction_emeraldLvL1]
addResourcesScaledByAIHandicaps: Emerald=10
spawnEffects:CUSTOM:produceEmerald

[effect_produceEmerald]
alwayStartDirAtZero:true
attachedToUnit: false
life: 100
alpha: 1
hOffset:16
hSpeed: 0.3
image: ROOT:\data\images\emerald10.png
priority: high
drawUnderUnits:false
scaleFrom:1.2
scaleTo: 1.2

[hiddenAction_amberTimer]
autoTrigger: if self.customTimer(laterThanSeconds=5) and self.tags(includes='generateAmber')
alsoTriggerAction: amberLvL1
resetCustomTimer:true
[hiddenAction_amberLvL1]
requireConditional:if self.resource(type='Amber',lessThan=100)
addResourcesScaledByAIHandicaps: amber=1
spawnEffects:CUSTOM:produceAmber

[effect_produceAmber]
alwayStartDirAtZero:true
attachedToUnit: false
life: 100
alpha: 1
hOffset:16
hSpeed: 0.3
image: ROOT:\data\images\amber10.png
priority: high
drawUnderUnits:false
scaleFrom:1.2
scaleTo: 1.2

[hiddenAction_rubyTimer]
autoTrigger: if self.customTimer(laterThanSeconds=5) and self.tags(includes='generateRuby')
alsoTriggerAction: rubyLvL1
resetCustomTimer:true
[hiddenAction_rubyLvL1]
requireConditional:if self.resource(type='Ruby',lessThan=100)
addResourcesScaledByAIHandicaps: ruby=1
spawnEffects:CUSTOM:produceRuby

[effect_produceRuby]
alwayStartDirAtZero:true
attachedToUnit: false
life: 100
alpha: 1
hOffset:16
hSpeed: 0.3
image: ROOT:\data\images\ruby10.png
priority: high
drawUnderUnits:false
scaleFrom:1.2
scaleTo: 1.2

[hiddenAction_sapphireTimer]
autoTrigger: if self.customTimer(laterThanSeconds=5) and self.tags(includes='generateSapphire')
alsoTriggerAction: sapphireLvL1
resetCustomTimer:true
[hiddenAction_sapphireLvL1]
requireConditional:if self.resource(type='Sapphire',lessThan=100)
addResourcesScaledByAIHandicaps: sapphire=1
spawnEffects:CUSTOM:produceSapphire

[effect_produceSapphire]
alwayStartDirAtZero:true
attachedToUnit: false
life: 100
alpha: 1
hOffset:16
hSpeed: 0.3
image: ROOT:\data\images\sapphire10.png
priority: high
drawUnderUnits:false
scaleFrom:1.2
scaleTo: 1.2

[hiddenAction_coinTimer]
autoTrigger: if self.customTimer(laterThanSeconds=9) and self.tags(includes='generateCoin')
alsoTriggerAction: coinLvL1
resetCustomTimer:true
[hiddenAction_coinLvL1]
addResourcesScaledByAIHandicaps: coins=10
spawnEffects:CUSTOM:produceCoin

[effect_produceCoin]
alwayStartDirAtZero:true
attachedToUnit: false
life: 100
alpha: 1
hOffset:16
hSpeed: 0.3
image: ROOT:\data\images\coin10.png
priority: high
drawUnderUnits:false
scaleFrom:1.2
scaleTo: 1.2



[graphics]
total_frames: 1
imageScale: 1

image:        base.png
image_back:  base.png
image_wreak:  NONE
image_turret: NONE

image_shadow: NONE
shadowOffsetX:0
shadowOffsetY:0



[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

turretSize: 0
turretTurnSpeed: 1


maxAttackRange: 0
shootDelay: 2s


[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0
turnAcceleration: 0.1



[ai]

buildPriority: 0.4

noneGlobalExtraPriority: 0.2