
[core]
copyFrom: ROOT:\data\templates\unitXp.template
name: highpeakHauntingInfantry_1
tags: undead, infantry, normalVision, etheral
displayText: Haunter
displayDescription: -Etheral infantry\n -Well armored\n -Good vs infantry\n -Can move over water
class: CustomUnitMetadata
price: Gazul=100, Spirit=1
maxHp: 450
selfRegenRate:0
armour:-1
mass: 120
radius: 5
softCollisionOnAll: 50

techLevel: 1
experimental: false
buildSpeed: 8s

explodeOnDeathGroundCollision:false
effectOnDeathGroundCollision:NONE

isBio: true
isBug: false
hideScorchMark: true
effectOnDeath:CUSTOM:death, CUSTOM:deathFog*3
unitsSpawnedOnDeath:neutralDead

[effect_death]
life: 0
spawnChance:0.40
alpha:0
alsoPlaySound:ROOT:\data\soundFx\deathHaunt.ogg:0.075, ROOT:\data\soundFx\deathHaunt2.ogg:0.075, ROOT:\data\soundFx\deathHaunt3.ogg:0.075, ROOT:\data\soundFx\deathHaunt4.ogg:0.1


[effect_deathFog]
fadeInTime:20
color:#81f7ff
attachedToUnit: false
alpha:0.5
life: 70
scaleFrom:0.7
scaleTo: 0.1
xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.1
hSpeed: 0.1
image: ROOT:\data\images\smoke.png
drawUnderUnits:false

[hiddenAction_returnOnDeath]
requireConditional: if numberOfUnitsInTeam(withTag='selector', greaterThan=0)
autoTriggerOnEvent: destroyed
spawnUnits: highpeakHauntingWisp_1

[action_etheralInfo]
iconImage:ROOT:\data\images\etheralIcon.png
displayType:action
pos:1
text: Etheral
description: Passive\n -Become a shade if not anchored\n -A shade is fragile and slow
buildSpeed: 0s
isVisible: true

[hiddenAction_etheralStealth]
autoTrigger:if (numberOfUnitsInTeam(withTag='lodestone', withinRange=200, lessThan=1) and numberOfUnitsInTeam(withTag='marker', withinRange=125, lessThan=1))
convertTo:highpeakHauntingInfantry_1_stealth

[graphics]
imageScale: 0.8
total_frames: 5

movementEffect:CUSTOM:deathFog
movementEffectRate:15

image:        body.png
image_wreak:  NONE
image_turret: NONE

image_shadow: SHADOW:ROOT:\data\images\shadow.png
shadowOffsetX:1
shadowOffsetY:2


animation_moving_start: 1
animation_moving_end: 3
animation_moving_speed: 7

animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 120
animation_idle_scale_start:1
animation_idle_scale_end:1.03
animation_idle_pingPong: true

animation_attack_start: 2
animation_attack_end: 4
animation_attack_speed: 5
animation_attack_pingPong: true

lock_body_rotation_with_main_turret: true


[attack]

canAttack: true
canAttackFlyingUnits: if self.isFlying()
canAttackLandUnits:  if self.isAtGroundHeight()
canAttackUnderwaterUnits: false
isFixedFiring: true
isMelee:true
meleeEngangementDistance:120
turretSize: 8
turretTurnSpeed: 3

maxAttackRange: 8
shootDelay: 1s

[turret_1]
x: 0
y: 0
shoot_sound:ROOT:\data\soundFx\maceHit.ogg, ROOT:\data\soundFx\maceHit2.ogg, ROOT:\data\soundFx\axeHit3.ogg
shoot_sound_vol:0.05
recoilOffset:3
recoilOutTime: 15
recoilReturnTime: 18

[projectile_1]
directDamage: 22
armourIgnoreAmount:0
life: 10
instant:true
explodeEffect:NONE


[movement]
movementType: HOVER
targetHeight:2
targetHeightDrift:1
moveSpeed: 0.8
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.05
joinsGroupFormations: false

maxTurnSpeed: 8.5
turnAcceleration: 2.5

moveSlidingMode :false
moveIgnoringBody:false
moveSlidingDir:  180
reverseSpeedPercentage:0

#------------------------------------(ai)-----------------------------------------------------

[hiddenAction_aiHaunting]

autoTrigger:if self.isControlledByAI() and not self.hasActiveWaypoint(type='guard')
addWaypoint_type:guard
addWaypoint_target_nearestUnit_tagged: livinglodestone
addWaypoint_target_nearestUnit_team: own
addWaypoint_target_nearestUnit_maxRange:800
clearAllWaypoints:true
addWaypoint_triggerActionIfFailed: aiHaunting2

[hiddenAction_aiHaunting2]

autoTrigger:if self.isControlledByAI() and not self.hasActiveWaypoint(type='guard')
addWaypoint_type:guard
addWaypoint_target_nearestUnit_tagged: marker
addWaypoint_target_nearestUnit_team: own
addWaypoint_target_nearestUnit_maxRange:400
clearAllWaypoints:true
addWaypoint_triggerActionIfFailed: aiHaunting3

[hiddenAction_aiHaunting3]

autoTrigger:if self.isControlledByAI() and not self.hasActiveWaypoint(type='guard')
addWaypoint_type:guard
addWaypoint_target_nearestUnit_tagged: lodestone
addWaypoint_target_nearestUnit_team: own
addWaypoint_target_nearestUnit_maxRange:200
clearAllWaypoints:true





