
[core]
name: highpeakOrcFlyNest
tags:canBurn, building
class: CustomUnitMetadata
price: Emerald=1200
maxHp: 2200
mass: 9000

displayText: Flarg Nest
displayDescription: "Flarg live here. Yes... its made of dung"\n\n -Can train flaggorts and flargs

techLevel: 1
buildSpeed: 20s

radius: 35
footprint: -1,-1,1,1
constructionFootprint: -1,-1,1,2
buildingToFootprintOffsetX:10
buildingToFootprintOffsetY:0

isBuilding: true
isBio: false
numBitsOnDeath: 5


exit_y:15

[hiddenAction_smoke]
autoTrigger:true
spawnEffects:CUSTOM:smoke*3

[effect_smoke]
color:#d3c88a
xOffsetRelativeRandom:20
yOffsetRelativeRandom:20
attachedToUnit: false
life: 400
alpha: 0.3
scaleFrom:1
scaleTo: 2
#physics: true
xSpeedRelativeRandom: 0.07
ySpeedRelativeRandom: 0.07
hSpeed: 0.1
image: ROOT:\data\images\smoke.png
priority: low
drawUnderUnits:false
atmospheric:true
fadeInTime:40

[canBuild_1]
name:setRally, highpeakOrcMaggot_1
pos: 0.1
addResources: Lodging=1

[canBuild_2]
name:highpeakOrcFly_1
pos: 0.2
addResources: Lodging=2

[canBuild_3]
name:highpeakOrcFly_2
pos: 0.3
addResources: Lodging=4
isLocked: if self.numberOfUnitsInTeam(withTag='tech', lessThan=1)
isLockedMessage: Requires an Eatery


[canBuild_ai1]
name:setRally, highpeakOrcMaggot_1_ai
pos: 0.1
isVisible:if self.isControlledByAI()
addResources: Lodging=1

[canBuild_ai2]
name:highpeakOrcFly_1_ai
pos: 0.2
isVisible:if self.isControlledByAI()
addResources: Lodging=2

[canBuild_ai3]
name:highpeakOrcFly_2_ai
pos: 0.3
isVisible:if self.isControlledByAI()
addResources: Lodging=4

[graphics]
total_frames: 1
imageScale: 0.86

image:        base.png
image_back:  back.png
image_wreak:  NONE
image_turret: NONE

image_shadow: NONE
shadowOffsetX:0.5
shadowOffsetY:2



[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

turretSize: 0
turretTurnSpeed: 1


maxAttackRange: 0
shootDelay: 2s


[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0
turnAcceleration: 0.1



[ai]

buildPriority: 0.30

noneGlobalExtraPriority: 0.1

maxEachBase: 1