
[core]
copyFrom: ROOT:\data\templates\unitXp.template, ROOT:\data\templates\drowning.template
name: highpeakTheWizardSiege_1
tags: magical, normalVision
displayText: Ice cannon
displayDescription: -Long ranged construct \n -Good vs buildings\n -Slow
class: CustomUnitMetadata
price: Emerald=700, Gazul=450, Sapphire=30
maxHp: 250
armour:8
mass: 1000

techLevel: 1
experimental: false
buildSpeed: 25s

transportSlotsNeeded:2

radius: 12
isBio: false
isBug: false
fogOfWarSightRange: 18
hideScorchMark: true
selfRegenRate:0
softCollisionOnAll: 12
explodeOnDeath:false
effectOnDeath: CUSTOM:iceSpark*5

[hiddenAction_iceSpark]
spawnEffects: CUSTOM:iceSpark*3
autoTrigger:true

[effect_iceSpark]
attachedToUnit: false
life: 80
scaleFrom:0.7
scaleTo: 0
xOffsetRelativeRandom: 8
yOffsetRelativeRandom: 8
hOffset: 2
dirOffsetRandom:25
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.3
ySpeedRelative: 0.1
hSpeed: 0.1
image: ROOT:\data\images\snowFlake2.png
drawUnderUnits:true
fadeInTime:15

[graphics]
teamColorsOnTurret: true
imageScale: 0.85
total_frames: 1

image:        body.png
image_wreak:  ROOT:\data\images\water.png
image_turret: NONE

movementEffect:CUSTOM:iceSpark
movementEffectRate:5

#AUTO
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:2

lock_body_rotation_with_main_turret: true

[attack]

canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
isFixedFiring: true
turretSize: 14
turretTurnSpeed: 3

maxAttackRange: 305
shootDelay: 1.5s

[turret_1]
x: 0
y: 0
shoot_sound:ROOT:\data\soundFx\crystalShards.ogg
shoot_sound_vol:0.1
recoilOffset:-3
recoilOutTime: 7
recoilReturnTime: 50
projectile:main
limitingMinRange:50
warmup:30
chargeEffectImage:ROOT:\data\images\magicBall.png

[projectile_main]

mutatorShield_ifUnitWithTags:shield
mutatorShield_areaDamageMultiplier:0.5

mutatorPlate_ifUnitWithTags:plate
mutatorPlate_areaDamageMultiplier:0.5

areaDamage:75
areaHitAirAndLandAtSameTime:true
areaRadius:15
targetGround:true
targetGround_includeTargetHeight:true
targetGroundSpread:14
lightColor:#c3ddef
armourIgnoreAmount:-8

life: 120
speed: 5
speedSpread:1
image: projectile.png

buildingDamageMultiplier: 3
drawSize:0.8
shadowFrame:11
trailEffect:CUSTOM:trail
trailEffectRate:1
initialUnguidedSpeedHeight: 1
gravity:0.18

explodeEffect:CUSTOM:effectFreezingBomb*2

mutatorFire_ifUnitWithTags: bio
mutatorFire_addResourcesAreaHit: Freezing=3

[effect_effectFreezingBomb]
attachedToUnit: true
life: 10
alpha: 1
hOffset:1
xOffsetRelativeRandom:3
yOffsetRelativeRandom:3
hSpeed: 0.2
xSpeedRelativeRandom:0.1
ySpeedRelativeRandom:0.1
dirSpeed:0.4
dirSpeedRandom:0.3
dirOffsetRandom:360
fadeInTime:2
image: ROOT:\data\images\snowFlake.png
priority: high
drawUnderUnits:false
scaleFrom:1
scaleTo: 2

[effect_trail]
createWhenZoomedOut: false
color:#c3ddef
image: ROOT:\data\images\trail.png
life: 20
fadeOut: true
attachedToUnit: false
fadeInTime:2
scaleFrom: 0.7
scaleTo: 0.2
alpha: 0.6
drawUnderUnits:false

[movement]
movementType: LAND
moveSpeed: 0.5
targetHeight:1
targetHeightDrift:0.5
moveAccelerationSpeed: 0.05
moveDecelerationSpeed: 0.01
maxTurnSpeed: 2
turnAcceleration: 0.1
moveSlidingMode :true
moveIgnoringBody:true
moveSlidingDir:  181
reverseSpeedPercentage:0

[arm_1]
x: -4
y: 2.5
drawUnderAllUnits: true
spinRate:-1

[decal_body1]
onlyWhileAlive:true
order:0
imageScale:0.8
xOffsetRelative:0
yOffsetRelative:0
hOffset:0
layer: beforeBody
imageStack: wheel2.png
stack_hOffset:0.4
teamColors:true
basePositionFromLegEnd:arm_1

image_shadow: SHADOW:wheel.png
shadowOffsetX:0
shadowOffsetY:0

[arm_2]
x: 4
y: 2.5
drawUnderAllUnits: true
spinRate:1

[decal_body2]
onlyWhileAlive:true
order:0
imageScale:0.8
xOffsetRelative:0
yOffsetRelative:0
hOffset:0
layer: beforeBody
imageStack: wheel2.png
stack_hOffset:0.4
teamColors:true
basePositionFromLegEnd:arm_2

image_shadow: SHADOW:wheel.png
shadowOffsetX:0
shadowOffsetY:0

[arm_3]
x: 0
y: -1
drawUnderAllUnits: true
spinRate:1

[decal_body3]
onlyWhileAlive:true
order:0
imageScale:0.65
xOffsetRelative:0
yOffsetRelative:0
hOffset:0
layer: afterBody
imageStack: wheel.png
stack_hOffset:0.4
teamColors:true
basePositionFromLegEnd:arm_3

image_shadow: SHADOW:wheel.png
shadowOffsetX:0
shadowOffsetY:0



