
[core]
name: highpeakTheConspiracyCenter
tags: center, canBurn, building, dropoff
class: CustomUnitMetadata
price: Emerald:750
maxHp: 3000
mass: 9000

displayText: Hive
displayDescription: "Huddle huddle! Gather to scheme!"\n\n-Generates cave dwellers\n-Can train sappers\n -Randomly spawns acid miasma in a very large area\n -Can house sappers to gain the acid rain ability\n-Resource dropoff


techLevel: 1
buildSpeed: 15s

radius: 60
footprint: -2,-2,2,1
constructionFootprint: -2,-2,2,2
buildingToFootprintOffsetX:10
buildingToFootprintOffsetY:0
fogOfWarSightRange: 5

transportUnitsCanUnloadUnits:if self.queueSize(lessThan=1)
maxTransportingUnits:10
transportUnitsRequireTag:builder
transportUnitsKillOnDeath:false

isBuilding: true
isBio: false
numBitsOnDeath: 5

exit_y:20
exit_moveAwayAmount:40

[hiddenAction_caveDwellersTimer]
autoTrigger: if self.customTimer(laterThanSeconds=9)
alsoTriggerAction: caveDwellersLvL1
resetCustomTimer:true
[hiddenAction_caveDwellersLvL1]
requireConditional:if self.resource(type='CaveDwellers',lessThan=100)
addResourcesScaledByAIHandicaps: caveDwellers=1
spawnEffects:CUSTOM:produceCaveDwellers

[effect_produceCaveDwellers]
alwayStartDirAtZero:true
attachedToUnit: false
life: 100
alpha: 1
hOffset:16
hSpeed: 0.3
image: ROOT:\data\images\caveDwellers10.png
priority: high
drawUnderUnits:false
scaleFrom:1.2
scaleTo: 1.2

[canBuild_builder]
name: setRally, highpeakTheConspiracyBuilder_1
pos: 2.2

[canBuild_hero]
name: highpeakTheConspiracyHero
isLocked: if numberOfUnitsInTeam(withTag='hero', greaterThan=0, factoryQueue=true)
isLockedMessage:Your explorer is alive
pos:2

[hiddenAction_miasma]
autoTrigger:true
spawnEffects:CUSTOM:miasma
fireTurretXAtGround: miasma
fireTurretXAtGround_withOffset:0,0

[effect_miasma]
dirOffsetRandom:360
xOffsetRelative:7
yOffsetRelative:53
attachedToUnit: false
life: 200
alpha: 0.3
scaleFrom:0.75
scaleTo: 3
xSpeedRelativeRandom: 0.07
ySpeedRelativeRandom: 0.07
hSpeed: 0.25
image: ROOT:\data\images\miasma.png
priority: low
drawUnderUnits:false
atmospheric:true
fadeInTime:40
alsoEmitEffects:CUSTOM:miasma2, CUSTOM:miasma3

[effect_miasma2]
dirOffsetRandom:360
xOffsetRelative:-15
yOffsetRelative:35
attachedToUnit: false
life: 200
alpha: 0.35
scaleFrom:0.5
scaleTo: 3
xSpeedRelativeRandom: 0.12
ySpeedRelativeRandom: 0.12
hSpeed: 0.25
image: ROOT:\data\images\miasma.png
priority: low
drawUnderUnits:false
atmospheric:true
fadeInTime:40

[effect_miasma3]
dirOffsetRandom:360
xOffsetRelative:18
yOffsetRelative:25
attachedToUnit: false
life: 200
alpha: 0.35
scaleFrom:0.5
scaleTo: 3
xSpeedRelativeRandom: 0.12
ySpeedRelativeRandom: 0.12
hSpeed: 0.25
image: ROOT:\data\images\miasma.png
priority: low
drawUnderUnits:false
atmospheric:true
fadeInTime:40

[graphics]
total_frames: 1
imageScale: 0.9

image:        base.png
image_back:  back.png
image_wreak:  NONE
image_turret: NONE

image_shadow: SHADOW:shadow.png
shadowOffsetX:0
shadowOffsetY:0

[attack]

canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

turretSize: 0
turretTurnSpeed: 20

maxAttackRange: 300
shootDelay: 2s

[turret_miasma]
x: 0
y: 0
projectile:miasma

[projectile_miasma]
mutatorAcid_ifUnitWithTags: bio, magical, machine, building, boneConstruct
mutatorAcid_addResourcesAreaHit: Acid=5

areaDamage:50
areaRadius:40
targetGround:true
areaHitAirAndLandAtSameTime:true
targetGroundSpread:300
life: 150
explodeOnEndOfLife:true
speed: 20
explodeEffect: CUSTOM:crack, CUSTOM:crackSpread*5, CUSTOM:miasmaTrail*3
drawSize:0

[effect_crack]
fadeInTime:25
alwayStartDirAtZero:true
priority:high
attachedToUnit: false
life: 90
scaleFrom:0.75
scaleTo: 0.75
#dirOffsetRandom:360
image: ROOT:\data\images\crack.png
drawUnderUnits:true

[effect_crackSpread]
attachedToUnit: false
fadeInTime:35
life: 60
scaleFrom:0.5
scaleTo: 0.5
dirOffsetRandom:360
image: ROOT:\data\images\crack.png
alpha:0.5
drawUnderUnits:true
xOffsetAbsoluteRandom:14
yOffsetAbsoluteRandom:14

[effect_miasmaTrail]
fadeInTime:50
dirOffsetRandom:360
xOffsetRelativeRandom:7
yOffsetRelativeRandom:7
attachedToUnit: false
life: 125
alpha: 0.35
scaleFrom:1
scaleTo: 3
hSpeed: 0.25
xSpeedRelativeRandom:0.12
ySpeedRelativeRandom:0.12
image: ROOT:\data\images\miasma.png
priority: high
drawUnderUnits:false
atmospheric:true


[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0
turnAcceleration: 0.1



[ai]

buildPriority: 0.55

noneInBaseExtraPriority: 0.25

maxEachBase: 1

[arm_8]
x: 0
y: 0
spinRate:-0.5
image_end: ROOT:\data\images\miasmaFogLarge.png
drawUnderAllUnits: false

#-------------------------------------------------(animation)----------------------------------------------------

[animation_erupting]
effect_0s:{name:CUSTOM|miasmaEruption}
effect_0.25s:{name:CUSTOM|miasmaEruption}
[effect_miasmaEruption]
dirOffsetRandom:360
xOffsetRelative:7
yOffsetRelative:53
attachedToUnit: false
life: 450
alpha: 0.3
scaleFrom:0.75
scaleTo: 5
xSpeedRelativeRandom: 0.07
ySpeedRelativeRandom: 0.07
hSpeed: 0.5
image: ROOT:\data\images\miasma.png
priority: low
drawUnderUnits:false
atmospheric:true
fadeInTime:40
alsoEmitEffects:CUSTOM:miasmaEruption2, CUSTOM:miasmaEruption3

[effect_miasmaEruption2]
dirOffsetRandom:360
xOffsetRelative:-15
yOffsetRelative:35
attachedToUnit: false
life: 450
alpha: 0.35
scaleFrom:0.5
scaleTo: 5
xSpeedRelativeRandom: 0.12
ySpeedRelativeRandom: 0.12
hSpeed: 0.5
image: ROOT:\data\images\miasma.png
priority: low
drawUnderUnits:false
atmospheric:true
fadeInTime:40

[effect_miasmaEruption3]
dirOffsetRandom:360
xOffsetRelative:18
yOffsetRelative:25
attachedToUnit: false
life: 450
alpha: 0.35
scaleFrom:0.5
scaleTo: 5
xSpeedRelativeRandom: 0.12
ySpeedRelativeRandom: 0.12
hSpeed: 0.5
image: ROOT:\data\images\miasma.png
priority: low
drawUnderUnits:false
atmospheric:true
fadeInTime:40

#-------------------------------------------------(acidRain)----------------------------------------------------
[turret_acidRain]
x: 0
y: 0
canShoot:false
limitingRange:3000

[action_acidRain]
iconImage:ROOT:\data\images\trophy.png
isLocked: if self.transportingCount(lessThan=10)
isLockedMessage: Requires 10 sappers
displayType: action
price: Gazul=75
text: Acid rain
description: -Spawn a cloud of deadly acid rain at target location\n -The cloud becomes less accurate over great distances\n -Requires 10 sappers\n -Friendly fire\n -Cannot be aborted
playSoundToPlayerOnQueue:ROOT:\data\soundFx\flamethrower.ogg:0.7
whenBuilding_playAnimation:erupting
fireTurretXAtGround: acidRain
fireTurretXAtGround_withProjectile:acidRainClose
buildSpeed: 5s
canPlayerCancel:false
pos: 1
onlyOneUnitAtATime: true
whenBuilding_cannotMove:true
addActionCooldownTime:120s
allowMultipleInQueue: false

[projectile_acidRainClose]
areaDamage:10
areaHitAirAndLandAtSameTime:true
areaRadius:180
targetGround:true
targetGroundSpread: 0
armourIgnoreAmount:0
life: 45
speed: 22
color:red
image: ROOT:\data\images\smoke.png
largeHitEffect:true
buildingDamageMultiplier: 100
drawSize:0
spawnProjectilesOnEndOfLife:acidRainMedium
spawnUnit:highpeakAcidRain
pushVelocity:-1

explodeEffect: NONE

[projectile_acidRainMedium]
@copyFromSection: projectile_acidRainClose
targetGroundSpread: 100
spawnProjectilesOnEndOfLife:acidRainFar
color:yellow
[projectile_acidRainFar]
@copyFromSection: projectile_acidRainClose
spawnProjectilesOnEndOfLife:IGNORE
targetGroundSpread: 300
life: 1000
color:green