
[core]
copyFrom: ROOT:\data\templates\unitXp.template
name: highpeakGoblinBomber_1
tags: machine, normalVision, canBurn
displayText: Bomb-O Copter
displayDescription: -Flying machine\n -Well armed\n -Good vs buildings and plated
class: CustomUnitMetadata
price: Emerald=450, Gazoo=250, Lodging=2
borrowResourcesWhileBuilt:Lodging=2
maxHp: 300
selfRegenRate:0
armour:8
mass: 1000
radius: 13
softCollisionOnAll: 75

techLevel: 1
experimental: false
buildSpeed: 20s

energyMax: 1
energyRegen: 0.003
energyNeedsToRechargeToFull: true

isBio: false
isBug: false
hideScorchMark: false
effectOnDeath:CUSTOM:death, CUSTOM:blood*3

[effect_death]
life: 0
spawnChance:0.40
alpha:0
alsoPlaySound:ROOT:\data\soundFx\deathTrog.ogg:0.05

[effect_blood]
attachedToUnit: false
life: 60
physics: true
scaleFrom:1.1
scaleTo: 0.2
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.5
hSpeed: 1
image: ROOT:\data\images\bloodRed.png
drawUnderUnits:false

[hiddenAction_smoke]
autoTrigger:true
spawnEffects:CUSTOM:smoke*2

[effect_smoke]
xOffsetRelative:-3
yOffsetRelative:-9
attachedToUnit: false
life: 100
alpha: 0.2
scaleFrom:0.4
scaleTo: 1.5
#physics: true
xSpeedRelativeRandom: 0.2
ySpeedRelativeRandom: 0.2
hSpeed: 0.1
image: ROOT:\data\images\smokeGazoo.png
priority: low
drawUnderUnits:false
atmospheric:true

[graphics]
showEnergyBar:false
imageScale: 0.9
total_frames: 1

movementEffect:CUSTOM:smoke*2
movementEffectRate:10

image:        body.png
image_wreak:  NONE
image_turret: NONE

image_shadow: AUTO
shadowOffsetX:0
shadowOffsetY:0


animation_moving_start: 0
animation_moving_end: 0
animation_moving_speed: 5
animation_moving_scale_start:1
animation_moving_scale_end:1.03

animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 10
animation_idle_scale_start:1
animation_idle_scale_end:1.03

[attack]

canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: true

turretSize: 10
turretTurnSpeed: 1.5

maxAttackRange: 45
shootDelay: 30

attackMovement: bomber

[turret_1]
#bomber
invisible: true
x: 0
y: 0
idleDir:0


projectile: 1
size: 1.1
turnSpeed: 20

energyUsage: 1

[projectile_1]
areaDamage:100
areaHitAirAndLandAtSameTime:true
areaRadius:25
targetGround:true
targetGroundSpread:15
life: 120
speed: 2
image: ROOT:\data\images\shell.png
largeHitEffect:true
buildingDamageMultiplier: 2.5
drawSize:0.9
initialUnguidedSpeedHeight: -0.1
gravity:0.18
shadowFrame:11
lightColor:#ffffff
lightSize:0.2


[movement]
movementType: AIR
moveSpeed: 1.2
moveAccelerationSpeed: 0.02
moveDecelerationSpeed: 0.01
joinsGroupFormations: true

targetHeightDrift:3

maxTurnSpeed: 2.5
turnAcceleration: 1

moveSlidingMode :false
moveIgnoringBody:false
moveSlidingDir:  100
reverseSpeedPercentage:0

[arm_1]
x: 0
y: -10
image_end: foot.png
drawOverBody: true
image_foot_shadow:SHADOW:foot.png
spinRate:15



