
[core]
copyFrom:ROOT:\data\templates\builderEffect.template
name: highpeakLonguiTech
tags: canBurn, building, workshop
class: CustomUnitMetadata
price: Emerald=500, gazul=250	
maxHp: 2200
mass: 9000

displayText: LonguiTech
displayDescription: ""\n -Can research technology

techLevel: 1
buildSpeed: 20s

radius: 30
footprint: -2,-1,1,0
constructionFootprint: -2,-1,1,1
buildingToFootprintOffsetX:0
buildingToFootprintOffsetY:0

isBuilding: true
isBio: false
numBitsOnDeath: 5

canRepairUnitsOnlyWithTags:machine
autoRepair: true
nanoRepairSpeed: 0.1
nanoBuildSpeed: 1
canRepairBuildings: false
canRepairUnits: true
nanoRange: 100


exit_y:30
exit_moveAwayAmount:40

################################# Techs #################################

[action_wineTech]
isVisible: if not self.globalTeamTags(includes='longuiWineTech')
iconImage:ROOT:\data\images\ranged.png
displayType:action
pos:1
text: Bulk Wine Production
price: emerald=350, gazul=400
description: Houses generate additional wine
addGlobalTeamTags: longuiWineTech
buildSpeed: 60s

[action_arrowTech]
isVisible: if not self.globalTeamTags(includes='longuiArrowTech')
iconImage:ROOT:\data\images\ranged.png
displayType:action
pos:1
text: Rocket Propelled Arrows
price: emerald=500, gazul=300
description: Increase range of Shoubie and Tieyu
addGlobalTeamTags: longuiArrowTech
buildSpeed: 120s

[action_hangoverTech]
isVisible: if not self.globalTeamTags(includes='longuiHangoverTech')
iconImage:ROOT:\data\images\ranged.png
displayType:action
pos:1
text: Experienced Drinkers
price: emerald=550, gazul=450
description: Longui units can no longer get hungover
addGlobalTeamTags: longuiHangoverTech
buildSpeed: 120s

################################# Graphics #################################

[hiddenAction_smoke]
autoTrigger:true
spawnEffects:CUSTOM:smoke*3

[effect_smoke]
xOffsetRelative:33
yOffsetRelative:22
attachedToUnit: false
life: 300
alpha: 0.4
scaleFrom:0.1
scaleTo: 2
#physics: true
xSpeedRelativeRandom: 0.07
ySpeedRelativeRandom: 0.07
hSpeed: 0.1
image: ROOT:\data\images\smoke.png
priority: low
drawUnderUnits:false
atmospheric:true


[graphics]
total_frames: 1
imageScale: 0.9

image:        base.png
image_back:  back.png
image_wreak:  NONE
image_turret: NONE

image_shadow: SHADOW:shadow.png
shadowOffsetX:0
shadowOffsetY:0.5

################################# Attack #################################

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
turretSize: 10
turretTurnSpeed: 20
maxAttackRange: 100
shootDelay: 1

################################# Movement #################################

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0
turnAcceleration: 0.1

################################# Ai #################################

[ai]

buildPriority: 0.30

noneGlobalExtraPriority: 0.1

maxEachBase: 1