
[core]
name: highpeakDvarikBlackIron
tags: highpeakForge, canSellTrophy, building, dropoff
class: CustomUnitMetadata
price: Emerald=700, Gazul=250
maxHp: 2000
mass: 9000

displayText: Black Iron Forge
displayDescription: "The forges are ever burning to sustain the machines of war."\n\n -Generates Black Iron\n -Black Iron is used to upgrade war machines

techLevel: 1
buildSpeed: 15s

radius: 30
footprint: -1,-1,1,1
constructionFootprint: -1,-1,1,1
buildingToFootprintOffsetX:10
buildingToFootprintOffsetY:10

isBuilding: true
isBio: false
numBitsOnDeath: 5

exit_y:30

[hiddenAction_blackIronTimer]
autoTrigger: if self.customTimer(laterThanSeconds=10)
alsoTriggerAction: blackIronLvL1
resetCustomTimer:true
[hiddenAction_blackIronLvL1]
addResourcesScaledByAIHandicaps: BlackIron=25
spawnEffects:CUSTOM:produceBlackIron

[hiddenAction_reinforceTech]
autoTrigger: if self.globalTeamTags(includes='dvarikBuildingTech') and not self.tags(includes='reinforced')
temporarilyAddTags: reinforced
setUnitStats: hp+=${core.maxHp*0.25}, maxHp+=${core.maxHp*0.25}

[effect_produceBlackIron]
alwayStartDirAtZero:true
attachedToUnit: false
life: 100
alpha: 1
hOffset:16
hSpeed: 0.3
image: ROOT:\data\images\blackIron10.png
priority: high
drawUnderUnits:false
scaleFrom:1.2
scaleTo: 1.2

[hiddenAction_smoke]
autoTrigger:true
spawnEffects:CUSTOM:smoke*3

[effect_smoke]
xOffsetRelative:7
yOffsetRelative:20
attachedToUnit: false
life: 400
alpha: 0.3
scaleFrom:1
scaleTo: 3
#physics: true
xSpeedRelativeRandom: 0.07
ySpeedRelativeRandom: 0.07
hSpeed: 0.1
image: ROOT:\data\images\smoke.png
priority: low
drawUnderUnits:false
atmospheric:true
fadeInTime:40


[graphics]
total_frames: 1
imageScale: 1.1

image:        base.png
image_back:  back.png
image_wreak:  NONE
image_turret: NONE

image_shadow: AUTO
shadowOffsetX:0
shadowOffsetY:1




[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

turretSize: 0
turretTurnSpeed: 1


maxAttackRange: 0
shootDelay: 2s


[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0
turnAcceleration: 0.1



[ai]

buildPriority: 0.6

noneGlobalExtraPriority: 0.2

maxEachBase: 1