
[core]
name: highpeakPlagueOrcTech
tags:canBurn, building, tech
class: CustomUnitMetadata
price: Emerald=500, gazul=250
maxHp: 1750
mass: 9000

displayText: Foul Den
displayDescription: "Toil and trouble, eh eh eh!'."\n\n -Unlocks certain units\n -Can research upgrades

techLevel: 1
buildSpeed: 20s

radius: 35
footprint: -1,-1,1,1
constructionFootprint: -1,-1,1,2
buildingToFootprintOffsetX:10
buildingToFootprintOffsetY:0

isBuilding: true
isBio: false
numBitsOnDeath: 5


exit_y:35

################################# Techs #################################

[action_larvaTech]
isVisible: if not self.globalTeamTags(includes='plagueOrcLarvaTech')
iconImage:ROOT:\data\images\feast.png
displayType:action
pos:1
text: Larva Tending
price: emerald=750, gazul=600
description: An additional, larger larva will spawn from plague mutants on death, and from most "Hive" unit attacks
addGlobalTeamTags: plagueOrcLarvaTech
buildSpeed: 140s

[action_moundTech]
isVisible: if not self.globalTeamTags(includes='plagueOrcMoundTech')
iconImage:ROOT:\data\images\meleeplus.png
displayType:action
pos:1
text: Larva Mound
price: emerald=600, gazul=450
description: Crones can now build Larva Mounds
addGlobalTeamTags: plagueOrcMoundTech
buildSpeed: 60s

[action_plagueTech]
isVisible: if not self.globalTeamTags(includes='plagueOrcPlagueTech')
iconImage:ROOT:\data\images\maul.png
displayType:action
pos:1
text: Pestilence
price: emerald=600, gazul=500
description: Plague can now damage enemy units down to 25% health, instead of 50%
addGlobalTeamTags: plagueOrcPlagueTech
buildSpeed: 180s
################################# Graphics #################################

[hiddenAction_smoke]
autoTrigger:true
spawnEffects:CUSTOM:smoke*2

[effect_smoke]
xOffsetRelative: 10
yOffsetRelative: 10
xOffsetRelativeRandom:5
yOffsetRelativeRandom:5
attachedToUnit: false
life: 400
alpha: 0.3
scaleFrom:1
scaleTo: 2
#physics: true
xSpeedRelativeRandom: 0.07
ySpeedRelativeRandom: 0.07
hSpeed: 0.1
hOffset:10
image: ROOT:\data\images\sick.png
priority: low
drawUnderUnits:false
atmospheric:true
fadeInTime:40

[graphics]
total_frames: 1
imageScale: 0.8

image:        base.png
image_back:  back.png
image_wreak:  NONE
image_turret: NONE

image_shadow: SHADOW:shadow.png
shadowOffsetX:0
shadowOffsetY:0

################################# Attack #################################

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

turretSize: 0
turretTurnSpeed: 1


maxAttackRange: 0
shootDelay: 2s

################################# Movement #################################

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0
turnAcceleration: 0.1

################################# AI #################################

[ai]

buildPriority: 0.4

noneInBaseExtraPriority: 0.1

maxEachBase: 1