[core]
copyFrom: ROOT:\data\templates\unitXp.template
name: highpeakLonguiMonster_3
displayText: Fenglong
tags: bio, normalVision, monster, cannotConvert, large, fenglong
displayDescription: -Large air monster\n -Very well armed\n -Good vs infantry\n -Fast
class: CustomUnitMetadata
price: Emerald=750, Gazul=300, Lodging=3
borrowResourcesWhileBuilt:Lodging=3
maxHp: 475
armour: 4
armourMinDamageToKeep: 0
mass: 4500

energyMax: 2
energyRegen: 0.009
energyNeedsToRechargeToFull: true

transportSlotsNeeded:5

techLevel: 1
buildSpeed: 30s
radius: 15
isBio: true
isBug: false

hideScorchMark: true
selfRegenRate:0
softCollisionOnAll: 12

effectOnDeath:CUSTOM:death, CUSTOM:blood*3
unitsSpawnedOnDeath:neutralDead

explodeOnDeathGroundCollision:false
effectOnDeathGroundCollision:NONE

[effect_death]
life: 0
spawnChance:0.40
alpha:0
alsoPlaySound:ROOT:\data\soundFx\deathReptile.ogg:0.3

[effect_blood]
attachedToUnit: false
life: 60
physics: true
scaleFrom:1.1
scaleTo: 0.2
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.5
hSpeed: 1
image: ROOT:\data\images\bloodRed.png
drawUnderUnits:false

[action_daze]
iconImage:ROOT:\data\images\dazeIcon.png
displayType:action
pos:1
text: Daze
description: Passive\n -Daze enemies making them behave erratically
buildSpeed: 0s
isVisible: true

[graphics]
drawLayer:experimentals
total_frames: 8
imageScale: 0.7
scaleTurretImagesTo:12
teamColorsOnTurret: true
image:        body.png
image_wreak:  ROOT:\data\images\medium_dead.png
image_turret: turret.png
image_shadow: SHADOW:shadow.png
shadowOffsetX:0
shadowOffsetY:0

showTransportBar:false

animation_moving_start: 0
animation_moving_end: 6
animation_moving_speed: 5

animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 120
animation_idle_scale_start:1
animation_idle_scale_end:1.03
animation_idle_pingPong: true


[attack]

canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:  true
canAttackUnderwaterUnits: false

turretSize: 20
turretTurnSpeed: 1.5

maxAttackRange: 100
shootDelay: 3
aimOffsetSpread:0
attackMovement: bomber

[attachment_1]
x: 0
y: 0
height:-10
isVisible:true
keepAliveWhenParentDies:false
setDrawLayerOnBottom:true

[action_HealingMist]
iconImage:ROOT:\data\images\healingBreeze.png
isLocked: if self.tags(includes='isDrunk')
highPriorityQueue:true
displayType: action
text: Healing mist
price:  Wine=45
description: -Summon magical mist for 20s\n -Ally units in the area will heal over time(Do not stack)
addActionCooldownTime: 60s
allowMultipleInQueue:false
onlyOneUnitAtATime:true
spawnEffects: CUSTOM:gettingDrunk
attachments_addNewUnits:highpeakLonguiHealingMist
buildSpeed: 0s

[effect_gettingDrunk]
alsoPlaySound:ROOT:\data\soundFx\wind.ogg:0.6
fadeInTime:10
alwayStartDirAtZero:true
attachedToUnit: true
life: 30
alpha: 1
image: ROOT:\data\images\auraWine.png
priority: high
drawUnderUnits:true
scaleFrom:1
scaleTo: 2.5

[turret_1]
x: 0
y: 0
canShoot:false
invisible:true

recoilOffset:-3
recoilOutTime: 15
recoilReturnTime: 18

[turret_2]
x: 0
y: 9
energyUsage: 0.2
recoilOffset:-1
#shoot_flame:smoke
shoot_sound:ROOT:\data\soundFx\flameThrower.ogg
shoot_sound_vol:0.1

[projectile_1]

areaDamage: 15
areaRadius: 30
armourIgnoreAmount:6
buildingDamageMultiplier:0.5
life: 120
speed:4
speedSpread: 1
trailEffect:CUSTOM:trail
lightColor:#ffecc0
explodeEffect:smoke
image:ROOT:\data\images\mist.png
color:#ffecc0
drawSize:0.6
targetGround:true
targetGroundSpread: 10
targetGround_includeTargetHeight:true
initialUnguidedSpeedHeight: 1.2
gravity:0.18

mutatorDaze_ifUnitWithTags: bio
mutatorDaze_addResourcesAreaHit: Daze=1

[effect_trail]
createWhenZoomedOut: false
image: ROOT:\data\images\mist.png
xOffsetRelative:0
yOffsetRelative:0
attachedToUnit: false
life: 55
alpha: 0.7
scaleFrom:0.4
scaleTo: 1.8
#physics: true
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.3
ySpeedRelative: 1
hSpeed: 0.1
priority: high
drawUnderUnits:false
atmospheric:true
color:#ffecc0

[effect_smoke]
xOffsetRelative:-8
yOffsetRelative:-8
attachedToUnit: false
life: 150
alpha: 0.5
scaleFrom:0.3
scaleTo: 1.6
xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.1
hSpeed: 0.1
image: ROOT:\data\images\mist.png
color:#ffecc0
priority: low
drawUnderUnits:false
atmospheric:true

[movement]
movementType: AIR
moveSpeed: 1.2
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.005
maxTurnSpeed: 2
turnAcceleration: 0.1
moveSlidingMode :true
moveIgnoringBody:false
moveSlidingDir:  181
reverseSpeedPercentage:0
joinsGroupFormations: true