
[core]
name: highpeakTheConspiracyTower
tags: highpeakTower, canBurn, normalVision, building
class: CustomUnitMetadata
price: Emerald=250
maxHp: 1500
mass: 9000

displayText: Crater
displayDescription: "Miasma! Kill kill! Surface dwellers!"\n\n -Defensive building\n -Good vs biological units\n -Randomly spawns acid miasma in a large area \n -Can house bomb teams to gain a powerful exlosion ability

techLevel: 1
buildSpeed: 10s

radius: 30
footprint: -1,-1,0,0
constructionFootprint: -2,-2,1,1
buildingToFootprintOffsetX:0
buildingToFootprintOffsetY:0
fogOfWarSightRange: 5
isBuilding: true
isBio: false
numBitsOnDeath: 5
exit_y:22

transportUnitsCanUnloadUnits:if self.queueSize(lessThan=1)
maxTransportingUnits:10
transportUnitsRequireTag:bombTeam
transportUnitsUnloadDelayBetweenEachUnit:6
transportUnitsEachUnitAlwaysUsesSingleSlot:true
transportUnitsKillOnDeath:true

[hiddenAction_miasma]
autoTrigger:true
spawnEffects:CUSTOM:miasma*2
fireTurretXAtGround: miasma
fireTurretXAtGround_withOffset:0,0

[effect_miasma]
dirOffsetRandom:360
xOffsetRelative:1
yOffsetRelative:25
attachedToUnit: false
life: 125
alpha: 0.35
scaleFrom:1
scaleTo: 3
xSpeedRelativeRandom: 0.12
ySpeedRelativeRandom: 0.12
hSpeed: 0.25
image: ROOT:\data\images\miasma.png
priority: low
drawUnderUnits:false
atmospheric:true
fadeInTime:40



[graphics]
total_frames: 1
imageScale: 0.7

image:        base.png
image_back:  back.png
image_wreak:  NONE
image_turret: NONE

image_shadow: SHADOW:shadow.png
shadowOffsetX:0
shadowOffsetY:0



[attack]

canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

turretSize: 0
turretTurnSpeed: 20

maxAttackRange: 175
shootDelay: 2s

[turret_miasma]
x: 0
y: 0
projectile:miasma

[projectile_miasma]
mutatorAcid_ifUnitWithTags: bio, magical, machine, building, boneConstruct
mutatorAcid_addResourcesAreaHit: Acid=5

areaDamage:50
areaRadius:40
targetGround:true
areaHitAirAndLandAtSameTime:true
targetGroundSpread:175
life: 150
explodeOnEndOfLife:true
speed: 20
explodeEffect: CUSTOM:crack, CUSTOM:crackSpread*5, CUSTOM:miasmaTrail*3
drawSize:0

[effect_crack]
fadeInTime:25
alwayStartDirAtZero:true
priority:high
attachedToUnit: false
life: 90
scaleFrom:0.75
scaleTo: 0.75
#dirOffsetRandom:360
image: ROOT:\data\images\crack.png
drawUnderUnits:true

[effect_crackSpread]
attachedToUnit: false
fadeInTime:35
life: 60
scaleFrom:0.5
scaleTo: 0.5
dirOffsetRandom:360
image: ROOT:\data\images\crack.png
alpha:0.5
drawUnderUnits:true
xOffsetAbsoluteRandom:14
yOffsetAbsoluteRandom:14

[effect_miasmaTrail]
fadeInTime:50
dirOffsetRandom:360
xOffsetRelativeRandom:7
yOffsetRelativeRandom:7
attachedToUnit: false
life: 125
alpha: 0.35
scaleFrom:1
scaleTo: 3
hSpeed: 0.25
xSpeedRelativeRandom:0.12
ySpeedRelativeRandom:0.12
image: ROOT:\data\images\miasma.png
priority: high
drawUnderUnits:false
atmospheric:true

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0
turnAcceleration: 0.1



[ai]

buildPriority: 0.28

noneInBaseExtraPriority: 0.1

maxEachBase: 2

recommendedInEachBaseNum:1

[arm_8]
x: 0
y: 0
spinRate:-0.5
image_end: ROOT:\data\images\miasmaFogSmall.png
drawUnderAllUnits: false

#-------------------------------(explosion)----------------------------

[action_Exploding]
isLocked: if self.transportingCount(lessThan=10)
isLockedMessage: Requires 10 bomb teams
displayType:action
text:D-Bomb
description:-Generates a massive explosion\n -Requires 10 bomb teams\n -Friendly fire\n -Cannot be aborted
iconImage:ROOT:\data\images\fireIcon.png

canPlayerCancel:false
whenBuilding_playAnimation:erupting
spawnEffects:largeExplosion
deleteNumUnitsFromTransport:9
addResourcesScaledByAIHandicaps: hp=-100000
fireTurretXAtGround: death
fireTurretXAtGround_withOffset:0,0
buildSpeed: 4s

[animation_erupting]
onActions : queuedUnits
effect_0s:{name:CUSTOM|smokeBlack}
effect_0.25s:{name:CUSTOM|smokeBlack}

[hiddenAction_smoke]
autoTrigger:true
spawnEffects:CUSTOM:miasma*3

[effect_smoke]
dirOffsetRandom:360
xOffsetRelative:1
yOffsetRelative:25
attachedToUnit: false
life: 300
alpha: 0.25
scaleFrom:0
scaleTo: 6
#physics: true
xSpeedRelativeRandom: 0.07
ySpeedRelativeRandom: 0.07
hSpeed: 0.2
image: ROOT:\data\images\miasma.png
priority: low
drawUnderUnits:false
atmospheric:true

[effect_smokeBlack]
dirOffsetRandom:360
xOffsetRelative:1
yOffsetRelative:25
attachedToUnit: false
life: 300
alpha: 0.25
fadeInTime:30
scaleFrom:1
scaleTo: 10
#physics: true
xSpeedRelativeRandom: 0.07
ySpeedRelativeRandom: 0.07
hSpeed: 0.3
image: ROOT:\data\images\smokeBlack.png
priority: low
drawUnderUnits:false
atmospheric:true
alsoEmitEffects: CUSTOM:volcanoRock*3

[effect_volcanoRock]
xOffsetRelative:1
yOffsetRelative:25
spawnChance:0.5
attachedToUnit: false
fadeInTime:5
life: 60
ySpeedRelativeRandom: 1
xSpeedRelativeRandom: 1
image: ROOT:\data\images\fireAcid.png
dirSpeedRandom:0.5
dirOffsetRandom:360
scaleFrom:1.1
scaleTo: 0
priority: low
physics:true
hSpeed:2
alpha:1

[effect_deathExplode]
xOffsetRelative:1
yOffsetRelative:25
spawnChance:0.5
attachedToUnit: false
fadeInTime:5
life: 50
ySpeedRelativeRandom: 7
xSpeedRelativeRandom: 7
image: ROOT:\data\images\fireAcid.png
dirSpeedRandom:0.5
dirOffsetRandom:360
scaleFrom:1
scaleTo: 0
priority: critical
physics:true
hSpeed:4
showInFog:true
createWhenOffscreen:true
alpha:2

[effect_crackBig]
fadeInTime:0
alwayStartDirAtZero:true
priority:high
attachedToUnit: false
life: 450
scaleFrom:1.5
scaleTo: 1.5
#dirOffsetRandom:360
image: ROOT:\data\images\crack.png
drawUnderUnits:true

[turret_death]
x: 0
y: 0
canShoot:false
invisible:true
projectile:death

[projectile_death]
spawnProjectilesOnExplode:death
areaDamage: 750
areaRadius:175
areaDamageNoFalloff:false
areaHitAirAndLandAtSameTime:true
areaHitUnderwaterAlways:true
armourIgnoreAmount:20
friendlyFire:true
life: 120
speed:50
explodeEffect:shockwave, CUSTOM:deathExplode*15, CUSTOM:crackBig, CUSTOM:crackSpread*5
drawSize:0

mutatorAcid_ifUnitWithTags: bio, magical, machine, building, boneConstruct
mutatorAcid_addResourcesAreaHit: Acid=5