
[core]
copyFrom: ROOT:\data\templates\unitXp.template, ROOT:\data\templates\drowning.template
name: highpeakTheWizardSiege_2
tags: magical, normalVision, large
displayText: Metronome
displayDescription: -Large long ranged construct\n -Fire and ice attack \n -Good vs everything\n -Slow\n -Can cross cliffs
class: CustomUnitMetadata
price: Emerald=1450, Gazul=500, Amber=50, Ruby=50, Sapphire=50
maxHp: 575
armour:12
mass: 5000

techLevel: 1
experimental: false
buildSpeed: 45s

transportSlotsNeeded:5

radius: 24
isBio: false
isBug: false
fogOfWarSightRange: 18
hideScorchMark: true
selfRegenRate:0
softCollisionOnAll: 12
explodeOnDeath:false
effectOnDeath: CUSTOM:iceSpark*5

[hiddenAction_iceSpark]
spawnEffects: CUSTOM:iceSpark*3
autoTrigger:true

[effect_iceSpark]
attachedToUnit: false
life: 80
scaleFrom:0.7
scaleTo: 0
xOffsetRelativeRandom: 16
yOffsetRelativeRandom: 16
hOffset: 8
dirOffsetRandom:25
xSpeedRelativeRandom: 0.15
ySpeedRelativeRandom: 0.15
ySpeedRelative: 0.2
hSpeed: 0.1
image: ROOT:\data\images\snowFlake2.png
drawUnderUnits:true
fadeInTime:15

[action_fire]
iconImage:ROOT:\data\images\fireIcon.png
displayType:action
pos:1
text: Fire
description: Passive\n -Can set buildings on fire, dealing damage over time
buildSpeed: 0s
isVisible: true

[action_freeze]
iconImage:ROOT:\data\images\iceIcon.png
displayType:action
pos:1
text: Freeze
description: Passive\n -Can slow down bio units, dealing low damage over time
buildSpeed: 0s
isVisible: true

[graphics]
teamColorsOnTurret: true
imageScale: 1.1
total_frames: 1

image:        wheel.png
image_wreak:  ROOT:\data\images\water.png
image_turret: NONE

movementEffect:CUSTOM:iceSpark
movementEffectRate:5

#AUTO
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:2

[attack]

canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
isFixedFiring: false
turretSize: 14
turretTurnSpeed: 1
turretMultiTargeting:true
aimOffsetSpread:0
maxAttackRange: 225
shootDelay: 1.5s

[attachment_1]
resetRotationWhenNotAttacking:true
x: 0
y: 0
idleDir:0
height:9
isVisible:true
keepAliveWhenParentDies:false
rotateWithParent:true
onCreateSpawnUnitOf:highpeakTheWizardArcher_4

[turret_1]
height: 6
x: 0
y: 0
idleSpin:0.5
canShoot:false
invisible:true
limitingRange:0

[turret_2]
canAttackFlyingUnits: false
x: 0
y: 10
attachedTo: 1
limitingAngle:15

image:turret1.png
shoot_sound:ROOT:\data\soundFx\energy.ogg
shoot_sound_vol:0.1
recoilOffset:-2
recoilOutTime: 7
recoilReturnTime: 50
projectile:1
chargeEffectImage:ROOT:\data\images\magicBall.png

[turret_3]
canAttackFlyingUnits: false
x: -10
y: -5
copyFrom:2
shoot_sound:ROOT:\data\soundFx\flameThrower.ogg
idleDir:-125
image:turret2.png
projectile:2

[turret_4]
canAttackFlyingUnits: false
x: 10
y: -5
copyFrom:2
shoot_sound:ROOT:\data\soundFx\crystalShards.ogg
idleDir:125
image:turret3.png
projectile:3

[projectile_1]
areaDamage:120
areaHitAirAndLandAtSameTime:true
areaRadius:20
targetGround:true
targetGround_includeTargetHeight:true
targetGroundSpread:10
life: 120
speed: 5
speedSpread:1
image: ROOT:\data\images\emberBall.png
buildingDamageMultiplier: 0.5
drawSize:1.1
shadowFrame:11
trailEffect:CUSTOM:trail1
trailEffectRate:1

initialUnguidedSpeedHeight: 1
gravity:0.18

[effect_trail1]
createWhenZoomedOut: false
image: ROOT:\data\images\emberBall.png
life: 20

xSpeedRelativeRandom:0.4
ySpeedRelativeRandom:0.4
ySpeedRelative:2

fadeOut: true
attachedToUnit: false
fadeInTime:2
scaleFrom: 0.6
scaleTo: 0
alpha: 1
drawUnderUnits:false

[projectile_2]
areaDamage:120
areaHitAirAndLandAtSameTime:true
areaRadius:20
targetGround:true
targetGround_includeTargetHeight:true
targetGroundSpread:10
life: 120
speed: 5
speedSpread:1
image: ROOT:\data\images\ember.png
buildingDamageMultiplier: 0.5
drawSize:1.1
shadowFrame:11
trailEffect:CUSTOM:trail2
trailEffectRate:1

initialUnguidedSpeedHeight: 1
gravity:0.18

mutatorFire_ifUnitWithTags: canBurn
mutatorFire_addResourcesAreaHit: Fire=5

[effect_trail2]
createWhenZoomedOut: false
image: ROOT:\data\images\ember.png
life: 20

xSpeedRelativeRandom:0.4
ySpeedRelativeRandom:0.4
ySpeedRelative:2

fadeOut: true
attachedToUnit: false
fadeInTime:2
scaleFrom: 1
scaleTo: 0
alpha: 1
drawUnderUnits:false

[projectile_3]
areaDamage:120
areaHitAirAndLandAtSameTime:true
areaRadius:20
targetGround:true
targetGround_includeTargetHeight:true
targetGroundSpread:10
life: 120
speed: 5
speedSpread:1
image: ROOT:\data\images\snowFlake.png
buildingDamageMultiplier: 0.5
drawSize:0.8
shadowFrame:11
trailEffect:CUSTOM:trail3
trailEffectRate:1
lightColor:#c3ddef
initialUnguidedSpeedHeight: 1
gravity:0.18

explodeEffect:CUSTOM:effectFreezingBomb*2

mutatorFire_ifUnitWithTags: bio
mutatorFire_addResourcesAreaHit: Freezing=3

[effect_effectFreezingBomb]
attachedToUnit: true
life: 10
alpha: 1
hOffset:1
xOffsetRelativeRandom:3
yOffsetRelativeRandom:3
hSpeed: 0.2
xSpeedRelativeRandom:0.1
ySpeedRelativeRandom:0.1
dirSpeed:0.4
dirSpeedRandom:0.3
dirOffsetRandom:360
fadeInTime:2
image: ROOT:\data\images\snowFlake.png
priority: high
drawUnderUnits:false
scaleFrom:1
scaleTo: 2

[effect_trail3]
createWhenZoomedOut: false
image: ROOT:\data\images\snowFlake.png
life: 40

xSpeedRelativeRandom:0.4
ySpeedRelativeRandom:0.4
ySpeedRelative:2

fadeOut: true
attachedToUnit: false
fadeInTime:2
scaleFrom: 0.6
scaleTo: 0
alpha: 1
drawUnderUnits:false

[movement]
movementType: OVER_CLIFF
moveSpeed: 0.4
targetHeight:3
moveAccelerationSpeed: 0.05
moveDecelerationSpeed: 0.01
maxTurnSpeed: 2
turnAcceleration: 0.1
moveSlidingMode :true
moveIgnoringBody:true
moveSlidingDir:  181
reverseSpeedPercentage:0

[arm_1]
x: 0
y: 0
drawUnderAllUnits: true
spinRate:-1

[decal_body1]
onlyWhileAlive:true
order:0
imageScale:1.1
xOffsetRelative:0
yOffsetRelative:0
hOffset:0
layer: afterBody
imageStack: body.png, ROOT:\data\images\auraHero.png, wheel.png
stack_hOffset:3
teamColors:true
basePositionFromLegEnd:arm_1

image_shadow: SHADOW:body.png
shadowOffsetX:2
shadowOffsetY:6

[arm_2]
x: 0
y: 0
image_end: amber.png
drawOverBody: true
spinRate:2

[arm_3]
x: 0
y: 0
image_end: ruby.png
drawOverBody: true
spinRate:2
drawDirOffset: 115

[arm_4]
x: 0
y: 0
image_end: sapphire.png
drawOverBody: true
spinRate:2
drawDirOffset:230

[leg_1]
x: 0
y: -8
attach_x: 0
attach_y: -2
rotateSpeed:4
moveSpeed: 1.1
resetAngle:5
heightSpeed: 0.5
dust_effect: false
holdDisMin: 4
holdDisMax: 12
hardLimit: 12
holdDisMin_maxMovingLegs:2
hold_moveOnlyIfFurthest:true
estimatingPositionMultiplier:0.45
hidden:if self.hasParent()
image_end_teamColors: true
endDirOffset:180
draw_foot_on_top:true
image_leg:  leg.png
image_foot:  leg.png
image_foot_shadow:SHADOW:leg.png

[leg_2]
x: -8
y: 8
attach_x: -2
attach_y: 2
copyFrom: 1
hidden:if self.hasParent()
endDirOffset:-45

[leg_3]
x: 8
y: 8
attach_x: 2
attach_y: 2
copyFrom: 1
hidden:if self.hasParent()
endDirOffset:45





