
[core]
showInEditor:false
tags: gazulVein
onNewMapSpawn: emptyOrOccupiedResourcePools_asNeutral
stayNeutral:true
createNeutral:true
name: highpeakGazulVein
displayText: Gazul vein
displayDescription: 
class: CustomUnitMetadata
price: 0
maxHp: 100
mass: 100

techLevel: 1
buildSpeed: 0

radius: 1
isBio: false
isBug: false
isBuilding:false

numBitsOnDeath: 10

isUnselectable:true
isUnselectableAsTarget:true
canNotBeDirectlyAttacked:true
createOnAggressiveTeam:true
showOnMinimap: false
disableAllUnitCollisions:true
explodeOnDeath:false

effectOnDeath:NONE

################################# Abilities #################################

################################# Graphics #################################

[graphics]
rotate_with_direction:false
drawLayer:wreaks
imageScale: 0.8
total_frames: 1
image:        base.png
image_wreak:  NONE
image_turret: NONE

image_shadow: NONE
shadowOffsetX:1
shadowOffsetY:1

#[action_triggerDropoff]
#ai_isHighPriority: if self.numberOfUnitsInAllTeams(withTag='center', greaterThan=0, withinRange=1000) and self.numberOfUnitsInAllTeams(withTag='highpeakForge', withinRange=100, lessThan=1)
#spawnUnits: placeDropoff(gridAlign=true, offsetY=-40)
#addActionCooldownTime: 60s

################################# Weapons #################################

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
turretSize: 0
turretTurnSpeed: 100
maxAttackRange: 1
shootDelay: 1

################################# Movement #################################

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.12
joinsGroupFormations: false
targetHeight:0.5

maxTurnSpeed: 0
turnAcceleration: 0.4

reverseSpeedPercentage:0

