
[core]
name: highpeakForeignLegionTower
tags: highpeakTower, canBurn, normalVision, building
class: CustomUnitMetadata
price: Emerald=550
maxHp: 2000
mass: 9000

displayText: Watch
displayDescription: "Sloppy soldiers end in the watch."\n\n -Defensive building\n -Good vs infantry

techLevel: 1
buildSpeed: 20s

radius: 30
footprint: -1,-1,0,0
constructionFootprint: -2,-2,1,1
buildingToFootprintOffsetX:0
buildingToFootprintOffsetY:0

isBuilding: true
isBio: false
numBitsOnDeath: 5
exit_y:20

[action_antiRaider]
iconImage:ROOT:\data\images\melee.png
displayType:action
pos:1
text: Tower
description:This unit deals more damage to raiders
buildSpeed: 0s
isVisible: true

[graphics]
total_frames: 1
imageScale: 0.8

image:        base.png
image_back:  back.png
image_wreak:  NONE
image_turret: NONE

image_shadow: NONE
shadowOffsetX:0
shadowOffsetY:2



[attack]

canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 8
turretTurnSpeed: 20

maxAttackRange: 300
shootDelay: 2s

[turret_1]
x: 0
y: 18
shoot_sound:ROOT:\data\soundFx\shootGun.ogg
shoot_sound_vol:0.15
recoilOffset:-3
recoilOutTime: 15
recoilReturnTime: 18
projectile:spawner


[projectile_spawner]
spawnProjectilesOnCreate:1*5
life: 0
speed: 1
drawSize:0
directDamage:0

[projectile_1]
mutatorRaider_ifUnitWithTags:raider
mutatorRaider_areaDamageMultiplier:2

mutatorShield_ifUnitWithTags:shield
mutatorShield_areaDamageMultiplier:0.35

mutatorPlate_ifUnitWithTags:plate
mutatorPlate_areaDamageMultiplier:0.25

areaDamage:24
areaRadius:3
areaRadiusFromEdge:true
areaDamageNoFalloff:true
targetGround:true
targetGround_includeTargetHeight:true
targetGroundSpread:12

life: 120
speed: 4
speedSpread:1
image: ROOT:\data\images\dart.png
explodeEffect: CUSTOM:arrowGround
buildingDamageMultiplier: 0.1
drawSize:0.5
initialUnguidedSpeedHeight: 1.2
gravity:0.18
shadowFrame:11
trailEffect:CUSTOM:trail
trailEffectRate:1

[effect_arrowGround]
attachedToUnit: false
life: 1000
scaleFrom:0.5
scaleTo: 0.5
#xOffsetAbsoluteRandom:25
#yOffsetAbsoluteRandom:25
dirOffsetRandom:5
image: ROOT:\data\images\dart.png
drawUnderUnits:true

[effect_trail]
createWhenZoomedOut: false
color:#dbc782
image: ROOT:\data\images\trail.png
life: 30
fadeOut: true
attachedToUnit: false
fadeInTime:2
scaleFrom: 0.3
scaleTo: 0.2
alpha: 0.6
drawUnderUnits:false


[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0
turnAcceleration: 0.1



[ai]

buildPriority: 0.28

noneInBaseExtraPriority: 0.1

maxEachBase: 2

recommendedInEachBaseNum:1