
[core]
copyFrom:ROOT:\data\templates\builderEffect.template
name: highpeakHumanTech
tags: canBurn, building
class: CustomUnitMetadata
price: Emerald=500, gazul=250
maxHp: 2200
mass: 9000

displayText: HumanTech
displayDescription: ""\n\n -Can research Technology

techLevel: 1
buildSpeed: 20s

radius: 30
footprint: -1,-1,1,1
constructionFootprint: -2,-2,2,2
buildingToFootprintOffsetX:10
buildingToFootprintOffsetY:5

isBuilding: true
isBio: false
numBitsOnDeath: 5

canRepairUnitsOnlyWithTags:machine
autoRepair: true
nanoRepairSpeed: 0.1
nanoBuildSpeed: 1
canRepairBuildings: false
canRepairUnits: true
nanoRange: 100


exit_y:30
exit_moveAwayAmount:40

################################# Techs #################################

[action_machineTech]
isVisible: if not self.globalTeamTags(includes='humanMachineTech')
iconImage:ROOT:\data\images\ranged.png
displayType:action
pos:1
text: Higher Pressure
price: emerald=350, gazul=500
description: Tribeault, Pressure bow, and Ironclad gain faster firerate
addGlobalTeamTags: humanMachineTech
buildSpeed: 70s

[action_yakTech]
isVisible: if not self.globalTeamTags(includes='humanYakTech')
iconImage:ROOT:\data\images\ranged.png
displayType:action
pos:1
text: Well Trained Yaks
price: emerald=500, gazul=300
description: All yak riders gain movespeed
addGlobalTeamTags: humanYakTech
buildSpeed: 100s

[action_rancherTech]
isVisible: if not self.globalTeamTags(includes='humanRancherTech')
iconImage:ROOT:\data\images\ranged.png
displayType:action
pos:1
text: Local Militia
price: emerald=600, gazul=400
description: Most Human structures spawn temporary Ranchers when attacked
addGlobalTeamTags: humanRancherTech
buildSpeed: 140s

################################# Graphics #################################

[hiddenAction_smoke]
autoTrigger:true
spawnEffects:CUSTOM:smoke*3

[effect_smoke]
xOffsetRelative:-5
yOffsetRelative:11
attachedToUnit: false
life: 300
alpha: 0.4
scaleFrom:0.1
scaleTo: 2
#physics: true
xSpeedRelativeRandom: 0.07
ySpeedRelativeRandom: 0.07
hSpeed: 0.1
image: ROOT:\data\images\smoke.png
priority: low
drawUnderUnits:false
atmospheric:true


[graphics]
total_frames: 3
imageScale: 0.9

image:        base.png
image_back:  back.png
image_wreak:  NONE
image_turret: NONE

image_shadow: SHADOW:shadow.png
shadowOffsetX:0
shadowOffsetY:0.5

################################# Animation #################################

[animation_idle]
onActions: idle
KeyframeTimeScale : 0.8
body_0s: {frame:0}
body_0.1s: {frame:0}
body_0.2s: {frame:1}
body_0.3s: {frame:1}
body_0.4s: {frame:2}
body_0.5s: {frame:2}

################################# Attacks #################################

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
turretSize: 10
turretTurnSpeed: 20
maxAttackRange: 100
shootDelay: 1


################################# Movement #################################

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0
turnAcceleration: 0.1


################################# Ai #################################

[ai]

buildPriority: 0.30

noneGlobalExtraPriority: 0.1

maxEachBase: 1