[core]
showInEditor: true
name: highpeakBlizzardSpell
displayText: Blizzard
displayDescription: -Deal 300 ice damage at target location over 6 seconds
class: CustomUnitMetadata
price: 0
maxHp: 1000
armour: 999999
armourMinDamageToKeep: 0
mass: 10000
techLevel: 1
radius: 1
isBio: false
transportSlotsNeeded: 1000
isUnrepairableUnit: true
hideScorchMark: true
fogOfWarSightRange: 0
energyMax: 6
energyRegen: 0
dieOnZeroEnergy: true
explodeOnDeath:false
softCollisionOnAll: 100
disableAllUnitCollisions:true
canNotBeDirectlyAttacked:true
isUnselectable:true

[action_lifeTime]
autoTrigger: true
isVisible: false
addEnergy: -1

[hiddenAction_triggerDamage]
autoTrigger: true
fireTurretXAtGround: damageEmitter
fireTurretXAtGround_withOffset: 0,0

[hiddenAction_triggerParticles]
autoTriggerOnEvent: created
isVisible: false
fireTurretXAtGround: effects
fireTurretXAtGround_withOffset: 0,10

[graphics]
total_frames: 1
showEnergyBar:false
image:        spawner.png
image_wreak:  NONE
image_shadow: NONE

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
maxAttackRange: 90
turretTurnSpeed: 10
shootDelay: 3
aimOffsetSpread: 0

[turret_damageEmitter]
x: 0
y: 0
projectile: snow
canShoot: true

shoot_sound:blizzard.ogg,blizzard2.ogg,blizzard3.ogg
shoot_sound_vol:0.05

[turret_effects]
x: 0
y: 0
projectile: ambientFog
canShoot: true

[projectile_snow]
life: 0
speed: 0
frame: 0
drawSize: 0
targetGround: true
areaDamage: 50
areaRadius: 90
friendlyFire: true
buildingDamageMultiplier: 0.25
explodeOnEndOfLife: true
explodeEffect: NONE
areaHitAirAndLandAtSameTime: true

mutatorFire_ifUnitWithTags: bio
mutatorFire_addResourcesAreaHit: Freezing=5

[projectile_ambientFog]
#life: 14400
life: 600
speed: 0.0001
targetSpeed: 0.0001
targetGround: true
directDamage: 0
frame: 0
drawSize: 0
trailEffect: CUSTOM:fog*3, CUSTOM:iceFragments*3
trailEffectRate: 15

[effect_none]
priority:verylow
stripIndex: effects
frameIndex: 0
life: 0
alpha: 0

[effect_fog]
priority:veryhigh
createWhenOffscreen: true
image: ROOT:\data\images\snowFlake.png
life: 50
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0
scaleTo: 1
alpha: 0.8
drawUnderUnits:false
hSpeed: -0.3
hOffset: 5
hOffsetRandom: 0.15
atmospheric:true
dirOffsetRandom:180
shadow:true
imageShadow: SHADOW:ROOT:\data\images\snowFlake.png
xOffsetRelativeRandom: 50
yOffsetRelativeRandom: 50
xSpeedAbsoluteRandom:0.5
ySpeedAbsoluteRandom:0.5

[effect_iceFragments]
priority:high
physics:true
physicsGravity:1.2
createWhenOffscreen: false
createWhenZoomedOut: false
image: ice.png
imageShadow: SHADOW:SHARED:light_50.png
life: 130
fadeOut: true
attachedToUnit: false
fadeInTime: 60
scaleFrom: 0.9
scaleTo: 0
alpha: 1
drawUnderUnits:false
xSpeedAbsolute: -1
hSpeed: -2
hOffset: 270
atmospheric:true
dirOffset:100
xOffsetRelative: 0
xOffsetRelativeRandom: 30
yOffsetRelative: 40
yOffsetRelativeRandom: 30
xSpeedAbsoluteRandom:0.6
ySpeedAbsoluteRandom:0.6

[movement]
movementType: NONE
moveSpeed: 0
targetHeight:-1
maxTurnSpeed: 0
moveSlidingMode :true
moveIgnoringBody: true