
[core]
name: highpeakDvarikGateOpen
copyFrom: gate_closed.ini
showInEditor: false
disableAllUnitCollisions:true
isUnselectable:false

################################# Abilities #################################

[hiddenAction_reinforceTech]
autoTrigger: if self.globalTeamTags(includes='dvarikBuildingTech') and not self.tags(includes='reinforced')
temporarilyAddTags: reinforced
setUnitStats: hp+=${core.maxHp*0.25}, maxHp+=${core.maxHp*0.25}

[action_open]
isVisible: true
convertTo: highpeakDvarikGateClosed
buildSpeed: 0s
text: Close
[graphics]
image:    gateOpen.png