
[core]
copyFrom:archer_1.ini
showInEditor:false
name: highpeakHauntingArcher_1_stealth
tags: undead
maxHp: 75
showOnMinimapToEnemies:false
fogOfWarSightRange: 5

[hiddenAction_etheralStealth]
autoTrigger:if (numberOfUnitsInTeam(withTag='lodestone', withinRange=200, greaterThan=0) or numberOfUnitsInTeam(withTag='marker', withinRange=125, greaterThan=0))
convertTo:highpeakHauntingArcher_1

[effect_deathFog]
image: SHADOW:ROOT:\data\images\smoke.png

[graphics]

image_shadow: NONE

[movement]
moveSpeed: 0.5

#----------------------------(Decals)--------------------------------------
[decal_body1]
alpha:0.2
xOffsetRelative:0
yOffsetRelative:0
layer: afterBody
imageStack:SHADOW:body.png
total_frames:5
addBodyFrameMultipliedBy:1

[arm_9]
x: 0
y: 0
image_end: ROOT:\data\images\shadeAura.png
drawUnderAllUnits: true




