[core]
copyFrom: ROOT:\data\templates\unitXp.template, ROOT:\data\templates\blackIronUpgrades.template
name: highpeakDvarikwarMachine_2
displayText: Magna talpa
tags:machine, normalVision, plate, large
displayDescription: -Large war machine\n -Very well armed and armored\n -Can load and shoot lava shells \n -Trample damage while it moves \n -Plated\n -Good vs buildings and plated units
class: CustomUnitMetadata
price: Emerald=1500, Gazul=500, Lodging=8
borrowResourcesWhileBuilt:Lodging=8

maxHp: 1600
armour: 20
armourMinDamageToKeep: 0
mass: 10000

transportSlotsNeeded:8

energyMax: 2
energyRegen: 0.009
energyNeedsToRechargeToFull: true

maxTransportingUnits:8
transportUnitsRequireTag:infantry, small
transportUnitsCanUnloadUnits:if not self.isOverLiquid()
transportUnitsUnloadDelayBetweenEachUnit:6

techLevel: 1
buildSpeed: 45s
radius: 24
isBio: false
isBug: false
fogOfWarSightRange: 18
hideScorchMark: false
selfRegenRate:0
softCollisionOnAll: 12

################################# Information #################################

[action_plated]
iconImage:ROOT:\data\images\plated.png
displayType:action
pos:1
text: Plated
description: Passive\n -This unit is extremely resistant to small projectiles
buildSpeed: 0s
isVisible: true

[action_unstoppable]
iconImage:ROOT:\data\images\bulldozerIconClean.png
displayType:action
pos:1
text: Unstoppable Force
description: Passive\n -This unit may not be stunned, slowed, or confused in any way
buildSpeed: 0s
isVisible: if self.tags(includes='Unstoppable')

################################# Abilities #################################

[hiddenAction_charge]
autoTrigger:if self.isMoving()
fireTurretXAtGround: charge
fireTurretXAtGround_withOffset:0,50

[action_mortar]
ai_isDisabled:true
displayRemainingStockpile: true
isLocked: if self.ammo(lessThan=1)
isLockedMessage: Out of ammo
playSoundAtUnit: cannon_firing
iconImage:ROOT:\data\images\fireIcon.png
displayType: action
text: Mortar shot
description: -Shoot a massive fireball\n -Deal 400 fire damage at target location and burn structures for 10 seconds\n -Friendly fire
price: ammo=1
fireTurretXAtGround: mortar
fireTurretXAtGround_withProjectile:mortar
buildSpeed: 2s
addActionCooldownTime:15s
pos:0
allowMultipleInQueue:false
whenBuilding_rotateTo_aimAtActionTarget:true
#whenBuilding_rotateTo_rotateTurretX:mortar
whenBuilding_cannotMove:true

[action_buildShell]
ai_isDisabled:true
iconImage:ROOT:\data\images\addon.png
displayType:action
price:  BlackIron=350
text: Load shell
description:Load magma shell\n -Maximum capacity of 3 shells\n -Machine must remain stationary during process
buildSpeed: 25s
pos: 0
isActive:if self.ammoIncludingQueued(lessThan=3)
addResources: ammo=1
whenBuilding_cannotMove:true

[hiddenAction_dvarLegsTechTrigger]
autoTrigger:if self.globalTeamTags(includes='dvarikLegsTech') and not self.tags(includes='DvarLegsTech')
setUnitStats: moveSpeed+=${movement.moveSpeed * 0.1}
temporarilyAddTags: DvarLegsTech, Unstoppable

################################# Graphics #################################

[graphics]
drawLayer:experimentals
total_frames: 1
imageScale: 0.9
teamColorsOnTurret: true
image:        body.png
image_wreak:  ROOT:\data\images\medium_dead_wood.png
image_turret: mainTurret.png
image_shadow: AUTO
shadowOffsetX:2
shadowOffsetY:3
showTransportBar:false
scaleTurretImagesTo:20
movementEffect:CUSTOM:smoke*2
movementEffectRate:10

animation_moving_start: 0
animation_moving_end: 0
animation_moving_speed: 10
animation_moving_scale_start:1
animation_moving_scale_end:1.01

animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 15
animation_idle_scale_start:1
animation_idle_scale_end:1.01

[arm_1]
hidden: if not self.tags(includes='bulldozer')
x: -17
y: 29
endDirOffset:-36
drawOverBody:false
image_end:  ROOT:\data\images\bulldozer.png

[arm_2]
hidden: if not self.tags(includes='bulldozer')
x: 17
y: 29
copyFrom:1
endDirOffset:36

[hiddenAction_smoke]
autoTrigger:true
spawnEffects:CUSTOM:smoke*3

[effect_mortarTrail]
atmospheric:true
createWhenZoomedOut: false
color:#ff4e00
image: ROOT:\data\images\trail.png
life: 90
fadeOut: true
attachedToUnit: false
fadeInTime:2
scaleFrom: 0.8
scaleTo: 0.3
alpha: 0.6
drawUnderUnits:false

[effect_mortarTrail2]
createWhenZoomedOut: false
image: ROOT:\data\images\ember.png
life: 50

xSpeedRelativeRandom:0.2
ySpeedRelativeRandom:0.2
ySpeedRelative:0.5
fadeOut: true
attachedToUnit: false
fadeInTime:10
scaleFrom: 1.4
scaleTo: 0.3
alpha: 0.5
drawUnderUnits:false

[effect_trail]
atmospheric:true
createWhenZoomedOut: false
color:#ffba00
image: ROOT:\data\images\trail.png
life: 90
fadeOut: true
attachedToUnit: false
fadeInTime:2
scaleFrom: 0.4
scaleTo: 0.3
alpha: 0.6
drawUnderUnits:false

[effect_smoke]
xOffsetRelative:-10
yOffsetRelative:-20
attachedToUnit: false
life: 150
alpha: 0.5
scaleFrom:0.3
scaleTo: 1.6
xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.1
hSpeed: 0.1
image: ROOT:\data\images\smoke.png
priority: low
drawUnderUnits:false
atmospheric:true

################################# Weapons #################################

[attack]
canAttack: true
canAttackFlyingUnits: if self.isFlying()
canAttackLandUnits:  if self.isAtGroundHeight()
canAttackUnderwaterUnits: false
isFixedFiring: true
isMelee:true
meleeEngangementDistance:120
turretSize: 1
turretTurnSpeed: 3
aimOffsetSpread:0
maxAttackRange: 25
shootDelay: 0.1s

[turret_1]
x:0
y:27
attachedTo:2
slave:true
shoot_flame:smoke
shoot_sound: ROOT:\data\soundFx\bigDrill.ogg
shoot_sound_vol:0.2
recoilOffset: 2
recoilOutTime: 1
recoilReturnTime: 30
projectile:1
energyUsage: 0.13

[turret_2]
x:0
y:0
image:top.png
canShoot:false

[projectile_1]
mutatorPlate_ifUnitWithTags:plate
mutatorPlate_directDamageMultiplier:1.5

directDamage: 20
buildingDamageMultiplier:4.0
armourIgnoreAmount:5
life: 10
instant:true
explodeEffect:NONE



[turret_mortar]
x: 0
y: -6
size:16
shoot_light:#ff7800
shoot_flame:large
shoot_sound: ROOT:\data\soundFx\flameThrower.ogg
shoot_sound_vol:0.25
recoilOffset: -3
recoilOutTime: 4
recoilReturnTime: 18
canShoot:false
image:mortar.png
limitingRange:325
turnSpeed:0.5

[projectile_mortar]
areaDamage:400
areaHitAirAndLandAtSameTime:true
areaRadius:35
targetGround:true
life: 1000
speed: 3.5
speedSpread:0.5
image: ROOT:\data\images\ember.png
buildingDamageMultiplier: 1
drawSize:1.3
shadowFrame:11
trailEffect:CUSTOM:mortarTrail, CUSTOM:mortarTrail2
trailEffectRate:1
lightColor:#ff7800
lightSize:2
largeHitEffect:true
explodeEffect: largeExplosion, shockwave
friendlyFire: true
mutatorFire_ifUnitWithTags: canBurn
mutatorFire_addResourcesAreaHit: Fire=10
initialUnguidedSpeedHeight: 1.2
gravity:0.18



[turret_charge]
x: 0
y: 0
attachedTo:2
slave:true
size:0
canShoot:false
invisible: true
projectile: charge
turnSpeed: 40

[projectile_charge]
life: 140
speed: 10
drawSize: 0
targetGround:true
explodeEffect:NONE
deflectionPower: -1
areaDamage: 120
areaRadius: 45
buildingDamageMultiplier:0
mutator1_ifUnitWithTags:shield
mutator1_areaDamageMultiplier:0.5
mutator2_ifUnitWithTags:cavalry
mutator2_areaDamageMultiplier:0
################################# Cargo #################################

[attachment_1]
x: -12
y: 11
idleDir:0
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
setDrawLayerOnTop:true
addTransportedUnits:true
rotateWithParent:true

[attachment_2]
x: 12
y: 11
idleDir:0
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
setDrawLayerOnTop:true
addTransportedUnits:true
rotateWithParent:true

[attachment_3]
x: -12
y: 3
idleDir:0
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
setDrawLayerOnTop:true
addTransportedUnits:true
rotateWithParent:true


[attachment_4]
x: 12
y: 3
idleDir:0
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
setDrawLayerOnTop:true
addTransportedUnits:true
rotateWithParent:true

[attachment_5]
x: -12
y: -4
idleDir:0
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
setDrawLayerOnTop:true
addTransportedUnits:true
rotateWithParent:true

[attachment_6]
x: 12
y: -4
idleDir:0
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
setDrawLayerOnTop:true
addTransportedUnits:true
rotateWithParent:true

[attachment_7]
x: -12
y: -11
idleDir:0
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
setDrawLayerOnTop:true
addTransportedUnits:true
rotateWithParent:true

[attachment_8]
x: 12
y: -11
idleDir:0
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
setDrawLayerOnTop:true
addTransportedUnits:true
rotateWithParent:true

################################# Legs #################################

[leg_1]
x: -14
y: 22
attach_x: -8
attach_y: 16
rotateSpeed:100
moveSpeed: 2
resetAngle:5
heightSpeed: 1
dust_effect: true
holdDisMin: 5
holdDisMax: 15
hardLimit: 15
holdDisMin_maxMovingLegs:1
hold_moveOnlyIfFurthest:true
estimatingPositionMultiplier:0.54
endDirOffset:0
draw_foot_on_top:true
image_leg:  leg.png
image_foot:  foot.png

[leg_2]
x: 14
y: 22
attach_x: 8
attach_y: 16
copyFrom: 1

endDirOffset:0

[leg_3]
x: -16
y: 0
attach_x: -8
attach_y: 0
copyFrom: 1

endDirOffset:180

[leg_4]
x: 16
y: 0
attach_x: 8
attach_y: 0
copyFrom: 1

endDirOffset:180

[leg_5]
x: -16
y: -20
attach_x: -8
attach_y: -20
copyFrom: 1

endDirOffset:180

[leg_6]
x: 16
y: -20
attach_x: 8
attach_y: -20
copyFrom: 1

endDirOffset:180


[movement]
movementType: OVER_CLIFF
moveSpeed: 0.4
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.06
maxTurnSpeed: 1
turnAcceleration: 0.03
moveSlidingMode :true
moveIgnoringBody:false
moveSlidingDir:  181
reverseSpeedPercentage:0