
[core]
copyFrom: ROOT:\data\templates\unitXp.template
name: highpeakHauntingLivingLodestone_1
tags: magical, undead, normalVision, canBurn, machine, livinglodestone, attackCorpse
displayText: Living lodestone
displayDescription: -Mobile defensive building\n -Can train etheral infantry\n -Can raise the dead\n -Can move over water\n -Anchors etheral units\n -Increases spirit limit by 5
class: CustomUnitMetadata
price: 0
maxHp: 1600
armour:14
mass: 500

techLevel: 1
experimental: false
buildSpeed: 300s

borrowResourcesWhileBuilt:maxSpirit=-5

transportSlotsNeeded:100

radius: 23
isBio: false
isBug: false
fogOfWarSightRange: 18
hideScorchMark: true
selfRegenRate:0
softCollisionOnAll: 12

[effect_trail]
fadeInTime:20
color:#81f7ff
attachedToUnit: false
alpha:0.75
life: 200
scaleFrom:2
scaleTo: 1
xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.1
hSpeed: 0.05
image: ROOT:\data\images\smoke.png
drawUnderUnits:true

[action_anchorInfo]
iconImage:ROOT:\data\images\trophy.png
displayType:action
pos:0
text: Anchor
description: Passive\n -Anchor etheral units
buildSpeed: 0s
isVisible: true

[canBuild_Recruit]
name:setRally, highpeakHauntingInfantry_1, highpeakHauntingArcher_1, highpeakHauntingArcher_2, highpeakHauntingInfantry_2
pos: 0.1

[graphics]
drawLayer:experimentals
imageScale: 0.9
total_frames: 1

movementEffect:CUSTOM:trail
movementEffectRate:30

image:        body.png
image_wreak:  ROOT:\data\images\rubble.png
image_turret: NONE

#AUTO
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1

lock_body_rotation_with_main_turret: true

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
turretSize: 8
turretTurnSpeed: 3

maxAttackRange: 180
shootDelay: 1.5s

[turret_1]
x: 0
y: 0
projectile:dummy

[projectile_dummy]
life: 0
speed: 0
drawSize: 0
explodeEffect:NONE
deflectionPower: -1
directDamage: 0

[attachment_1]
#resetRotationWhenNotAttacking:true
x: 0
y: 0
idleDir:-90
lockRotation:true
height:18
isVisible:true
keepAliveWhenParentDies:false
rotateWithParent:false
canBeAttackedAndDamaged:false
onCreateSpawnUnitOf:highpeakHauntingLodestoneLiving
prioritizeParentsMainTarget:true

[movement]
movementType: HOVER
targetHeight:3
targetHeightDrift:0.8
moveSpeed: 0.7
landOnGround:false
moveAccelerationSpeed: 0.05
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0
turnAcceleration: 0.01
moveSlidingMode :true
moveIgnoringBody:true
moveSlidingDir:  181
reverseSpeedPercentage:0
joinsGroupFormations: false

[arm_1]
x: 0
y: 0
drawOverBody: true
spinRate:1

[arm_2]
x: 0
y: 0
drawOverBody: false
spinRate:2

[decal_body1]
onlyWhileAlive:true
order:0
imageScale:1
xOffsetRelative:0
yOffsetRelative:0
hOffset:14
layer: beforeBody
imageStack:aura.png
teamColors:true
basePositionFromLegEnd:arm_2

[decal_body2]
onlyWhileAlive:true
order:0
imageScale:0.9
xOffsetRelative:0
yOffsetRelative:0
hOffset:15
layer: afterBody
imageStack:ring.png
teamColors:true
basePositionFromLegEnd:arm_1

image_shadow: SHADOW:ring.png
shadowOffsetX:0
shadowOffsetY:0





