
[core]
name: highpeakOrcTech
tags:canBurn, building, tech
class: CustomUnitMetadata
price: Emerald=500, gazul=250
maxHp: 1750
mass: 9000

displayText: Eatery
displayDescription: "Many chef make duh soup better'."\n\n -Unlocks certain units\n -Can research upgrades

techLevel: 1
buildSpeed: 20s

radius: 35
footprint: -1,-1,1,1
constructionFootprint: -1,-1,1,2
buildingToFootprintOffsetX:10
buildingToFootprintOffsetY:0

isBuilding: true
isBio: false
numBitsOnDeath: 5


exit_y:35

################################# Techs #################################

[action_bloodlust]
isVisible: if not self.globalTeamTags(includes='orcBloodlust')
iconImage:ROOT:\data\images\feast.png
displayType:action
pos:1
text: Bloodlust
price: emerald=500, gazul=350
description: All orc infantry units will now heal a very small amount when they kill an enemy
addGlobalTeamTags: orcBloodlust
buildSpeed: 120s

[action_stampede]
isVisible: if not self.globalTeamTags(includes='orcStampede')
iconImage:ROOT:\data\images\meleeplus.png
displayType:action
pos:1
text: Stampede
price: emerald=600, gazul=450
description: Cleavers now have an automatically triggering charge, boosting their movespeed temporarily for a short duration when entering combat
addGlobalTeamTags: orcStampede
buildSpeed: 160s

[action_frenzy]
isVisible: if not self.globalTeamTags(includes='orcFrenzyUnlock')
iconImage:ROOT:\data\images\maul.png
displayType:action
pos:1
text: Frenzy
price: emerald=400, gazul=350
description: The Shaman can now cast Frenzy
addGlobalTeamTags: orcFrenzyUnlock
buildSpeed: 80s
################################# Graphics #################################

[graphics]
total_frames: 1
imageScale: 0.7

image:        base.png
image_back:  back.png
image_wreak:  NONE
image_turret: NONE

image_shadow: SHADOW:shadow.png
shadowOffsetX:0
shadowOffsetY:0

################################# Attack #################################

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

turretSize: 0
turretTurnSpeed: 1


maxAttackRange: 0
shootDelay: 2s

################################# Movement #################################

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0
turnAcceleration: 0.1

################################# AI #################################

[ai]

buildPriority: 0.4

noneInBaseExtraPriority: 0.1

maxEachBase: 1