[core]
copyFrom: ROOT:\data\templates\unitXp.template
name: highpeakGoblinWarMachine_3Cargo
displayText: Monster trek
tags:machine, normalVision, plate, large
displayDescription: -Large war machine\n -Well armed and armored\n -Powerful trample damage while it moves\n -Plated\n -Good vs infantry
class: CustomUnitMetadata
price: Emerald=1000, Gazoo=500, Lodging=4
borrowResourcesWhileBuilt:Lodging=4
showInEditor: false

maxHp: 1250
armour: 16
armourMinDamageToKeep: 0
mass: 9000

transportSlotsNeeded:5

energyMax: 14
energyRegen: 0.07
energyNeedsToRechargeToFull: true

techLevel: 1
buildSpeed: 30s
radius: 18
isBio: false
isBug: false
fogOfWarSightRange: 18
hideScorchMark: false
selfRegenRate:0
softCollisionOnAll: 25

################################# Death #################################

################################# Trample Damage #################################

[hiddenAction_charge]
autoTrigger:if self.isMoving()
fireTurretXAtGround: charge
fireTurretXAtGround_withOffset:0,30
[turret_charge]
x: 0
y: 0
size:0
canShoot:false
invisible: true
projectile: charge
turnSpeed: 40
[projectile_charge]
life: 140
speed: 10
drawSize: 0
targetGround:true
explodeEffect:NONE
areaDamageNoFalloff:true
areaRadiusFromEdge:true
deflectionPower: -1
areaDamage: 140
areaRadius: 15
buildingDamageMultiplier:1
mutator1_ifUnitWithTags:shield
mutator1_areaDamageMultiplier:0.5

################################# Graphics #################################

[action_plated]
iconImage:ROOT:\data\images\plated.png
displayType:action
pos:1
text: Plated
description: Passive\n -This unit is extremely resistant to small projectiles
buildSpeed: 0s
isVisible: true


[graphics]
showEnergyBar:false
drawLayer:experimentals
total_frames: 1
imageScale: 0.9
teamColorsOnTurret: true
image:        cargo.png
image_wreak:  ROOT:\data\images\rubble.png
image_shadow: AUTO
shadowOffsetX:2
shadowOffsetY:3
showTransportBar:false

movementEffect: NONE
movementEffectRate:10

dustEffect:true


[arm_1]
x: -10.5
y: -25
image_end: wheel.png
drawOverBody: false
moveSpeed: 0.5
rotateSpeed: 0
endDirOffset:1


[arm_2]
x: 11.5
y: -25
image_end: wheel.png
drawOverBody: false
moveSpeed: 0.5
rotateSpeed: 0
endDirOffset:1

[arm_3]
x: -10.5
y: -6
image_end: wheel.png
drawOverBody: false
moveSpeed: 0.5
rotateSpeed: 0
endDirOffset:1

[arm_4]
x: 11.5
y: -6
image_end: wheel.png
drawOverBody: false
moveSpeed: 0.5
rotateSpeed: 0
endDirOffset:1

[arm_5]
x: -10.5
y: -45
image_end: wheel.png
drawOverBody: false
moveSpeed: 0.5
rotateSpeed: 0
endDirOffset:1

[arm_6]
x: 11.5
y: -45
image_end: wheel.png
drawOverBody: false
moveSpeed: 0.5
rotateSpeed: 0
endDirOffset:1


################################# Weapons #################################

[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
aimOffsetSpread:0
turretSize: 16
turretTurnSpeed: 3
maxAttackRange: 100
shootDelay: 0.2s
turretMultiTargeting:true
attackMovement: bomber

[turret_1]
x:-10
y:4
idleDir:-15
shoot_sound:gun_fire
shoot_sound_vol:0.2
shoot_flame:NONE
shoot_light:#cdff00
recoilOffset: -1
recoilOutTime: 4
recoilReturnTime: 18
projectile:1
energyUsage: 1

[projectile_1]
mutatorShield_ifUnitWithTags:shield
mutatorShield_areaDamageMultiplier:0.35

mutatorPlate_ifUnitWithTags:plate
mutatorPlate_areaDamageMultiplier:0.25

areaDamage:30
areaRadius:15
targetGround:true
targetGround_includeTargetHeight:true
targetGroundSpread:15
armourIgnoreAmount:-8
life: 120
speed: 6
speedSpread:1
explodeEffect: NONE
buildingDamageMultiplier: 0.1
drawSize:0.5
color:#cdff00

################################# Movement #################################

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.005
maxTurnSpeed: 5
turnAcceleration: 0.05
moveSlidingMode :true
moveIgnoringBody:false
moveSlidingDir:  90
reverseSpeedPercentage:0
targetHeight:2
joinsGroupFormations: true

[hiddenAction_freezeIfNoParent]
autoTrigger: if not self.hasParent()
convertTo: highpeakGoblinWarMachine_3CargoBunker