[core]
copyFrom: ROOT:\data\templates\unitXp.template
name: highpeakGoblinWarMachine_3
displayText: Semi Trek
tags:machine, normalVision, shield, large
displayDescription: -Large transport truck\n -Well armored\n -Powerful trample damage while it moves\n -Shielded
class: CustomUnitMetadata
price: Emerald=1500, Gazoo=750, Lodging=6
borrowResourcesWhileBuilt:Lodging=6

maxHp: 1500
armour: 15 
armourMinDamageToKeep: 1
mass: 9000

transportSlotsNeeded:1000

energyMax: 14
energyRegen: 0.07
energyNeedsToRechargeToFull: true

techLevel: 1
buildSpeed: 30s
radius: 24
isBio: false
isBug: false
fogOfWarSightRange: 18
hideScorchMark: false
selfRegenRate:0
softCollisionOnAll: 25
maxTransportingUnits: 8
transportUnitsRequireTag: goblinSemiTransportable
transportUnitsUnloadDelayBetweenEachUnit:3

################################# Tech #################################

[hiddenAction_beetleTech]
autoTrigger: if self.globalTeamTags(includes='GobTruckTech')
convertTo: highpeakGoblinWarMachine_3Tech

################################# Trample Damage #################################

[hiddenAction_charge]
autoTrigger:if self.isMoving()
fireTurretXAtGround: charge
fireTurretXAtGround_withOffset:0,30
[turret_charge]
x: 0
y: 0
size:0
canShoot:false
invisible: true
projectile: charge
turnSpeed: 40
[projectile_charge]
life: 140
speed: 10
drawSize: 0
targetGround:true
explodeEffect:NONE
areaDamageNoFalloff:true
areaRadiusFromEdge:true
deflectionPower: -1
areaDamage: 140
areaRadius: 15
buildingDamageMultiplier:1
mutator1_ifUnitWithTags:shield
mutator1_areaDamageMultiplier:0.5

################################# Graphics #################################

[hiddenAction_smoke]
autoTrigger:true
spawnEffects:CUSTOM:smoke*2, CUSTOM:smoke2*2


[effect_smoke]
xOffsetRelative:8
yOffsetRelative:16
attachedToUnit: false
life: 150
alpha: 0.3
scaleFrom:0.3
scaleTo: 1.6
xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.1
hSpeed: 0.1
image: ROOT:\data\images\smokeGazoo.png
priority: low
drawUnderUnits:false
atmospheric:true

[effect_smoke2]
xOffsetRelative:-8
yOffsetRelative:16
attachedToUnit: false
life: 150
alpha: 0.3
scaleFrom:0.3
scaleTo: 1.6
xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.1
hSpeed: 0.1
image: ROOT:\data\images\smokeGazoo.png
priority: low
drawUnderUnits:false
atmospheric:true

[action_shield]
iconImage:ROOT:\data\images\shield.png
displayType:action
pos:1
text: Shield
description: Passive\n -This unit is resistant to small projectiles
buildSpeed: 0s
isVisible: true


[graphics]
showEnergyBar:false
drawLayer:experimentals
total_frames: 1
imageScale: 0.9
teamColorsOnTurret: true
image:        body.png
image_wreak:  ROOT:\data\images\rubble.png
image_shadow: AUTO
shadowOffsetX:2
shadowOffsetY:3
showTransportBar:false

movementEffect:CUSTOM:smoke*2, CUSTOM:smoke2*2
movementEffectRate:10

dustEffect:true


[arm_1]
x: -8.5
y: 14
image_end: wheel.png
drawOverBody: false
moveSpeed: 0.5
rotateSpeed: 1

[arm_2]
x: 9.5
y: 14
image_end: wheel.png
drawOverBody: false
moveSpeed: 0.5
rotateSpeed: 1

[arm_3]
x: -11
y: -4
image_end: wheel.png
drawOverBody: false
moveSpeed: 0.5
rotateSpeed: 1

[arm_4]
x:  12
y: -4
image_end: wheel.png
drawOverBody: false
moveSpeed: 0.5
rotateSpeed: 1

[attachment_Body1]
x: 0
y: -16
keepAliveWhenParentDies: false
canBeAttackedAndDamaged: true
setDrawLayerOnTop: true
rotateWithParent: false
lockRotation: false
idleDir: 0
resetRotationWhenNotAttacking: true
deattachIfWantingToMove: false
onCreateSpawnUnitOf: highpeakGoblinWarMachine_3Cargo
prioritizeParentsMainTarget: false
lockLegMovement: false
redirectDamageToParent: true
isUnselectable: true


[attachment_cargo1]
x: 5
y: -20
idleDir:0
isVisible:false
keepAliveWhenParentDies:true
addTransportedUnits:true
rotateWithParent:true

[attachment_cargo2]
x: 3
y: -25.25
idleDir:0
isVisible:false
keepAliveWhenParentDies:true
addTransportedUnits:true
rotateWithParent:true

[attachment_cargo3]
x: 0
y: -30.5
idleDir:0
isVisible:false
keepAliveWhenParentDies:true
addTransportedUnits:true
rotateWithParent:true

[attachment_cargo4]
x: 1
y: -35.75
idleDir:0
isVisible:false
keepAliveWhenParentDies:true
addTransportedUnits:true
rotateWithParent:true

[attachment_cargo5]
x: -1
y: -41
idleDir:0
isVisible:false
keepAliveWhenParentDies:true
addTransportedUnits:true
rotateWithParent:true

[attachment_cargo6]
x: 3
y: -46.25
idleDir:0
isVisible:false
keepAliveWhenParentDies:true
addTransportedUnits:true
rotateWithParent:true

[attachment_cargo7]
x: -5
y: -51.5
idleDir:0
isVisible:false
keepAliveWhenParentDies:true
addTransportedUnits:true
rotateWithParent:true

[attachment_cargo8]
x: -3
y: -60
idleDir:0
isVisible:false
keepAliveWhenParentDies:true
addTransportedUnits:true
rotateWithParent:true


################################# Weapons #################################

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
aimOffsetSpread:0
turretSize: 16
turretTurnSpeed: 3
maxAttackRange: 100
shootDelay: 0.2s
turretMultiTargeting:true
attackMovement: bomber

[turret_1]
x:-10
y:4
idleDir:-15
shoot_sound:gun_fire
shoot_sound_vol:0.2
shoot_flame:CUSTOM:toxicSmoke*1, CUSTOM:sparks*1
shoot_light:#cdff00
recoilOffset: -1
recoilOutTime: 4
recoilReturnTime: 18
projectile:1
energyUsage: 1

[turret_2]
x:10
y:4
idleDir:15
copyFrom:1

[projectile_1]
mutatorShield_ifUnitWithTags:shield
mutatorShield_areaDamageMultiplier:0.35

mutatorPlate_ifUnitWithTags:plate
mutatorPlate_areaDamageMultiplier:0.25

areaDamage:30
areaRadius:15
targetGround:true
targetGround_includeTargetHeight:true
targetGroundSpread:15
armourIgnoreAmount:-8
life: 120
speed: 6
speedSpread:1
explodeEffect: NONE
buildingDamageMultiplier: 0.1
drawSize:0.5
color:#cdff00

[effect_sparks]
attachedToUnit: false
life: 150
physics: true
xOffsetRelative: 2
xSpeedRelativeRandom: 0.6
ySpeedRelativeRandom: 0.6
hSpeed: 1
image: ROOT:\data\images\spark.png
priority: verylow

[effect_toxicSmoke]
attachedToUnit: true
alwayStartDirAtZero:true
life: 90
alpha: 0.4
scaleFrom:0.05
scaleTo: 0.9
dirOffsetRandom:90
dirSpeed:2
xOffsetRelative: 2
xSpeedRelativeRandom: 0.08
ySpeedRelative: 0.2
hSpeed: 0.1
image: ROOT:\data\images\smokeGazoo.png
priority: low

################################# Wheel Animations #################################

[animation_move]
onActions: move
arm1_0.1s: {height:-0.5,x:0, y:0.5, dir:5	}
arm2_0.1s: {height:-0.5,x:0, y:0.5, dir:-5	}
arm3_0.1s: {height:-0.5,x:0, y:0.5, dir:5	}
arm4_0.1s: {height:-0.5,x:0, y:0.5, dir:-5	}


################################# Movement #################################

[movement]
movementType: LAND
moveSpeed: 1.2
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.0075
maxTurnSpeed: 2
turnAcceleration: 0.15
moveSlidingMode :true
moveIgnoringBody:false
moveSlidingDir:  45
reverseSpeedPercentage:0
targetHeight:2
joinsGroupFormations: true