
[core]
name: highpeakTrollFarm
class: CustomUnitMetadata
tags: canBurn, building
price: Emerald=1000, Gazul=750
maxHp: 1000
mass: 9000

displayText: Sarsenn
displayDescription: -Slowly generates emerald patches nearby

techLevel: 1
buildSpeed: 12s

radius: 22
footprint: -1,-1,0,0
constructionFootprint: -1,-1,0,0
buildingToFootprintOffsetX:0
buildingToFootprintOffsetY:0

disableAllUnitCollisions:true

energyMax: 15
energyRegen: 0
dieOnZeroEnergy:true


isBuilder: true
autoRepair: true
nanoRepairSpeed: 0.5
nanoBuildSpeed: 2
canRepairBuildings: true
canRepairUnits:true
canRepairUnitsOnlyWithTags:emeraldResource
nanoRange: 50

explodeOnDeath:false
isBuilding: true
isBio: false
numBitsOnDeath: 0

################################# Placing Emeralds #################################

[hiddenAction_emeraldTimer]
autoTrigger: if self.customTimer(laterThanSeconds=60) and self.numberOfUnitsInTeam(withinRange=50, withTag='emeraldResource', lessThan=5)
alsoTriggerAction: emerald, emerald1, emerald2, emerald3, emerald4, 
resetCustomTimer:true

[hiddenAction_emerald]
requireConditional: if self.numberOfUnitsInTeam(withinRange=50, withTag='emeraldResource', equalTo=0)
addResources: energy=-1
spawnUnits: highpeakTrollFarm_1(gridAlign=true, offsetX=40, offsetY=0, skipIfOverlapping=true)

[hiddenAction_emerald1]
requireConditional: if self.numberOfUnitsInTeam(withinRange=50, withTag='emeraldResource', equalTo=1)
addResources: energy=-1
spawnUnits: highpeakTrollFarm_1(gridAlign=true, offsetX=-40, offsetY=0, skipIfOverlapping=true)

[hiddenAction_emerald2]
requireConditional: if self.numberOfUnitsInTeam(withinRange=50, withTag='emeraldResource', equalTo=2)
addResources: energy=-1
spawnUnits: highpeakTrollFarm_1(gridAlign=true, offsetX=0, offsetY=-40, skipIfOverlapping=true)

[hiddenAction_emerald3]
requireConditional: if self.numberOfUnitsInTeam(withinRange=50, withTag='emeraldResource', equalTo=3)
addResources: energy=-1
spawnUnits: highpeakTrollFarm_1(gridAlign=true, offsetX=25, offsetY=40, skipIfOverlapping=true)

[hiddenAction_emerald4]
requireConditional: if self.numberOfUnitsInTeam(withinRange=50, withTag='emeraldResource', equalTo=4)
addResources: energy=-1
spawnUnits: highpeakTrollFarm_1(gridAlign=true, offsetX=-25, offsetY=40, skipIfOverlapping=true)



[hiddenAction_onCreate]
addResources: energy=1
autoTriggerOnEvent: completeAndActive



[graphics]
total_frames: 1
imageScale: 0.85

image:        body.png
image_back:  back.png
image_wreak:  NONE
image_turret: NONE

image_shadow: AUTO
shadowOffsetX:0
shadowOffsetY:0.5

repairEffectAtTarget:CUSTOM:marker
repairEffectRate:25

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

turretSize: 0
turretTurnSpeed: 1


maxAttackRange: 1
shootDelay: 2s

[effect_marker]
color:green
alwayStartDirAtZero:true
fadeInTime:20
xOffsetRelative:0
yOffsetRelative:0
attachedToUnit: true
life: 250
alpha: 0.3
scaleFrom:1
scaleTo: 0
hSpeed: 0.2
xSpeedRelativeRandom: 0.2
ySpeedRelativeRandom: 0.2
image: ROOT:\data\images\marker.png
priority: high
drawUnderUnits:false

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0
turnAcceleration: 0.1



[ai]

buildPriority: 0.7

noneInBaseExtraPriority: 0.2

recommendedInEachBaseNum:5

[arm_1]
x: 1
y: -10

image_end: crystal.png
drawOverBody: true
spinRate:0

[animation_idle]
onActions: idle

arm1_0s: {x:0, y:0,height:0}
arm1_3s: {x:0, y:0,height:3}

pingPong:true