[core]
copyFrom: ROOT:\data\templates\unitXp.template
name: highpeakGoblinWarMachine_2Tech
displayText: Monster trek
tags:machine, normalVision, plate, large
displayDescription: -Large war machine\n -Well armed and armored\n -Powerful trample damage while it moves\n -Plated\n -Good vs infantry
class: CustomUnitMetadata
price: Emerald=1000, Gazoo=500, Lodging=4
borrowResourcesWhileBuilt:Lodging=4

maxHp: 1250
armour: 16
armourMinDamageToKeep: 0
mass: 9000

transportSlotsNeeded:5

energyMax: 14
energyRegen: 0.07
energyNeedsToRechargeToFull: true

techLevel: 1
buildSpeed: 30s
radius: 18
isBio: false
isBug: false
fogOfWarSightRange: 18
hideScorchMark: false
selfRegenRate:0
softCollisionOnAll: 25

[hiddenAction_smoke]
autoTrigger:true
spawnEffects:CUSTOM:smoke*3

[action_plated]
iconImage:ROOT:\data\images\plated.png
displayType:action
pos:1
text: Plated
description: Passive\n -This unit is extremely resistant to small projectiles
buildSpeed: 0s
isVisible: true

[hiddenAction_charge]
autoTrigger:if self.isMoving()
fireTurretXAtGround: charge
fireTurretXAtGround_withOffset:0,30
[turret_charge]
x: 0
y: 0
size:0
canShoot:false
invisible: true
projectile: charge
turnSpeed: 40
[projectile_charge]
life: 140
speed: 10
drawSize: 0
targetGround:true
explodeEffect:NONE
areaDamageNoFalloff:true
areaRadiusFromEdge:true
deflectionPower: -1
areaDamage: 140
areaRadius: 15
buildingDamageMultiplier:1
mutator1_ifUnitWithTags:shield
mutator1_areaDamageMultiplier:0.5

[graphics]
showEnergyBar:false
drawLayer:experimentals
scaleTurretImagesTo:10
total_frames: 1
imageScale: 0.9
teamColorsOnTurret: true
image:        body.png
image_wreak:  ROOT:\data\images\rubble.png
image_turret: turret.png
image_shadow: AUTO
shadowOffsetX:2
shadowOffsetY:3
showTransportBar:false

movementEffect:CUSTOM:smoke*2
movementEffectRate:10

dustEffect:true

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
aimOffsetSpread:0
turretSize: 16
turretTurnSpeed: 3
maxAttackRange: 125
shootDelay: 0.2s
turretMultiTargeting:true
attackMovement: bomber

[turret_1]
x:-10
y:4
idleDir:-15
image:turret2.png
shoot_sound:gun_fire
shoot_sound_vol:0.2
shoot_flame:CUSTOM:toxicSmoke*1, CUSTOM:sparks*1
shoot_light:#cdff00
recoilOffset: -1
recoilOutTime: 4
recoilReturnTime: 18
projectile:1
energyUsage: 1
limitingRange:100

[turret_2]
x:10
y:4
idleDir:15
image:turret.png
copyFrom:1

[turret_3]
x: 0
y: 3
shoot_sound:ROOT:\data\soundFx\energy.ogg
shoot_sound_vol:0.2
shoot_flame:CUSTOM:toxicSmoke2*1, CUSTOM:sparks2*1
shoot_light:#cdff00
recoilOffset:-1
recoilOutTime: 15
recoilReturnTime: 18
projectile:2
image:turret3.png
idleDir:30
delay: 1s

[projectile_2]

mutatorShield_ifUnitWithTags:shield
mutatorShield_areaDamageMultiplier:0.5

mutatorPlate_ifUnitWithTags:plate
mutatorPlate_areaDamageMultiplier:0.5

color:GREEN

areaDamage:75
areaHitAirAndLandAtSameTime:true
areaRadius:20
targetGround:true
targetGround_includeTargetHeight:true
targetGroundSpread:15
#directDamage: 40
armourIgnoreAmount:-8

life: 120
speed: 4
speedSpread:0.5
image: ROOT:\data\images\magicFire.png
explodeEffect: NONE

lightColor:#cdff00

buildingDamageMultiplier: 0.25
drawSize:0.6
shadowFrame:11
trailEffect:CUSTOM:trail2
trailEffectRate:1

[effect_trail2]
color:#cdff00
createWhenZoomedOut: false
image: ROOT:\data\images\trail.png
life: 20
fadeOut: true
attachedToUnit: false
fadeInTime:2
scaleFrom: 0.3
scaleTo: 0.1
alpha: 0.6
drawUnderUnits:false

[effect_sparks2]
attachedToUnit: false
life: 150
physics: true
xOffsetRelative: 2
xSpeedRelativeRandom: 0.6
ySpeedRelativeRandom: 0.6
hSpeed: 1
image: ROOT:\data\images\spark.png
priority: verylow

[effect_toxicSmoke2]
attachedToUnit: true
alwayStartDirAtZero:true
life: 90
alpha: 0.4
scaleFrom:0.05
scaleTo: 0.9
dirOffsetRandom:90
dirSpeed:2
xOffsetRelative: 2
xSpeedRelativeRandom: 0.08
ySpeedRelative: 0.2
hSpeed: 0.1
image: ROOT:\data\images\smokeGazoo.png
priority: low


[projectile_1]
mutatorShield_ifUnitWithTags:shield
mutatorShield_areaDamageMultiplier:0.35

mutatorPlate_ifUnitWithTags:plate
mutatorPlate_areaDamageMultiplier:0.25

areaDamage:30
areaRadius:15
targetGround:true
targetGround_includeTargetHeight:true
targetGroundSpread:15
armourIgnoreAmount:-8
life: 120
speed: 6
speedSpread:1
explodeEffect: NONE
buildingDamageMultiplier: 0.1
drawSize:0.5
color:#cdff00

[effect_sparks]
attachedToUnit: false
life: 150
physics: true
xOffsetRelative: 2
xSpeedRelativeRandom: 0.6
ySpeedRelativeRandom: 0.6
hSpeed: 1
image: ROOT:\data\images\spark.png
priority: verylow

[effect_toxicSmoke]
attachedToUnit: true
alwayStartDirAtZero:true
life: 90
alpha: 0.4
scaleFrom:0.05
scaleTo: 0.9
dirOffsetRandom:90
dirSpeed:2
xOffsetRelative: 2
xSpeedRelativeRandom: 0.08
ySpeedRelative: 0.2
hSpeed: 0.1
image: ROOT:\data\images\smokeGazoo.png
priority: low

[effect_smoke]
xOffsetRelative:-3
yOffsetRelative:-16
attachedToUnit: false
life: 150
alpha: 0.5
scaleFrom:0.3
scaleTo: 1.6
xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.1
hSpeed: 0.1
image: ROOT:\data\images\smokeGazoo.png
priority: low
drawUnderUnits:false
atmospheric:true

[arm_1]
x: -11.5
y: 9
image_end: wheel.png
drawOverBody: false
moveSpeed: 0.5
rotateSpeed: 1

[arm_2]
x: 12
y: 9
image_end: wheel.png
drawOverBody: false
moveSpeed: 0.5
rotateSpeed: 1

[arm_3]
x: -11.5
y: -6
image_end: wheel.png
drawOverBody: false
moveSpeed: 0.5
rotateSpeed: 1

[arm_4]
x: 12
y: -6
image_end: wheel.png
drawOverBody: false
moveSpeed: 0.5
rotateSpeed: 1

[animation_move]
onActions: move
arm1_0.1s: {height:-1,x:0, y:1, dir:10}
arm2_0.1s: {height:-1,x:0, y:1, dir:-10}
arm3_0.1s: {height:-1,x:0, y:1, dir:-10}
arm4_0.1s: {height:-1,x:0, y:1, dir:10}

[animation_idle]
onActions: idle
arm1_0s: {height:-1,x:0, y:0, dir:15}
arm2_0s: {height:-1,x:0, y:0, dir:15}
arm3_0s: {height:-1,x:0, y:0, dir:-2}
arm4_0s: {height:-1,x:0, y:0, dir:2}


[movement]
movementType: LAND
moveSpeed: 1
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.005
maxTurnSpeed: 2
turnAcceleration: 0.1
moveSlidingMode :true
moveIgnoringBody:false
moveSlidingDir:  181
reverseSpeedPercentage:0
targetHeight:2
joinsGroupFormations: true