
[core]
showInEditor:false
name: highpeakHumanFarmDepleted
tags: canBurn, building
class: CustomUnitMetadata
price: localFood=6000
maxHp: 300
mass: 9000
isUnrepairableUnit:true

energyStartingPercentage:0
energyMax: 100
energyRegen: 0.03
selfRegenRate: 0.005

displayText: Barren Ranch
displayDescription: "Best yak breeders in the region... also the only ones"\n\n -Can train Infantry\n -No food left, must be replanted to provide Yaks and Food\n -Extremely fragile

techLevel: 1
buildSpeed: 20s

radius: 50
footprint: -2,-3,1,0
constructionFootprint: -2,-3,1,1
buildingToFootprintOffsetX:-3
buildingToFootprintOffsetY:-5

isBuilding: true
isBio: false
numBitsOnDeath: 5
exit_y:35
exit_moveAwayAmount:40

################################# Rancher Tech #################################

[hiddenAction_rancherTechRecover]
autoTrigger: if self.resource(type='humanBuildingRancher', lessThan=30)
addResources: humanBuildingRancher=1

[hiddenAction_rancherTechTrigger]
requireConditional: if self.resource(type='humanBuildingRancher', equalTo=30)
autoTriggerOnEvent: tookDamage
spawnUnits: highpeakHumanTempRancher*2
addResources: humanBuildingRancher=-30

[hiddenAction_startingYak]
autoTriggerOnEvent:completeAndActive
addResources:Yak=1

[action_restock]
convertTo: highpeakHumanFarmReady
setUnitStats: hp += ${core.maxHp}
price: emerald=400
text: Raise Yaks
description: Raise new Yaks, resetting food to max and allowing Yaks to be created again
iconImage:yak.png

###############################################################

[hiddenAction_haveYaks]
autoTrigger: if self.resource(type='Yak', greaterThan=0) and not self.tags(includes='haveYaks')
temporarilyAddTags: haveYaks

[hiddenAction_dontHaveYaks]
autoTrigger: if self.resource(type='Yak', lessThan=1) and self.tags(includes='haveYaks')
temporarilyRemoveTags: haveYaks

[arm_1]
hidden: if self.resource(type='Yak', lessThan=1)
x:-21
y:38
image_end:yak.png
drawOverBody:false

[arm_2]
hidden: if self.resource(type='Yak', lessThan=2)
endDirOffset:-120
x:-1
y:38
image_end:yak.png
drawOverBody:false

[arm_3]
hidden: if self.resource(type='Yak', lessThan=3)
endDirOffset:135
x:22
y:38
image_end:yak.png
drawOverBody:false

###############################################################

[canBuild_Recruit]
name:setRally, highpeakHumanInfantry_1
pos: 2.2
addResources: Lodging=1


[effect_marker]
teamColorRatio:1
fadeInTime:20
xOffsetRelative:0
yOffsetRelative:0
attachedToUnit: true
life: 200
alpha: 0.3
scaleFrom:0.6
scaleTo: 0.2
hSpeed: 0.2
image: marker.png
priority: high
drawUnderUnits:false

[effect_markerRed]
color:red
fadeInTime:20
xOffsetRelative:0
yOffsetRelative:0
attachedToUnit: true
life: 200
alpha: 0.3
scaleFrom:0.6
scaleTo: 0.2
hSpeed: 0.2
image: marker.png
priority: high
drawUnderUnits:false


[graphics]
total_frames: 1
imageScale: 0.9

image:        baseDepleted.png
image_back:  back.png
image_wreak:  NONE
image_turret: NONE

image_shadow: SHADOW:shadow.png
shadowOffsetX:0
shadowOffsetY:0

repairEffect:NONE
repairEffectAtTarget:CUSTOM:marker
repairEffectRate:25
reclaimEffect:NONE
reclaimEffectAtTarget:CUSTOM:markerRed
reclaimEffectRate:25



[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

turretSize: 0
turretTurnSpeed: 1


maxAttackRange: 125
shootDelay: 2s


[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0
turnAcceleration: 0.1



[ai]

buildPriority: 0.7

noneInBaseExtraPriority: 0.2

recommendedInEachBaseNum:3

