
[core]
name: highpeakPlagueOrcMound
class: CustomUnitMetadata
tags: canBurn, building, plagueOrcBuilding, mound
price: Emerald=200, gazul=75, energy=50
maxHp: 500
mass: 9000

displayText: Larva Mound
displayDescription: -Defensive structure\n -Spawns larva passively, which raise corpses into Husks\n -No attack

techLevel: 1
buildSpeed: 8s

radius: 22
footprint: 0,0,0,0
constructionFootprint: 0,0,0,0
buildingToFootprintOffsetX:11
buildingToFootprintOffsetY:10

disableAllUnitCollisions:true

explodeOnDeath:false
isBuilding: true
isBio: true
numBitsOnDeath: 0

################################# Abilities #################################

[action_larva]
iconImage:ROOT:\data\images\addon.png
displayType:action
pos:1
text: Hive
description: Passive\n -Spawns larva over time, which raise corpses into Husks
buildSpeed: 0s
isVisible: true

[hiddenAction_larvaSpawn]
autoTrigger: if self.customTimer(laterThanSeconds=30) and not self.numberOfUnitsInTeam(withinRange=75, withTag='larva', greaterThan=0)
fireTurretXAtGround_withTarget: self
fireTurretXAtGround: 1
resetCustomTimer: true
alsoTriggerAction:largeLarva

[hiddenAction_largeLarva]
requireConditional: if self.globalTeamTags(includes='plagueOrcLarvaTech')
spawnUnits: highpeakPlagueOrcLargeLarva


################################# Graphics #################################

[hiddenAction_smoke]
autoTrigger:true
spawnEffects:CUSTOM:smoke

[effect_smoke]
xOffsetRelativeRandom:10
yOffsetRelativeRandom:10
attachedToUnit: false
life: 400
alpha: 0.3
scaleFrom:0.5
scaleTo: 1
#physics: true
xSpeedRelativeRandom: 0.07
ySpeedRelativeRandom: 0.07
hSpeed: 0.1
image: ROOT:\data\images\sick.png
priority: low
drawUnderUnits:false
atmospheric:true
fadeInTime:40


[graphics]
total_frames: 1
imageScale: 0.6

image:        base.png
image_back:  back.png
image_wreak:  NONE
image_turret: NONE

image_shadow: AUTO
shadowOffsetX:0
shadowOffsetY:0.5

animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 120
animation_idle_scale_start:1
animation_idle_scale_end:1.03
animation_idle_pingPong: true

################################# Attack #################################

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

turretSize: 0
turretTurnSpeed: 1


maxAttackRange: 50
shootDelay: 2s

[turret_1]
x: 0
y: 0
shoot_sound:ROOT:\data\soundFx\darkmissile.ogg
shoot_sound_vol:0.2
recoilOffset:3
recoilOutTime: 15
recoilReturnTime: 18

[projectile_1]
areaDamage:0
areaRadius:0

life: 7
speed: 1
image: NONE
drawSize:0.01
gravity:0.18
shadowFrame:11
explodeOnEndOfLife: true
explodeEffect: CUSTOM:spit*5, CUSTOM:spit2*15

spawnUnit:highpeakPlagueOrcMoundLarva*3


[effect_spit]
createWhenZoomedOut: false
image: ROOT:\data\images\plague.png
life: 50
fadeOut: true
attachedToUnit: false
dirOffsetRandom:75
xOffsetRelativeRandom:3
yOffsetRelativeRandom:3
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.5
fadeInTime:2
scaleFrom: 0.8
scaleTo: 1.2
alpha: 0.6
drawUnderUnits:false
physics:false

[effect_spit2]
attachedToUnit: false
life: 120
physics: true
scaleFrom:1.5
scaleTo: 0.2
xOffsetRelativeRandom:3
yOffsetRelativeRandom:3
xSpeedRelativeRandom: 0.8
ySpeedRelativeRandom: 0.8
hSpeed: 1
image: ROOT:\data\images\gunk.png
drawUnderUnits:false
dirOffsetRandom:60


################################# Movement #################################

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0
turnAcceleration: 0.1

################################# Ai #################################

[ai]

buildPriority: 0.7

noneInBaseExtraPriority: 0.2

recommendedInEachBaseNum:5

