
[core]
name: highpeakForeignLegionTech
tags:canBurn, building
class: CustomUnitMetadata
price: Emerald=500, gazul=350	
maxHp: 2500
mass: 9000

displayText: FLTech
displayDescription: ""\n\n -Can research technology

techLevel: 1
buildSpeed: 20s

radius: 35
footprint: -2,-1,1,1
constructionFootprint: -2,-1,1,2
buildingToFootprintOffsetX:0
buildingToFootprintOffsetY:0

isBuilding: true
isBio: false
numBitsOnDeath: 5
exit_y:35

################################# Techs #################################

[action_flodHelpTech]
isVisible: if not self.globalTeamTags(includes='flodHelpTech')
iconImage:ROOT:\data\images\ranged.png
displayType:action
pos:1
text: Flodrjinai Escorts
price: emerald=1250, gazul=1000
description: All Requisition requests from the Ministerium and Depot will now be accompanied by Flodrjinai units
addGlobalTeamTags: flodHelpTech
buildSpeed: 180s

[action_auxilaTech]
isVisible: if not self.globalTeamTags(includes='FLAuxilaTech')
iconImage:ROOT:\data\images\ranged.png
displayType:action
pos:1
text: Reduce Quality of Life
price: emerald=250, gazul=700
description: All auxila infantry are 10% cheaper
addGlobalTeamTags: FLAuxilaTech
buildSpeed: 60s

[action_beetleTech]
isVisible: if not self.globalTeamTags(includes='FLBeetleTech')
iconImage:ROOT:\data\images\ranged.png
displayType:action
pos:1
text: Scarabai Funding
price: emerald=750, gazul=850
description: Auxila beetles/flargs can transport more units.\n Skarabai Testudos and Karavanjai Testudos now burn everything with their mortars, not just structures.
addGlobalTeamTags: FLBeetleTech, FLMortarTech
buildSpeed: 140s



[action_requisition]
iconImage:ROOT:\data\images\requisitionIcon.png
displayType:action
pos:0
text: Requisition
description: Passive\n -Generates 0.3 Requisition points every 10 seconds
buildSpeed: 0s
isVisible: true

[hiddenAction_requisitionTrickle]
autoTrigger: if self.customTimer(laterThanSeconds=10)
addResources: Requisition=0.3
resetCustomTimer: true

[graphics]
total_frames: 1
imageScale: 0.9

image:        base.png
image_back:  back.png
image_wreak:  NONE
image_turret: NONE

image_shadow: NONE
shadowOffsetX:0
shadowOffsetY:2



[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

turretSize: 0
turretTurnSpeed: 1


maxAttackRange: 0
shootDelay: 2s


[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0
turnAcceleration: 0.1



[ai]

buildPriority: 0.30

noneGlobalExtraPriority: 0.1

maxEachBase: 1