
[core]
showInEditor:false
name: highpeakNeutralRavanCamp
tags: ravanCamp, canBurn, neutralTribe, building
class: CustomUnitMetadata
price: 0
maxHp: 2000
mass: 9000

displayText: Ravan cabin
displayDescription: -Ravan hunting camp\n -Can recruit up to 10 ravan hunters\n -Slowly generate Emeralds\n -Can be taken over

techLevel: 1
buildSpeed: 20s

radius: 36
footprint: -1,-1,1,0
constructionFootprint: -1,-1,1,1
buildingToFootprintOffsetX:10
buildingToFootprintOffsetY:0

isBuilding: true
isBio: true
numBitsOnDeath: 5
hideScorchMark: true
exit_y:15

unitsSpawnedOnDeath:highpeakNeutralRavanCamp
unitsSpawnedOnDeath_setToTeamOfLastAttacker:true

[hiddenAction_kms]
autoTrigger: true
requireConditional: if self.numberOfUnitsInAllTeams(withTag='managerResources', withinRange=100, greaterThan=0)
deleteSelf: true

[hiddenAction_emeraldTimer]
autoTrigger: if self.customTimer(laterThanSeconds=8)
alsoTriggerAction: emeraldLvL1
resetCustomTimer:true
[hiddenAction_emeraldLvL1]
addResourcesScaledByAIHandicaps: Emerald=10
spawnEffects:CUSTOM:produceEmerald

[effect_produceEmerald]
alwayStartDirAtZero:true
attachedToUnit: false
life: 100
alpha: 1
hOffset:16
hSpeed: 0.3
image: ROOT:\data\images\emerald10.png
priority: high
drawUnderUnits:false
scaleFrom:1.2
scaleTo: 1.2

[hiddenAction_smoke]
autoTrigger:true
spawnEffects:CUSTOM:smoke*3

[effect_smoke]
xOffsetRelative:17
yOffsetRelative:0
attachedToUnit: false
life: 400
alpha: 0.3
scaleFrom:0.5
scaleTo: 2
#physics: true
xSpeedRelativeRandom: 0.07
ySpeedRelativeRandom: 0.07
hSpeed: 0.1
image: ROOT:\data\images\smoke.png
priority: low
drawUnderUnits:false
atmospheric:true
fadeInTime:40

[hiddenAction_taken]
autoTriggerOnEvent:completeAndActive
showMessageToPlayer: Ravan boss: Ok! Ok! We hunt for you. More profit... ok?

[hiddenAction_lost]
autoTrigger:if numberOfUnitsInTeam(withTag='faction', lessThan=1)
spawnUnits:highpeakNeutralRavanCampNeutral
alsoTriggerAction:delete
[hiddenAction_delete]
deleteSelf:true

[canBuild_Warrior]
name:setRally, highpeakNeutralRavan
isLocked: if numberOfUnitsInTeam(withTag='ravan', greaterThan=9, factoryQueue=true) or self.isControlledByAi
pos: 1

[graphics]
total_frames: 1
imageScale: 0.8
image:        base.png
image_back:  back.png
image_wreak:  NONE
image_turret: NONE

image_shadow: SHADOW:shadow.png
shadowOffsetX:0
shadowOffsetY:0



[attack]

canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
turretSize: 0
turretTurnSpeed: 1
maxAttackRange: 0
shootDelay: 2s


[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0
turnAcceleration: 0.1

