
[core]
name: highpeakHumanBarracks
tags: highpeakbarracks, canBurn, building
class: CustomUnitMetadata
price: Emerald=600
maxHp: 2200
mass: 9000

displayText: Saloon
displayDescription: "Need a drink or a hired sword? This is your place... mind the mead though, it's bitter than life"\n\n -Can train advance Infantry units

techLevel: 1
buildSpeed: 20s

radius: 30
footprint: -1,-1,0,0
constructionFootprint: -2,-2,1,1
buildingToFootprintOffsetX:0
buildingToFootprintOffsetY:-5

isBuilding: true
isBio: false
numBitsOnDeath: 5


exit_y:30
exit_moveAwayAmount:40

################################# Rancher Tech #################################

[hiddenAction_rancherTechRecover]
autoTrigger: if self.resource(type='humanBuildingRancher', lessThan=30)
addResources: humanBuildingRancher=1

[hiddenAction_rancherTechTrigger]
requireConditional: if self.resource(type='humanBuildingRancher', equalTo=30)
autoTriggerOnEvent: tookDamage
spawnUnits: highpeakHumanTempRancher*4
addResources: humanBuildingRancher=-30


[canBuild_Recruit]
name:setRally, highpeakHumanInfantry_3, highpeakHumanInfantry_2, highpeakHumanArcher_1, highpeakHumanArcher_2
pos: 0.1
addResources: Lodging=1


[graphics]
total_frames: 3
imageScale: 0.9

image:        base.png
image_back:  back.png
image_wreak:  NONE
image_turret: NONE

image_shadow: SHADOW:shadow.png
shadowOffsetX:0
shadowOffsetY:0

[animation_idle]
onActions: idle
KeyframeTimeScale : 0.8
body_0s: {frame:0}
body_0.1s: {frame:0}
body_0.2s: {frame:1}
body_0.3s: {frame:1}
body_0.4s: {frame:2}
body_0.5s: {frame:2}


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

turretSize: 0
turretTurnSpeed: 1


maxAttackRange: 0
shootDelay: 2s


[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0
turnAcceleration: 0.1



[ai]

buildPriority: 0.45

noneInBaseExtraPriority: 0.1

maxEachBase: 2

