
[core]
copyFrom: ROOT:\data\templates\unitXp.template, ROOT:\data\templates\healerEffect.template
tags:machine, normalVision, center, greatEmerald, factionGoblin
name: highpeakGoblinSpaceShip
displayText: Gaztrooyer
displayDescription: -Armored battlecruiser\n-Heavily armed and armored \n-Good vs everything\n-Can transport units\n-Can train robogoblins and clone the captain\n -Can research technology\n -Heal nearby units\n -Defend at all cost\n -Provides 10 lodging

borrowResourcesWhileBuilt:lodging=-10

class: CustomUnitMetadata
price: 0
maxHp: 2000
armour:8
mass: 500000

maxTransportingUnits:6
transportUnitsCanUnloadUnits:if not self.isOverLiquid()
transportUnitsUnloadDelayBetweenEachUnit:6
transportUnitsKeepBuiltUnits:true

energyMax: 100
energyRegen: 1
energyNeedsToRechargeToFull: true

fogOfWarSightRange:10

techLevel: 1
experimental: false
buildSpeed: 60s

radius: 27
isBio: false
isBug: false

numBitsOnDeath: 5
hideScorchMark: true
selfRegenRate:0
softCollisionOnAll: 75

################################# Death #################################

[hiddenAction_deathExplosion]
requireConditional: if not game.nukesEnabled()
autoTriggerOnEvent:destroyed
fireTurretXAtGround:death


[effect_deathExplode]
priority:critical
attachedToUnit: false
life: 180
physics: true
scaleFrom:2.5
scaleTo: 0.6
xSpeedRelativeRandom: 12
ySpeedRelativeRandom: 12
hSpeed: 2
image: ROOT:\data\images\pixel.png
drawUnderUnits:false
color:green

################################# Build #################################

[canBuild_builder]
name: repair, highpeakGoblinBuilder_1
pos: 2.1

[canBuild_heroGoblin]
name: highpeakGoblinHero
isVisible:if self.globalTeamTags(includes='factionGoblin')
isLocked: if numberOfUnitsInTeam(withTag='hero', greaterThan=0, factoryQueue=true)
isLockedMessage:Your explorer is alive
pos:2.2

################################# Techs #################################

[action_truckTech]
isVisible: if not self.globalTeamTags(includes='GobTruckTech')
iconImage:ROOT:\data\images\ranged.png
displayType:action
pos:1
text: Corporate Secrets
price: emerald=500, gazoo=750
description: Semi Treks can now transport an extra four units, and drop their trailer on death as a bunker. Monster Treks gain an enforcer.
addGlobalTeamTags: GobTruckTech
buildSpeed: 160s

################################# Graphics #################################

[effect_trail]
color:#cdff00
xOffsetRelative:-14
yOffsetRelative:-48

createWhenZoomedOut: false
priority:high

image: ROOT:\data\images\trail.png
life: 25
fadeOut: true
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0
alpha: 2
ySpeedRelative:-0.4

[effect_trail2]
color:#cdff00
xOffsetRelative:14
yOffsetRelative:-48

createWhenZoomedOut: false
priority:high

image: ROOT:\data\images\trail.png
life: 25
fadeOut: true
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0
alpha: 2
ySpeedRelative:-0.4


[graphics]
teamColorsOnTurret:true
imageScale: 1.1
total_frames: 1
showEnergyBar:false
movementEffect:CUSTOM:trail, CUSTOM:trail2
movementEffectRate:1

image:        body.png
image_wreak:  NONE
image_turret: turret.png

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1

################################# Alarm #################################

[hiddenAction_onCreateAmmo]
requireConditional: if not game.nukesEnabled()
autoTriggerOnEvent: created
addResources: ammo=15

[hiddenAction_alarmTimer]
requireConditional: if not game.nukesEnabled()
autoTrigger: if self.ammo(lessThan=15)
addResources: ammo=1

[hiddenAction_alarm]
autoTriggerOnEvent: tookDamage
requireConditional:if self.ammo(greaterThan=14)
addResources: ammo=-15
showMessageToPlayer: OUR GAZTROOYER IS UNDER ATTACK!
playSoundToPlayer:ROOT:\data\soundFx\alarm.ogg:0.3

################################# Weapons #################################

[attack]
aimOffsetSpread:0
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 25
turretTurnSpeed: 20
turretMultiTargeting:true

maxAttackRange: 175
shootDelay: 3

[turret_1]
x: 0
y: 0
canShoot:false
invisible:true
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

[turret_2]
canAttackFlyingUnits: false
x: 0
y: 3
attachedTo:1
shoot_sound:plasma_fire
shoot_sound_vol:0.05
shoot_light:#b9ff45
projectile:1
energyUsage: 7
invisible:true

[projectile_1]

sweepOffset:12
sweepSpeed:1
moveWithParent:true
instantReuseLast:true
instantReuseLast_alsoChangeTurretAim:true

areaDamage: 9
areaRadius:30
armourIgnoreAmount:100
life: 8
instant:true
explodeEffect:CUSTOM:sparks*1
drawSize:1
laserEffect:true
color:#dbff9f
lightColor:#dbff9f

[turret_mini1]
x: -20
y: 3
turnSpeed:2
size:12
delay:0.7s
shoot_sound:ROOT:\data\soundFx\energy.ogg
shoot_sound_vol:0.2
shoot_flame:CUSTOM:toxicSmoke*1, CUSTOM:sparks*1
shoot_light:#cdff00
recoilOffset:-1
recoilOutTime: 15
recoilReturnTime: 18
projectile:2

idleDir:-30

[turret_mini2]
x: 20
y: 3
copyFrom:mini1
idleDir:30
warmup:10
linkDelayWithTurret:mini1

[projectile_2]

mutatorShield_ifUnitWithTags:shield
mutatorShield_areaDamageMultiplier:0.5

mutatorPlate_ifUnitWithTags:plate
mutatorPlate_areaDamageMultiplier:0.5

color:GREEN

areaDamage:75
areaHitAirAndLandAtSameTime:true
areaRadius:15
targetGround:true
targetGround_includeTargetHeight:true
targetGroundSpread:15
#directDamage: 40
armourIgnoreAmount:-8

life: 120
speed: 4
speedSpread:0.5
image: ROOT:\data\images\magicFire.png
explodeEffect: NONE

lightColor:#cdff00

buildingDamageMultiplier: 0.25
drawSize:0.6
shadowFrame:11
trailEffect:CUSTOM:projectileTrail
trailEffectRate:1

[effect_projectileTrail]
color:#cdff00
createWhenZoomedOut: false
image: ROOT:\data\images\trail.png
life: 20
fadeOut: true
attachedToUnit: false
fadeInTime:2
scaleFrom: 0.3
scaleTo: 0.1
alpha: 0.6
drawUnderUnits:false

[effect_sparks]
attachedToUnit: false
life: 150
physics: true
xOffsetRelative: 2
xSpeedRelativeRandom: 0.6
ySpeedRelativeRandom: 0.6
hSpeed: 1
image: ROOT:\data\images\spark.png
priority: verylow

[effect_toxicSmoke]
attachedToUnit: true
alwayStartDirAtZero:true
life: 90
alpha: 0.4
scaleFrom:0.05
scaleTo: 0.9
dirOffsetRandom:90
dirSpeed:2
xOffsetRelative: 2
xSpeedRelativeRandom: 0.08
ySpeedRelative: 0.2
hSpeed: 0.1
image: ROOT:\data\images\smokeGazoo.png
priority: low

[turret_death]
x: 0
y: 0
canShoot:false
invisible:true
projectile:death

[projectile_death]
spawnProjectilesOnExplode:death
areaDamage: 100000
areaRadius:500000
areaDamageNoFalloff:true
areaHitAirAndLandAtSameTime:true
areaHitUnderwaterAlways:true
armourIgnoreAmount:100
friendlyFire:only-ignoreEnemy
life: 120
speed:50
explodeEffect:shockwave, CUSTOM:deathExplode*100
drawSize:0

################################# Movement #################################

[movement]
movementType: AIR
moveSpeed: 0.6
moveAccelerationSpeed: 0.02
moveDecelerationSpeed: 0.01
joinsGroupFormations: true

targetHeightDrift:3

maxTurnSpeed: 2
turnAcceleration: 1

moveSlidingMode :false
moveIgnoringBody:true
moveSlidingDir:  100
reverseSpeedPercentage:0


################################# AI #################################

[hiddenAction_aiBoost]
autoTrigger: if self.resource(type='Emerald',lessThan=2000)
requireConditional: if self.isControlledByAI()
addResources: Emerald=10




