
[core]
copyFrom: ROOT:\data\templates\unitXp.template, ROOT:\data\templates\drowning.template
name: highpeakLonguiSiege_1
tags:machine, normalVision, canBurn, tieyu
displayText: Tieyu
displayDescription: -Long ranged war machine \n -Good vs infantry and cavalry\n -Slow
class: CustomUnitMetadata
price: Emerald=450, Gazul=350, Lodging=2
borrowResourcesWhileBuilt:Lodging=2
maxHp: 250
armour:8
mass: 1000

techLevel: 1
experimental: false
buildSpeed: 25s

transportSlotsNeeded:2

energyMax: 15
energyRegen: 0.05
energyNeedsToRechargeToFull: true

radius: 10
isBio: false
isBug: false
fogOfWarSightRange: 18
hideScorchMark: true
selfRegenRate:0
softCollisionOnAll: 12
explodeOnDeath:false
effectOnDeath:smoke*3

################################# Arrow Tech #################################

[hiddenAction_arrowTech]
autoTrigger: if self.globalTeamTags(includes='longuiArrowTech')
convertTo: highpeakLonguiSiege_1Tech


[graphics]
imageScale: 0.65
scaleTurretImagesTo:5
total_frames: 6
showEnergyBar:false
image:        body.png
image_wreak:  ROOT:\data\images\medium_dead_wood.png
image_turret: turret.png

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1


animation_moving_start: 1
animation_moving_end: 3
animation_moving_speed: 6
animation_moving_pingPong: true

animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 120
animation_idle_scale_start:1
animation_idle_scale_end:1.03
animation_idle_pingPong: true

animation_attack_start: 4
animation_attack_end: 5
animation_attack_speed: 10

lock_body_rotation_with_main_turret: true

[attack]

canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
isFixedFiring: true
turretSize: 6
turretTurnSpeed: 3

maxAttackRange: 200
shootDelay: 1s

[turret_base]
x: 0
y: 0
invisible:true
canShoot:false
recoilOffset:-2
recoilOutTime: 7
recoilReturnTime: 18

[turret_1]
x: -4
y: 5
attachedTo:base
slave:true
shoot_sound:ROOT:\data\soundFx\shootGun.ogg
shoot_sound_vol:0.3
projectile:main
energyUsage: 15
limitingMinRange:30

[turret_2]
x: 0
y: 5
copyFrom:1
warmup:15
linkDelayWithTurret:1
energyUsage: 0

[turret_3]
x: 4
y: 5
copyFrom:1
warmup:30
linkDelayWithTurret:1
energyUsage: 0

[projectile_main]
spawnProjectilesOnCreate:secondary*4

mutatorShield_ifUnitWithTags:shield
mutatorShield_areaDamageMultiplier:0.25

mutatorPlate_ifUnitWithTags:plate
mutatorPlate_areaDamageMultiplier:0.25

areaDamage:50
areaHitAirAndLandAtSameTime:true
areaRadius:15
targetGround:true
targetGround_includeTargetHeight:true
targetGroundSpread:12

initialUnguidedSpeedHeight: 1
gravity:0.18
life: 120
speed: 3
speedSpread:1
image: ROOT:\data\images\arrow.png
explodeEffect: CUSTOM:arrowGround

buildingDamageMultiplier: 0.5
drawSize:0.6
shadowFrame:11
trailEffect:CUSTOM:trail
trailEffectRate:1

[projectile_secondary]
mutatorShield_ifUnitWithTags:shield
mutatorShield_areaDamageMultiplier:0.25

mutatorPlate_ifUnitWithTags:plate
mutatorPlate_areaDamageMultiplier:0.25

areaDamage:50
areaHitAirAndLandAtSameTime:true
areaRadius:15
targetGround:true
targetGround_includeTargetHeight:true
targetGroundSpread:20

armourIgnoreAmount:-8
initialUnguidedSpeedHeight: 1.2
gravity:0.18
life: 120
speed: 4
speedSpread:0.5
image: ROOT:\data\images\arrow.png
explodeEffect: CUSTOM:arrowGround

buildingDamageMultiplier: 0.5
drawSize:0.6
shadowFrame:11
trailEffect:CUSTOM:trail
trailEffectRate:1

[effect_arrowGround]
attachedToUnit: false
life: 1000
scaleFrom:0.4
scaleTo: 0.4
dirOffsetRandom:5
image: ROOT:\data\images\arrowGround.png
drawUnderUnits:true

[effect_trail]
createWhenZoomedOut: false

image: ROOT:\data\images\trail.png
life: 22
fadeOut: true
attachedToUnit: false
fadeInTime:2
scaleFrom: 0.3
scaleTo: 0.2
alpha: 0.6
drawUnderUnits:false

[effect_particles]
attachedToUnit: false
life: 150
physics: true
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.5
hSpeed: 1
image: ROOT:\data\images\particle.png

[effect_sound]
alsoPlaySound: ROOT:\data\soundFx\missile_hit.ogg
life:30
attachedToUnit: false
priority: veryhigh

[movement]
movementType: LAND
moveSpeed: 0.4
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.12
maxTurnSpeed: 2
turnAcceleration: 0.05
moveSlidingMode :false
moveIgnoringBody:false
moveSlidingDir:  181
reverseSpeedPercentage:0



