[core]
copyFrom: ROOT:\data\templates\unitXp.template
name: highpeakDvarikWalker_1
displayText: Ranae
tags:machine, normalVision
displayDescription: -Fast Transport Machine\n -Well armored\n -Adept at scouting\n -Trample damage while it moves \n -Can garrison units\n -Can be refit into a powerful light weapons platform
class: CustomUnitMetadata
price: Emerald=250, Gazul=150, Lodging=1
borrowResourcesWhileBuilt:Lodging=1

maxHp: 300
armour: 7
armourMinDamageToKeep: 1
mass: 3000

maxTransportingUnits:2
transportUnitsRequireTag:infantry, small
transportUnitsCanUnloadUnits:if not self.isOverLiquid()
transportUnitsUnloadDelayBetweenEachUnit:6

techLevel: 1
buildSpeed: 16s
radius: 14
isBio: false
isBug: false
fogOfWarSightRange: 28
hideScorchMark: false
selfRegenRate:0
softCollisionOnAll: 12

################################# Information #################################

[action_dvarikPlated]
iconImage:ROOT:\data\images\plated.png
displayType:action
pos:1
text: Plated
description: Passive\n -This unit is extremely resistant to small projectiles
buildSpeed: 0s
isVisible: if self.tags(includes='plate')

[action_dvarikShield]
iconImage:ROOT:\data\images\shield.png
displayType:action
pos:1
text: Shield
description: Passive\n -This unit is resistant to small projectiles
buildSpeed: 0s
isVisible: if self.tags(includes='shield')

################################# Abilities #################################

[hiddenAction_smoke]
autoTrigger:true
spawnEffects:CUSTOM:smoke*3

[action_refit]
iconImage:ROOT:\data\images\shieldPlus.png
displayType:action
isVisible: true
isLocked: if not self.numberOfUnitsInTeam(withinRange=90, greaterThan=0, withTag='dvarikFactory')
isLockedMessage: Must be close to a Foundry
allowMultipleInQueue: false
whenBuilding_cannotMove: true
ai_isDisabled: true
price: BlackIron=225, lodging=2
text: Refit Ranae
description: -Refit this Ranae into a powerful light weapons platform\n -Loses speed and transport capacity\n -Gains durability and damage
convertTo:highpeakDvarikWalker_3
convertTo_keepCurrentFields: maxHp, moveSpeed
convertTo_keepCurrentTags: true
setUnitStats: maxHp+=75, hp+=75, armour+=3
pos:0.5
addResources: lodging=2
buildSpeed: 30s

[action_blackCladding]
iconImage:ROOT:\data\images\platedPlus.png
displayType:action
isVisible: true
isLocked: if self.resource(type='blackCladdingLayer')>=5
isLockedMessage: Maximum 5 layers
allowMultipleInQueue:false
whenBuilding_cannotMove:true
ai_isDisabled:true
price: BlackIron=75
addResources: blackCladdingLayer=1
setUnitStats: maxHp+=25, hp+=25, moveSpeed-=${ movement.moveSpeed * 0.03 }
text: Black Cladding
description: -Use Black Iron ingots to increase hp by 25\n -New layers of cladding slow down the unit\n -Unit becomes Shielded at 2 layers, and Plated at 4 layers\n -Maximum 5 layers
buildSpeed: 12s
pos: 0.5
spawnEffects: CUSTOM:blackIronUpgrade

[action_bulldozer]
iconImage:ROOT:\data\images\bulldozerIcon.png
displayType:action
isVisible: if not self.tags(includes='bulldozer')
allowMultipleInQueue:false
whenBuilding_cannotMove:true
ai_isDisabled:true
price: BlackIron=225
temporarilyAddTags:bulldozer
text: Bulldozer
description: -Use Black Iron ingots to install bulldozer plate\n -Increases charge damage
buildSpeed: 30s
pos: 0.5
spawnEffects: CUSTOM:blackIronUpgrade

[hiddenAction_claddingShield]
autoTrigger: if self.resource(type='blackCladdingLayer')>=2 and not (self.tags(includes='shield') or self.tags(includes='plate'))
temporarilyAddTags: shield

[hiddenAction_claddingPlate]
autoTrigger: if self.resource(type='blackCladdingLayer')>=4 and not self.tags(includes='plate')
temporarilyAddTags: plate
temporarilyRemoveTags: shield

[hiddenAction_dvarLegsTechTrigger]
autoTrigger:if self.globalTeamTags(includes='dvarikLegsTech') and not self.tags(includes='DvarLegsTech')
setUnitStats: moveSpeed+=${movement.moveSpeed * 0.1}
temporarilyAddTags: DvarLegsTech

################################# Graphics #################################

[graphics]
total_frames: 1
imageScale: 0.9
teamColorsOnTurret: true
image:        body.png
image_wreak:  ROOT:\data\images\medium_dead_wood.png
image_turret: mainTurret.png
image_shadow: AUTO
shadowOffsetX:2
shadowOffsetY:3
showTransportBar:false

movementEffect:CUSTOM:smoke*2
movementEffectRate:10

animation_moving_start: 0
animation_moving_end: 0
animation_moving_speed: 10
animation_moving_scale_start:1
animation_moving_scale_end:1.01

animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 15
animation_idle_scale_start:1
animation_idle_scale_end:1.01

[effect_blackIronUpgrade]
alsoPlaySound:ROOT:\data\soundFx\equipWeapon.ogg:0.15
fadeInTime:10
alwayStartDirAtZero:true
attachedToUnit: true
life: 30
alpha: 1
image: ROOT:\data\images\upgrade.png
priority: high
drawUnderUnits:true
scaleFrom:0.6
scaleTo: 1.4

[effect_arrowGround]
attachedToUnit: false
life: 1000
scaleFrom:0.5
scaleTo: 0.5
#xOffsetAbsoluteRandom:25
#yOffsetAbsoluteRandom:25
dirOffsetRandom:5
image: ROOT:\data\images\dart.png
drawUnderUnits:true

[effect_trail]
createWhenZoomedOut: false
color:#dbc782
image: ROOT:\data\images\trail.png
life: 30
fadeOut: true
attachedToUnit: false
fadeInTime:2
scaleFrom: 0.3
scaleTo: 0.2
alpha: 0.6
drawUnderUnits:false

[effect_smoke]
xOffsetRelative:-8
yOffsetRelative:-13
attachedToUnit: false
life: 150
alpha: 0.5
scaleFrom:0.3
scaleTo: 1.6
xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.1
hSpeed: 0.1
image: ROOT:\data\images\smoke.png
priority: low
drawUnderUnits:false
atmospheric:true

################################# Weapons #################################

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
isFixedFiring:true
aimOffsetSpread:0
turretSize: 11
turretTurnSpeed: 0
maxAttackRange: 100
shootDelay: 2s

[turret_1]
x:0
y:0
canShoot:false
invisible:true

[turret_main]
x:-10
y:0
attachedTo:1
slave:true
shoot_flame:small
shoot_sound: ROOT:\data\soundFx\shootGun.ogg
shoot_sound_vol:0.15
recoilOffset: -3
recoilOutTime: 4
recoilReturnTime: 18
projectile:spawner

[projectile_spawner]
spawnProjectilesOnCreate:1*4
life: 0
speed: 1
drawSize:0
directDamage:0

[projectile_1]
mutatorShield_ifUnitWithTags:shield
mutatorShield_areaDamageMultiplier:0.25

mutatorPlate_ifUnitWithTags:plate
mutatorPlate_areaDamageMultiplier:0.15

areaDamage:35
areaRadius:3
armourIgnoreAmount: -10
areaRadiusFromEdge:true
areaDamageNoFalloff:true
targetGround:true
targetGround_includeTargetHeight:true
targetGroundSpread:12

life: 120
speed: 4
speedSpread:1
image: ROOT:\data\images\dart.png
explodeEffect: CUSTOM:arrowGround
buildingDamageMultiplier: 0.1
drawSize:0.6
shadowFrame:11
trailEffect:CUSTOM:trail
trailEffectRate:1



[hiddenAction_charge]
autoTrigger:if self.isMoving()
fireTurretXAtGround: charge
fireTurretXAtGround_withOffset:0,50

[turret_charge]
x: 0
y: 0
size:0
canShoot:false
invisible: true
projectile: charge
turnSpeed: 40

[projectile_charge]
life: 140
speed: 10
drawSize: 0
targetGround:true
explodeEffect:NONE
deflectionPower: -1
areaDamage: 35
areaRadius: 35
buildingDamageMultiplier:0
mutator1_ifUnitWithTags:shield
mutator1_areaDamageMultiplier:0.5
mutator2_ifUnitWithTags:cavalry
mutator2_areaDamageMultiplier:0



[hiddenAction_bulldozerCharge]
autoTrigger:if self.isMoving() and self.tags(includes='bulldozer')
fireTurretXAtGround: bulldozerCharge
fireTurretXAtGround_withOffset:0,50

[turret_bulldozerCharge]
x: 0
y: 0
size:0
canShoot:false
invisible: true
projectile: bulldozerCharge
turnSpeed: 40

[projectile_bulldozerCharge]
life: 140
speed: 10
drawSize: 0
targetGround:true
explodeEffect:NONE
deflectionPower: -1
areaDamage: 20
areaRadius: 45
buildingDamageMultiplier:1
mutator1_ifUnitWithTags:shield
mutator1_areaDamageMultiplier:0.5
mutator2_ifUnitWithTags:cavalry
mutator2_areaDamageMultiplier:0

################################# Attachments #################################

[attachment_1]
x: 0
y: 6
idleDir:0
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
setDrawLayerOnTop:true
addTransportedUnits:true
rotateWithParent:true

[attachment_2]
x: 0
y: -4
idleDir:0
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
setDrawLayerOnTop:true
addTransportedUnits:true
rotateWithParent:true

################################# Limbs #################################

[arm_1]
x: 0.5
y: 15
drawOverBody:true

[leg_1]
x: -10
y: 4
attach_x: -2
attach_y: 4
rotateSpeed:100
moveSpeed: 3.1
resetAngle:5
heightSpeed: 1
dust_effect: false
holdDisMin: 5
holdDisMax: 15
hardLimit: 15
holdDisMin_maxMovingLegs:1
hold_moveOnlyIfFurthest:true
estimatingPositionMultiplier:0.54
endDirOffset:0
draw_foot_on_top:true
image_leg:  leg.png
image_foot:  foot.png

[leg_2]
x: 10
y: 4
attach_x: 2
attach_y: 4
copyFrom: 1

endDirOffset:0

[leg_3]
x: 0
y: -10
attach_x: 0
attach_y: -2
copyFrom: 1

endDirOffset:180

[arm_9]
hidden: if not self.tags(includes='bulldozer')
x: 0.5
y: 16
drawOverBody:true
image_end:  ROOT:\data\images\bulldozer.png

################################# Movement #################################

[movement]
movementType: OVER_CLIFF
moveSpeed: 1.4
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.06
maxTurnSpeed: 0.8
turnAcceleration: 0.5
moveSlidingMode :true
moveIgnoringBody:false
moveSlidingDir:  181
reverseSpeedPercentage:0