[core]
copyFrom: ROOT:\data\templates\unitXp.template
name: highpeakDvarikDrill_2
displayText: Porcupine
tags:machine, normalVision, bulldozer
displayDescription: -Machine\n -Melee attack\n -Poor into armor\n -Wounds infantry\n -Can garrison a unit
class: CustomUnitMetadata
price: Emerald=350, Gazul=200, Lodging=2
borrowResourcesWhileBuilt:Lodging=2

maxHp: 400
armour: 10
armourMinDamageToKeep: 1
mass: 3000

maxTransportingUnits:1
transportUnitsRequireTag:infantry, small
transportUnitsCanUnloadUnits:if not self.isOverLiquid()
transportUnitsUnloadDelayBetweenEachUnit:1

techLevel: 1
buildSpeed: 16s
radius: 12
softCollisionOnAll: 25
isBio: false
isBug: false
fogOfWarSightRange: 18
hideScorchMark: false
selfRegenRate:0

################################# Information #################################

[action_Wounded]
iconImage:ROOT:\data\images\wounded.png
displayType:action
pos:1
text: Gouge
description: Passive\n -Wounds enemy infantry on attack, slowing them and causing a bleed effect
buildSpeed: 0s
isVisible: true

[action_dvarikPlated]
iconImage:ROOT:\data\images\plated.png
displayType:action
pos:1
text: Plated
description: Passive\n -This unit is extremely resistant to small projectiles
buildSpeed: 0s
isVisible: if self.tags(includes='plate')

[action_dvarikShield]
iconImage:ROOT:\data\images\shield.png
displayType:action
pos:1
text: Shield
description: Passive\n -This unit is resistant to small projectiles
buildSpeed: 0s
isVisible: if self.tags(includes='shield')

################################# Abilities #################################

[action_blackCladding]
iconImage:ROOT:\data\images\platedPlus.png
displayType:action
isVisible: true
isLocked: if self.resource(type='blackCladdingLayer')>=5
isLockedMessage: Maximum 5 layers
allowMultipleInQueue:false
whenBuilding_cannotMove:true
ai_isDisabled:true
price: BlackIron=150
addResources: blackCladdingLayer=1
setUnitStats: maxHp+=30, hp+=30, moveSpeed-=${ movement.moveSpeed * 0.03 }
text: Black Cladding
description: -Use Black Iron ingots to increase hp by 30\n -New layers of cladding slow down the unit\n -Unit becomes Shielded at 2 layers, and Plated at 4 layers\n -Maximum 5 layers
buildSpeed: 20s
pos: 0.5
spawnEffects: CUSTOM:blackIronUpgrade



[hiddenAction_smoke]
autoTrigger:true
spawnEffects:CUSTOM:smoke*3

[hiddenAction_dvarLegsTechTrigger]
autoTrigger:if self.globalTeamTags(includes='dvarikLegsTech') and not self.tags(includes='DvarLegsTech')
setUnitStats: moveSpeed+=${movement.moveSpeed * 0.1}
temporarilyAddTags: DvarLegsTech

[hiddenAction_claddingShield]
autoTrigger: if self.resource(type='blackCladdingLayer')>=2 and not (self.tags(includes='shield') or self.tags(includes='plate'))
temporarilyAddTags: shield

[hiddenAction_claddingPlate]
autoTrigger: if self.resource(type='blackCladdingLayer')>=4 and not self.tags(includes='plate')
temporarilyAddTags: plate
temporarilyRemoveTags: shield

################################# Graphics #################################

[graphics]
total_frames: 1
imageScale: 0.7
teamColorsOnTurret: true
image:        body.png
image_wreak:  ROOT:\data\images\medium_dead_wood.png
image_turret: NONE
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:2
showTransportBar:false

movementEffect:CUSTOM:smoke*2
movementEffectRate:10

animation_moving_start: 0
animation_moving_end: 0
animation_moving_speed: 10
animation_moving_scale_start:1
animation_moving_scale_end:1.01

animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 15
animation_idle_scale_start:1
animation_idle_scale_end:1.01

[effect_smoke]
xOffsetRelative:-8
yOffsetRelative:-13
attachedToUnit: false
life: 150
alpha: 0.5
scaleFrom:0.3
scaleTo: 1.6
xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.1
hSpeed: 0.1
image: ROOT:\data\images\smoke.png
priority: low
drawUnderUnits:false
atmospheric:true



[effect_blackIronUpgrade]
alsoPlaySound:ROOT:\data\soundFx\equipWeapon.ogg:0.15
fadeInTime:10
alwayStartDirAtZero:true
attachedToUnit: true
life: 30
alpha: 1
image: ROOT:\data\images\upgrade.png
priority: high
drawUnderUnits:true
scaleFrom:0.6
scaleTo: 1.4

################################# Weapons #################################

[attack]
canAttack: true
canAttackFlyingUnits: if self.isFlying()
canAttackLandUnits:  if self.isAtGroundHeight()
canAttackUnderwaterUnits: false
isFixedFiring: true
isMelee: true
turretSize: 4
turretTurnSpeed: 3

maxAttackRange: 1
shootDelay: 0.1s

[turret_1]
x:0
y:14
shoot_flame:smoke
shoot_sound: ROOT:\data\soundFx\bigDrill.ogg
shoot_sound_vol:0.2
recoilOffset: 2
recoilOutTime: 1
recoilReturnTime: 30
projectile:1

[projectile_1]
directDamage: 7
areaDamage:8
areaRadius:10
buildingDamageMultiplier:2.0
armourIgnoreAmount:0
life: 10
instant:true
explodeEffect:NONE
mutatorWounded_ifUnitWithTags: infantry
mutatorWounded_addResourcesAreaHit: Wounded=1



[hiddenAction_charge]
autoTrigger:if self.isMoving()
fireTurretXAtGround: charge
fireTurretXAtGround_withOffset:0,25

[turret_charge]
x: 0
y: 0
size:0
canShoot:false
invisible: true
projectile: charge
turnSpeed: 40

[projectile_charge]
life: 140
speed: 10
drawSize: 0
targetGround:true
explodeEffect:NONE
deflectionPower: -1
areaDamage: 30
areaRadius: 45
buildingDamageMultiplier:0
mutator1_ifUnitWithTags:shield
mutator1_areaDamageMultiplier:0.5
mutator2_ifUnitWithTags:cavalry
mutator2_areaDamageMultiplier:0

################################# Attachments #################################

[attachment_1]
x: 0
y: -1
idleDir:0
canBeAttackedAndDamaged:false
keepAliveWhenParentDies:true
setDrawLayerOnTop:true
addTransportedUnits:true
rotateWithParent:true

################################# Limbs #################################

[leg_1]
x: -8
y: 6
attach_x: -5
attach_y: 4
rotateSpeed:100
moveSpeed: 2
resetAngle:5
heightSpeed: 1
dust_effect: true
holdDisMin: 5
holdDisMax: 15
hardLimit: 12
holdDisMin_maxMovingLegs:1
hold_moveOnlyIfFurthest:true
estimatingPositionMultiplier:0.54
endDirOffset:0
draw_foot_on_top:true
image_leg:  leg.png
image_foot:  foot.png

[leg_2]
x: 8
y: 6
attach_x: 5
attach_y: 4
copyFrom: 1

endDirOffset:0

[leg_3]
x: 0
y: -8
attach_x: 0
attach_y: 0
copyFrom: 1

endDirOffset:180



[arm_1]
x: 0
y: 10
drawOverBody:false

[arm_3]
x: 4
y: 10
drawOverBody: false
hidden: false
image_end:  turret.png

[arm_4]
x: -4.5
y: 10
drawOverBody: false
hidden: false
image_end:  turret.png


[arm_2]
hidden: if not self.tags(includes='bulldozer')
drawOverBody: true
x: -0.3
y: 10
image_end:bulldozer.png

################################# Movement #################################

[movement]
movementType: land
moveSpeed: 0.8
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.06
maxTurnSpeed: 1.25
turnAcceleration: 0.5
moveSlidingMode :true
moveIgnoringBody:false
moveSlidingDir:  181
reverseSpeedPercentage:0

[ai]
useAsBuilder:true

################################# Animation #################################

[animation_mine]
onActions : attack

arm3_0s: {y:0}
arm3_0.1s: {y:1}

arm4_0s: {y:0}
arm4_0.1s: {y:1}