
[core]
name: highpeakPlagueOrcNecropolis
tags:canBurn, necropolis, building
class: CustomUnitMetadata
price: Emerald=1200
maxHp: 2200
mass: 9000

displayText: Plaguehouse
displayDescription: "Haven for those who live by the plague."\n\n -Can train defilers and crones


techLevel: 1
buildSpeed: 20s

radius: 35
footprint: -1,-1,1,1
constructionFootprint: -1,-1,1,2
buildingToFootprintOffsetX:10
buildingToFootprintOffsetY:0

isBuilding: true
isBio: false
numBitsOnDeath: 5

exit_y:35

builtFrom_1_name: highpeakPlagueOrcBuilder_1
builtFrom_1_pos: 3

################################# Death #################################

[hiddenAction_spawnLarvas]
autoTriggerOnEvent: destroyed
spawnUnits:highpeakPlagueOrcLarva*3

################################# Abilities #################################

[canBuild_1]
name: setRally, highpeakPlagueOrcDefiler, highpeakPlagueOrcSpellCaster_1
pos: 1.3

[canBuild_2]
name: highpeakPlagueOrcSpellCaster_1
isLocked: if self.numberOfUnitsInTeam(withTag='tech', lessThan=1)
isLockedMessage: Requires a Foul Den
pos: 1.3

################################# Training #################################



################################# Attack #################################

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
canOnlyAttackUnitsWithTags:corpse
turretSize: 0
turretTurnSpeed: 1
maxAttackRange: 0
shootDelay: 2s

################################# Graphics #################################

[graphics]
total_frames: 1
imageScale: 0.7

image:        base.png
image_back:  back.png
image_wreak:  NONE
image_turret: NONE

image_shadow: SHADOW:shadow.png
shadowOffsetX:0
shadowOffsetY:0

################################# Movement #################################

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0
turnAcceleration: 0.1

################################# Ai #################################

[ai]

buildPriority: 0.4

noneInBaseExtraPriority: 0.1

maxEachBase: 1