
[core]
name: highpeakTrollTech
tags:canBurn, building, takePaint
class: CustomUnitMetadata
price: Emerald=750, gazul=400	
maxHp: 4000
mass: 9000

displayText: TrollTech
displayDescription: ""\n\n -Can research technology

techLevel: 1
buildSpeed: 20s

radius: 35
footprint: -1,-1,1,1
constructionFootprint: -1,-1,1,2
buildingToFootprintOffsetX:10
buildingToFootprintOffsetY:0

isBuilding: true
isBio: false
numBitsOnDeath: 5


exit_y:15

################################# Techs #################################

[action_weaponTech]
isVisible: if not self.globalTeamTags(includes='trollWeaponTech')
iconImage:ROOT:\data\images\ranged.png
displayType:action
pos:1
text: Durable Weapons
price: emerald=850, gazul=450
description: Weapons have higher durability
addGlobalTeamTags: trollWeaponTech
buildSpeed: 120s

[action_fireTech]
isVisible: if not self.globalTeamTags(includes='trollFireTech')
iconImage:ROOT:\data\images\ranged.png
displayType:action
pos:1
text: Roaring Bonfire
price: emerald=500, gazul=400
description: Bonfire now damages enemies that get too close
addGlobalTeamTags: trollFireTech
buildSpeed: 60s

[action_menhirTech]
isVisible: if not self.globalTeamTags(includes='trollMenhirTech')
iconImage:ROOT:\data\images\ranged.png
displayType:action
pos:1
text: Ancient Menhir
price: emerald=500, gazul=650
description: Menhir take half as long to age
addGlobalTeamTags: trollMenhirTech
buildSpeed: 120s



[graphics]
total_frames: 1
imageScale: 0.7

image:        base.png
image_back:  back.png
image_wreak:  NONE
image_turret: NONE

image_shadow: SHADOW:shadow.png
shadowOffsetX:0
shadowOffsetY:1



[attack]

canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

turretSize: 8
turretTurnSpeed: 20

maxAttackRange: 125
shootDelay: 1s


[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0
turnAcceleration: 0.1



[ai]

buildPriority: 0.30

noneGlobalExtraPriority: 0.1

maxEachBase: 1