
[core]
copyFrom: ROOT:\data\templates\unitXp.template, ROOT:\data\templates\drowning.template, ROOT:\data\templates\unitInventory.template, ROOT:\data\templates\hero.template
name: highpeakBarbarianHero
tags: bio, infantry, normalVision, hero, cannotConvert
displayText: Chieftain
displayDescription: -Explorer\n -Good vs neutrals\n -Can gather treasures\n -Can level up\n -Can be resurected at the Stone hall\n -Can carry up to 15 trophies\n -Will collect trophies from allies if they cant hold them
class: CustomUnitMetadata
price: Emerald=450
maxHp: 550
selfRegenRate:0
armour:0
mass: 300
radius: 7
softCollisionOnAll: 6

techLevel: 1
experimental: false
buildSpeed: 30s

isBio: true
isBug: false
hideScorchMark: true
effectOnDeath:CUSTOM:death, CUSTOM:blood*3
unitsSpawnedOnDeath:neutralDead

[effect_birth]
fadeInTime:10
attachedToUnit: true
life: 60
alpha: 2
scaleFrom:1.4
scaleTo: 0.2
hSpeed: 0.4
image: ROOT:\data\images\birth.png
priority: high
drawUnderUnits:false


[effect_blood]
attachedToUnit: false
life: 60
physics: true
scaleFrom:1.1
scaleTo: 0.2
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.5
hSpeed: 1
image: ROOT:\data\images\bloodRed.png
drawUnderUnits:false

[hiddenAction_takeTrophy]
autoTriggerOnEvent: killedAnyUnit
requireConditional:if self.resource(type='Trophy', lessThan=1)
addResources: Trophy=1

[hiddenAction_takeTrophy1]
autoTriggerOnEvent: newMessage(withTag='trophyOverflow')
requireConditional:if self.resource(type='Trophy', lessThan=15)
addResources: Trophy=1

[action_trophyInfo]
iconImage:ROOT:\data\images\trophy.png
displayType:action
pos:1
isGuiBlinking:if self.resource(type='Trophy', greaterThan=0)
text: Trophy: %{self.resource.trophy}/15
description: Passive\n -Collect a trophy to boast
buildSpeed: 0s
isVisible: true

[action_sellTrophy]
spawnEffectsOnQueue:CUSTOM:sellTrophy
isVisible: if (numberOfUnitsInTeam(withTag='canSellTrophy', withinRange=110, greaterThan=0) or self.numberOfUnitsInAllyNotOwnTeam(withTag='canSellTrophy', withinRange=110, greaterThan=0)) or self.isControlledByAI()
ai_isDisabled:true
iconImage:ROOT:\data\images\money.png
iconExtraImage:ROOT:\data\images\money.png
addResources: xp=50
displayType: upgrade
price:  trophy=1
text: Boast trophy
description:-Boast and display your trophy for experience\n -Get 50 xp
buildSpeed: 0s
pos:3
[effect_sellTrophy]
alsoPlaySound:ROOT:\data\soundFx\gazul.ogg:0.4

[graphics]
imageScale: 0.95
total_frames: 6
showEnergyBar:false
image:        body.png
image_wreak:  ROOT:\data\images\skeleton.png
image_turret: NONE

image_shadow: SHADOW:ROOT:\data\images\shadow.png
shadowOffsetX:2
shadowOffsetY:3


animation_moving_start: 1
animation_moving_end: 3
animation_moving_speed: 5
animation_moving_pingPong: true

animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 120
animation_idle_scale_start:1
animation_idle_scale_end:1.03
animation_idle_pingPong: true

animation_attack_start: 4
animation_attack_end: 5
animation_attack_speed: 6
animation_attack_pingPong: true

lock_body_rotation_with_main_turret: true


[attack]

canAttack: true
canAttackFlyingUnits: if self.isFlying()
canAttackLandUnits:  if self.isAtGroundHeight()
canAttackUnderwaterUnits: false
isFixedFiring: true
isMelee:true
meleeEngangementDistance:120
turretSize: 8
turretTurnSpeed: 3

maxAttackRange: 8
shootDelay: 1s

[turret_1]
x: 0
y: 0
shoot_sound:ROOT:\data\soundFx\axeHit.ogg, ROOT:\data\soundFx\axeHit2.ogg, ROOT:\data\soundFx\axeHit3.ogg
shoot_sound_vol:0.07
recoilOffset:3
recoilOutTime: 15
recoilReturnTime: 18

[projectile_1]
mutatorNeutral_ifUnitWithTags:neutral
mutatorNeutral_areaDamageMultiplier:2.5

areaDamage: 50
areaRadius:15
armourIgnoreAmount:0
life: 10
instant:true
explodeEffect:NONE

[movement]
movementType: LAND
moveSpeed: 1
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.05
joinsGroupFormations: false

maxTurnSpeed: 8.5
turnAcceleration: 2.5

moveSlidingMode :false
moveIgnoringBody:false
moveSlidingDir:  180
reverseSpeedPercentage:0

[arm_8]
x: 0
y: 0
image_end: ROOT:\data\images\auraHero.png
image_end_teamColors: true
drawUnderAllUnits: true

#-----------------------------------(decals)---------------------------

[decal_trophyOverlay]
isVisible:if self.resource(type='Trophy', greaterThan=0)
imageStack:ROOT:data\images\trophyMarker.png, ROOT:data\images\trophy.png
imageScale: 0.45
hOffset:12
stack_hOffset:0
onlyTeam:own
alwaysStartDirAtZero: true
xOffsetRelative: 0
yOffsetRelative: 0
basePosition: self
layer: beforeUI
alpha: 0.85
onlyWhileAlive: true
onlyWithZoomLevelOrMore: 0.5

[decal_trophyLvl1]
@copyFromSection: decal_trophyOverlay
imageStack:ROOT:data\images\trophyLvl1.png
isVisible:if self.resource(type='TrophyLevel', greaterThan=0)
[decal_trophyLvl2]
@copyFromSection: decal_trophyOverlay
imageStack:ROOT:data\images\trophyLvl2.png
isVisible:if self.resource(type='TrophyLevel', greaterThan=1)
[decal_trophyLvl3]
@copyFromSection: decal_trophyOverlay
imageStack:ROOT:data\images\trophyLvl3.png
isVisible:if self.resource(type='TrophyLevel', greaterThan=2)



