
[core]
name: highpeakPlagueOrcFarm
class: CustomUnitMetadata
tags: canBurn, farm, building, foodResource, Resource, plagueOrcBuilding
price: Emerald=200
maxHp: 650
mass: 9000

displayText: Worm farm
displayDescription: "OooooooHoohoo juicy drippy fleshy meat!"\n\n -Provides food to gather\n -Slowly gathers itself over time\n -Must be build near dropoff buildings

techLevel: 1
buildSpeed: 8s

radius: 22
footprint: -1,-1,0,0
constructionFootprint: -1,-1,0,0
buildingToFootprintOffsetX:0
buildingToFootprintOffsetY:0

disableAllUnitCollisions:true

explodeOnDeath:false
isBuilding: true
isBio: true
numBitsOnDeath: 0

[hiddenAction_onCreate]
autoTriggerOnEvent: completeAndActive
convertTo: highpeakPlagueOrcFarmReady

[hiddenAction_smoke]
autoTrigger:true
spawnEffects:CUSTOM:smoke*3

[effect_smoke]
xOffsetRelativeRandom:10
yOffsetRelativeRandom:10
attachedToUnit: false
life: 400
alpha: 0.3
scaleFrom:1
scaleTo: 2
#physics: true
xSpeedRelativeRandom: 0.07
ySpeedRelativeRandom: 0.07
hSpeed: 0.1
image: ROOT:\data\images\sick.png
priority: low
drawUnderUnits:false
atmospheric:true
fadeInTime:40


[graphics]
total_frames: 1
imageScale: 1

image:        base.png
image_back:  back.png
image_wreak:  NONE
image_turret: NONE

image_shadow: AUTO
shadowOffsetX:0
shadowOffsetY:0.5

animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 120
animation_idle_scale_start:1
animation_idle_scale_end:1.03
animation_idle_pingPong: true


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

turretSize: 0
turretTurnSpeed: 1


maxAttackRange: 1
shootDelay: 2s


[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0
turnAcceleration: 0.1



[ai]

buildPriority: 0.7

noneInBaseExtraPriority: 0.2

recommendedInEachBaseNum:5

[placementRule_All]
searchTags:dropoff
searchTeam:own
searchDistance:65
excludeIncompleteBuildings: true
excludeNonBuildings: true
minCount: 1
blocksPlacement: true
checkEachTile: false
cannotPlaceMessage: Must be near a dropoff building
