
[core]
copyFrom: ROOT:\data\templates\unitXp.template, ROOT:\data\templates\drowning.template
name: highpeakGoblinWarMachine_1
tags: machine, normalVision
displayText: Zapper
displayDescription: -Long ranged machine \n -Insane single target damage\n -Attack has to charge up\n -Extremely poor damage into structures
class: CustomUnitMetadata
price: Emerald=450, Gazoo=350, Lodging=2
borrowResourcesWhileBuilt:Lodging=2
maxHp: 250
armour:8
mass: 1000

techLevel: 1
experimental: false
buildSpeed: 20s

transportSlotsNeeded:2

radius: 12
isBio: false
isBug: false
fogOfWarSightRange: 18
hideScorchMark: true
selfRegenRate:0
softCollisionOnAll: 12
explodeOnDeath:false
effectOnDeath:smoke*3

[hiddenAction_smoke]
autoTrigger:true
spawnEffects:CUSTOM:smoke*2

[effect_smoke]
xOffsetRelative:-3
yOffsetRelative:-9
attachedToUnit: false
life: 100
alpha: 0.2
scaleFrom:0.4
scaleTo: 1.5
#physics: true
xSpeedRelativeRandom: 0.2
ySpeedRelativeRandom: 0.2
hSpeed: 0.1
image: ROOT:\data\images\smokeGazoo.png
priority: low
drawUnderUnits:false
atmospheric:true

[graphics]
teamColorsOnTurret: true
imageScale: 0.9
scaleTurretImagesTo:18
total_frames: 1

image:        body.png
image_wreak:  ROOT:\data\images\rubble.png
image_turret: turret.png

#AUTO
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:2

dustEffect:true

[attack]

canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 0
turretTurnSpeed: 3

maxAttackRange: 250
shootDelay: 1s

[turret_1]
invisible: true
x: 0
y: 5
shoot_sound:lighting_burst
shoot_sound_vol:0.05
shoot_light:#00ffd8
projectile:1
chargeEffectImage:ROOT:\data\images\magicBall.png
warmup: 0.5s
warmupNoReset: true
warmupCallDownRate: 0.85
warmupShootDelayTransfer: 57.5
warmupStartEffect: sparks
turnSpeed: 9999


[turret_2]

x: 0
y: 5
shoot_sound:lighting_burst
shoot_sound_vol:0.05
shoot_light:#00ffd8
projectile:1
idleSpin:2
chargeEffectImage:ROOT:\data\images\magicBall.png

canShoot: false
limitingRange: 1

[projectile_1]

directDamage:4
armourIgnoreAmount:50
life: 4
instant:true
explodeEffect: CUSTOM:sparks*2
buildingDamageMultiplier: 0.25
lightingEffect:true


[effect_sparks]
attachedToUnit: false
life: 150
physics: true
xOffsetRelative: 2
xSpeedRelativeRandom: 0.8
ySpeedRelativeRandom: 0.8
hSpeed: 1.5
image: ROOT:\data\images\spark.png
priority: verylow

[movement]
movementType: LAND
moveSpeed: 0.6
moveAccelerationSpeed: 0.05
moveDecelerationSpeed: 0.01
maxTurnSpeed: 2
turnAcceleration: 0.1
moveSlidingMode :false
moveIgnoringBody:false
moveSlidingDir:  181
reverseSpeedPercentage:0
joinsGroupFormations: true


